name = "match-probability-ai"
main = "src/index.ts"
compatibility_date = "2026-09-03"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "match-probability-ai-db"
database_id = "6da97357-a6cc-471b-86e7-21db19e67d98"
