const SNAPSHOT='https://raw.githubusercontent.com/anonimatoxx11xx-dev/match-probability-ai/main/data/api-football/latest.json';
const BASE='https://site.api.espn.com/apis/site/v2/sports/soccer';
const LEAGUES:any={'eng.1':'Premier League','ita.1':'Serie A','esp.1':'La Liga','ger.1':'Bundesliga','fra.1':'Ligue 1','uefa.champions':'Champions League'};
const LID:any={'Premier League':39,'Serie A':135,'La Liga':140,'Bundesliga':78,'Ligue 1':61,'Champions League':2};
const n=(v:any)=>Number(v??0)||0;
const empty=()=>({matches:0,gf:0,ga:0,hm:0,hgf:0,hga:0,am:0,agf:0,aga:0,shots:0,sot:0,corners:0,fouls:0,saves:0,cards:0});
const canon=(s:any)=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
function add(m:Map<string,any>,k:string,g:number,ga:number,home:boolean,z:any){const s=m.get(k)||empty();s.matches++;s.gf+=g;s.ga+=ga;if(home){s.hm++;s.hgf+=g;s.hga+=ga}else{s.am++;s.agf+=g;s.aga+=ga}s.shots+=n(z.shots);s.sot+=n(z.sot);s.corners+=n(z.corners);s.fouls+=n(z.fouls);s.saves+=n(z.saves);s.cards+=n(z.cards);m.set(k,s)}
function maps(s:any){const all=new Map<string,any>();for(const f of s.fixtures||[]){if(f?.goals?.home==null||f?.goals?.away==null)continue;const h=n(f.home?.id),a=n(f.away?.id);if(!h||!a)continue;add(all,String(h),n(f.goals.home),n(f.goals.away),true,f.stats?.home||{});add(all,String(a),n(f.goals.away),n(f.goals.home),false,f.stats?.away||{})}return all}
function team(s:any,name:string){const w=canon(name).split(' ').filter(x=>x.length>2);let best:any=null,score=0;for(const t of s.teams||[]){const g=canon(t.name).split(' ');const hit=w.filter(x=>g.includes(x)).length;const q=Math.max(w.length,g.length)?hit/Math.max(w.length,g.length):0;if(q>score){score=q;best=t}}return score>=.5?best:null}
function pois(l:number,k:number){let p=Math.exp(-l);for(let i=1;i<=k;i++)p*=l/i;return p}
function predict(h:any,a:any){const hw=h.matches?h.hm/(h.matches+8):.5,aw=a.matches?a.am/(a.matches+8):.5;const hgf=h.hm?h.hgf/h.hm:1.35,hga=h.hm?h.hga/h.hm:1.35,agf=a.am?a.agf/a.am:1.15,aga=a.am?a.aga/a.am:1.15;const lh=Math.max(.2,Math.min(3.8,((hgf*.55+(h.matches?h.gf/h.matches:1.35)*.45)*hw+(aga*.45+(a.matches?a.ga/a.matches:1.15)*.55)*aw)*1.05));const la=Math.max(.15,Math.min(3.5,((agf*.55+(a.matches?a.gf/a.matches:1.15)*.45)*aw+(hga*.45+(h.matches?h.ga/h.matches:1.35)*.55)*hw)*.95));const ph=Array.from({length:9},(_,k)=>pois(lh,k)),pa=Array.from({length:9},(_,k)=>pois(la,k)),sh=ph.reduce((x,y)=>x+y,0),sa=pa.reduce((x,y)=>x+y,0);let home=0,draw=0,away=0;const sum=(fn:(i:number,j:number)=>boolean)=>{let z=0;for(let i=0;i<9;i++)for(let j=0;j<9;j++)if(fn(i,j))z+=ph[i]/sh*pa[j]/sa;return z};for(let i=0;i<9;i++)for(let j=0;j<9;j++){const p=ph[i]/sh*pa[j]/sa;if(i>j)home+=p;else if(i===j)draw+=p;else away+=p}const min=Math.min(h.matches,a.matches),rel=Math.max(.35,Math.min(1,.35+Math.min(min,20)/20*.65));return{expectedGoals:{home:lh,away:la,total:lh+la},result:{home,draw,away},doubleChance:{'1X':home+draw,X2:draw+away,'12':home+away},drawNoBet:{home:home/(home+away||1),away:away/(home+away||1)},markets:{over05:sum((i,j)=>i+j>=1),under05:sum((i,j)=>i+j<1),over15:sum((i,j)=>i+j>=2),under15:sum((i,j)=>i+j<2),over25:sum((i,j)=>i+j>=3),under25:sum((i,j)=>i+j<3),over35:sum((i,j)=>i+j>=4),under35:sum((i,j)=>i+j<4),over45:sum((i,j)=>i+j>=5),under45:sum((i,j)=>i+j<5),bttsYes:sum((i,j)=>i>0&&j>0),bttsNo:sum((i,j)=>i===0||j===0)},correctScores:[],expectedStats:{shots:h.matches&&a.matches?h.shots/h.matches+a.shots/a.matches:null,sot:h.matches&&a.matches?h.sot/h.matches+a.sot/a.matches:null,corners:h.matches&&a.matches?h.corners/h.matches+a.corners/a.matches:null,fouls:h.matches&&a.matches?h.fouls/h.matches+a.fouls/a.matches:null,saves:h.matches&&a.matches?h.saves/h.matches+a.saves/a.matches:null,cards:h.matches&&a.matches?h.cards/h.matches+a.cards/a.matches:null},dataQuality:{homeMatches:h.matches,awayMatches:a.matches,minMatches:min,reliability:rel},reliability:rel}}
function dateRome(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return `${p.find(x=>x.type==='year')?.value}-${p.find(x=>x.type==='month')?.value}-${p.find(x=>x.type==='day')?.value}`}
async function get(u:string){const r=await fetch(u,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
export default async function handler(req:any,res:any){try{const date=dateRome(),d=date.replace(/-/g,''),s=await get(SNAPSHOT),mm=maps(s),out:any[]=[];for(const slug of Object.keys(LEAGUES)){try{const x=await get(`${BASE}/${slug}/scoreboard?dates=${d}`);for(const e of x.events||[]){const c=e.competitions?.[0],cs=c?.competitors||[],hh=cs.find((z:any)=>z.homeAway==='home'),aa=cs.find((z:any)=>z.homeAway==='away');if(!hh||!aa)continue;const hn=hh.team?.displayName||hh.team?.name,an=aa.team?.displayName||aa.team?.name,ht=team(s,hn),at=team(s,an),h=mm.get(String(ht?.apiId))||empty(),a=mm.get(String(at?.apiId))||empty();out.push({fixtureId:String(e.id),date:e.date,league:{name:LEAGUES[slug]},status:c.status?.type?.description||'Scheduled',home:{name:hn},away:{name:an},prediction:predict(h,a)})}}catch(e){console.error('ESPN',slug,e)}}if(!out.length)throw new Error('Nessuna partita disponibile per oggi');res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');res.status(200).json({ok:true,date,timezone:'Europe/Rome',source:'ESPN',matches:out.length,fixtures:out,historyAvailable:Boolean(s.generatedAt)})}catch(e:any){console.error('TODAY_APP_FAILED',e);res.status(500).json({ok:false,error:String(e?.message||e),code:'TODAY_APP_FAILED'})}}