const S='https://api.sofascore.com/api/v1';
const E='https://site.api.espn.com/apis/site/v2/sports/soccer';
const EW='https://site.web.api.espn.com/apis/site/v2/sports/soccer';
const cache=new Map();const headers={Accept:'application/json'};
const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|afc|sk|club|cf|fk|sc|ac|as|sv|bk|kv)\b/g,'').replace(/[^a-z0-9]/g,'');
const same=(a,b)=>{const x=norm(a),y=norm(b);return!!x&&!!y&&(x===y||x.includes(y)||y.includes(x))};
const n=x=>{if(x&&typeof x==='object')x=x.current??x.normaltime??x.displayValue??x.value??x.score;if(typeof x==='string'&&x.includes('/'))x=x.split('/')[0];const m=String(x??'').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null};
const get=async u=>{if(cache.has(u))return cache.get(u);const p=(async()=>{try{const r=await fetch(u,{headers});if(!r.ok)return null;return await r.json()}catch{return null}})();cache.set(u,p);return p};
const finished=e=>['finished','ended','afterpenalties','afterextra'].includes(String(e?.status?.type||e?.status?.type?.name||'').toLowerCase())||e?.status?.type?.completed===true;
const leagueCode=slug=>{const s=String(slug||'').toLowerCase();const m={'j1-league':'jpn.1','j-league':'jpn.1','j2-league':'jpn.2','russian-premier-league':'rus.1','saudi-pro-league':'ksa.1','premier-league':'eng.1','english-premier-league':'eng.1','english-championship':'eng.2','championship':'eng.2','league-one':'eng.3','league-two':'eng.4','la-liga':'esp.1','spanish-laliga':'esp.1','bundesliga':'ger.1','2-bundesliga':'ger.2','serie-a':'ita.1','serie-b':'ita.2','ligue-1':'fra.1','ligue-2':'fra.2','eredivisie':'ned.1','keuken-kampioen-divisie':'ned.2','belgian-pro-league':'bel.1','primeira-liga':'por.1','scottish-premiership':'sco.1','turkish-super-lig':'tur.1','greek-super-league':'gre.1','danish-superliga':'den.1','swedish-allsvenskan':'swe.1','norwegian-eliteserien':'nor.1','austrian-bundesliga':'aut.1','mls':'usa.1','liga-mx':'mex.1','mexican-liga-bbva-mx':'mex.1','brasileirao':'bra.1','argentine-liga-profesional':'arg.1','colombian-primera-a':'col.1','chinese-super-league':'chn.1','a-league-men':'aus.1','korean-k-league-1':'kor.1','indian-super-league':'ind.1','south-african-premiership':'rsa.1'};for(const k of Object.keys(m))if(s.includes(k))return m[k];return null};
function sofaRows(events,name){return(events||[]).filter(finished).map(e=>{const h=e?.homeTeam?.name,a=e?.awayTeam?.name,hg=n(e?.homeScore),ag=n(e?.awayScore);if(!h||!a||hg==null||ag==null)return null;const home=same(h,name),away=same(a,name);if(!home&&!away)return null;return{id:'sofa-'+e.id,eventId:String(e.id),team:name,opp:home?a:h,home,gf:home?hg:ag,ga:home?ag:hg,time:e.startTimestamp?new Date(e.startTimestamp*1000).toISOString():e.startTime||'',sofaEvent:e}}).filter(Boolean)}
function espnRows(j,name){return(j?.events||[]).filter(finished).map(e=>{const c=e.competitions?.[0]?.competitors||[],h=c.find(x=>x.homeAway==='home')||c[0],a=c.find(x=>x.homeAway==='away')||c[1],hs=n(h?.score),as=n(a?.score);if(!h?.team?.displayName||!a?.team?.displayName||hs==null||as==null)return null;const home=same(h.team.displayName,name),away=same(a.team.displayName,name);if(!home&&!away)return null;return{id:'espn-'+e.id,eventId:String(e.id),team:name,opp:home?a.team.displayName:h.team.displayName,home,gf:home?hs:as,ga:home?as:hs,time:e.date||'',espnEventId:String(e.id),seasonSlug:e.season?.slug||'',espnEvent:e}}).filter(Boolean)}
async function teamHistory(name,ids,slug){const out=[];if(ids?.sofaId){const pages=await Promise.all(Array.from({length:8},(_,p)=>get(`${S}/team/${ids.sofaId}/events/last/${p}`)));out.push(...pages.flatMap(x=>sofaRows(x?.events,name)))}if(ids?.espnId){const code=leagueCode(slug);if(code){let j=await get(`${E}/${code}/teams/${ids.espnId}/schedule`);if(!j?.events?.length)j=await get(`${EW}/${code}/teams/${ids.espnId}/schedule`);out.push(...espnRows(j,name))}}const map=new Map();for(const x of out)if(!map.has(x.eventId))map.set(x.eventId,x);return[...map.values()].sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,30)}
async function sofaSearch(name){const j=await get(`${S}/search/all?q=${encodeURIComponent(name)}`);const rows=(j?.results||[]).filter(x=>String(x.entity?.type||'').toLowerCase()==='team');const hit=rows.find(x=>same(x.entity?.name,name))||rows[0];return hit?.entity?.id||null}
async function espnSearch(name){const j=await get(`https://site.api.espn.com/apis/search/v2?query=${encodeURIComponent(name)}&limit=20`);const rows=j?.results||[];const hit=rows.find(x=>same(x?.contents?.[0]?.displayName,name))||rows.find(x=>same(x?.contents?.[0]?.name,name));return hit?.contents?.[0]?.uid?.split('~').pop()||hit?.contents?.[0]?.id||null}
async function idsFor(match,side){const sofaId=side==='home'?match.sofaIdHome:match.sofaIdAway;const espnId=side==='home'?match.espnIdHome:match.espnIdAway;const name=side==='home'?match.home:match.away;return{sofaId:sofaId||await sofaSearch(name),espnId:espnId||await espnSearch(name)}}
function statKey(v){const t=String(v||'').toLowerCase().replace(/[_-]/g,' ');if(/total shots|shot attempts|^shots$/.test(t))return'shots';if(/shot.*target|on target|on goal/.test(t))return'shotsOnTarget';if(/corner/.test(t))return'corners';if(/foul/.test(t))return'fouls';if(/yellow|booking|caution/.test(t))return'yellow';if(/offside/.test(t))return'offsides';if(/throw.?in/.test(t))return'throwIns';if(/save/.test(t))return'saves';return null}
async function eventStats(row,team){if(row.id?.startsWith('sofa-')){const j=await get(`${S}/event/${row.eventId}/statistics`);const groups=(j?.statistics||[]).find(x=>String(x.period).toUpperCase()==='ALL')?.groups||[];const h=j?.event?.homeTeam?.name||row.sofaEvent?.homeTeam?.name||'',a=j?.event?.awayTeam?.name||row.sofaEvent?.awayTeam?.name||'',data={};for(const g of groups)for(const r of g.statisticsItems||[]){const k=statKey(r.key||r.name||r.title),hv=n(r.homeValue??r.home),av=n(r.awayValue??r.away);if(k&&hv!=null&&av!=null)data[k]=same(h,team)?hv:same(a,team)?av:null}return data}return{}}
export async function analyzeMatch(match){const [hi,ai]=await Promise.all([idsFor(match,'home'),idsFor(match,'away')]);const [hf,af]=await Promise.all([teamHistory(match.home,hi,match.espnSeasonSlug),teamHistory(match.away,ai,match.espnSeasonSlug)]);const h2hMap=new Map();for(const x of [...hf.filter(x=>same(x.opp,match.away)),...af.filter(x=>same(x.opp,match.home))])if(!h2hMap.has(x.eventId))h2hMap.set(x.eventId,{...x,h2h:true});const h2hRows=[...h2hMap.values()].sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,15);const homeRows=[...h2hRows,...hf.filter(x=>!h2hMap.has(x.eventId))].slice(0,16);const awayRows=[...h2hRows.map(x=>({...x,team:match.away,opp:match.home,home:!x.home,gf:x.ga,ga:x.gf})),...af.filter(x=>!h2hMap.has(x.eventId))].slice(0,16);const targets=[...new Map([...h2hRows,...hf.slice(0,5),...af.slice(0,5)].map(x=>[x.eventId,x])).values()].slice(0,10);const stats=await Promise.all(targets.map(x=>eventStats(x,match.home)));const map=new Map(targets.map((x,i)=>[x.eventId,stats[i]]));const hs=homeRows.map(x=>({...x,data:map.get(x.eventId)||{}}));const as=awayRows.map(x=>({...x,data:map.get(x.eventId)||{}}));const verified=[...map.values()].filter(x=>Object.keys(x).length).length;return{...match,homeData:{sofaId:hi.sofaId,espnId:hi.espnId},awayData:{sofaId:ai.sofaId,espnId:ai.espnId},H:{form:homeRows,stats:hs},A:{form:awayRows,stats:as},h2h:h2hRows,h2hCount:h2hRows.length,verifiedStats:verified,loading:false}}
export function clearAnalysisCache(){cache.clear()}
