const S='https://api.sofascore.com/api/v1';
const F='https://www.fotmob.com/api';
const E='https://site.api.espn.com/apis/site/v2/sports/soccer';
const EW='https://site.web.api.espn.com/apis/site/v2/sports/soccer';
const EC='https://sports.core.api.espn.com/v2/sports/soccer';
const cache=new Map();const headers={Accept:'application/json','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36'};
const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|afc|sk|club|cf|fk|sc|ac|as|sv|bk|kv)\b/g,'').replace(/[^a-z0-9]/g,'');
const same=(a,b)=>{const x=norm(a),y=norm(b);if(!x||!y)return false;if(x===y||x.includes(y)||y.includes(x))return true;const ax=x.replace(/(.)\1+/g,'$1'),ay=y.replace(/(.)\1+/g,'$1');return ax===ay||ax.includes(ay)||ay.includes(ax)};
const n=x=>{if(x&&typeof x==='object')x=x.current??x.normaltime??x.displayValue??x.value??x.score;if(typeof x==='string'&&x.includes('/'))x=x.split('/')[0];const m=String(x??'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null};
const get=async u=>{if(cache.has(u))return cache.get(u);const p=(async()=>{try{const r=await fetch(u,{headers});if(!r.ok)return null;return await r.json()}catch{return null}})();cache.set(u,p);return p};
const finished=e=>e?.status?.finished===true||['finished','ended','afterpenalties','afterextra','ft'].includes(String(e?.status?.type||e?.status?.reason||e?.status?.short||'').toLowerCase())||e?.status?.type?.completed===true;
const leagueCode=slug=>{const s=String(slug||'').toLowerCase();const m={'j1-league':'jpn.1','russian-premier-league':'rus.1','saudi-pro-league':'ksa.1','premier-league':'eng.1','la-liga':'esp.1','bundesliga':'ger.1','serie-a':'ita.1','ligue-1':'fra.1','eredivisie':'ned.1','turkish-super-lig':'tur.1','mls':'usa.1','liga-mx':'mex.1'};for(const k of Object.keys(m))if(s.includes(k))return m[k];return null};
const day=x=>x.toISOString().slice(0,10).replaceAll('-','');
function sofaRows(events,name){return(events||[]).filter(finished).map(e=>{const h=e?.homeTeam?.name,a=e?.awayTeam?.name,hg=n(e?.homeScore),ag=n(e?.awayScore);if(!h||!a)return null;const home=same(h,name),away=same(a,name);if(!home&&!away)return null;return{id:'sofa-'+e.id,eventId:String(e.id),team:name,opp:home?a:h,home,gf:hg==null?null:(home?hg:ag),ga:ag==null?null:(home?ag:hg),time:e.startTimestamp?new Date(e.startTimestamp*1000).toISOString():e.startTime||'',sofaEvent:e}}).filter(Boolean)}
function espnRows(j,name){return(j?.events||[]).filter(finished).map(e=>{const c=e.competitions?.[0]?.competitors||[],h=c.find(x=>x.homeAway==='home')||c[0],a=c.find(x=>x.homeAway==='away')||c[1],hs=n(h?.score),as=n(a?.score);if(!h?.team?.displayName||!a?.team?.displayName)return null;const home=same(h.team.displayName,name),away=same(a.team.displayName,name);if(!home&&!away)return null;return{id:'espn-'+e.id,eventId:String(e.id),team:name,opp:home?a.team.displayName:h.team.displayName,home,gf:home?hs:as,ga:home?as:hs,time:e.date||'',espnEventId:String(e.id),seasonSlug:e.season?.slug||'',espnEvent:e}}).filter(Boolean)}
async function leagueRecent(code,name){if(!code)return[];const end=new Date(),start=new Date(end.getTime()-120*86400000);const u=`${E}/${code}/scoreboard?limit=500&dates=${day(start)}-${day(end)}`;return espnRows(await get(u),name)}
async function leagueH2H(code,home,away){if(!code)return[];const end=new Date(),start=new Date(end.getTime()-360*86400000);const u=`${E}/${code}/scoreboard?limit=1000&dates=${day(start)}-${day(end)}`;const j=await get(u);return(j?.events||[]).filter(finished).map(e=>{const c=e.competitions?.[0]?.competitors||[],h=c.find(x=>x.homeAway==='home')?.team?.displayName||c[0]?.team?.displayName,a=c.find(x=>x.homeAway==='away')?.team?.displayName||c[1]?.team?.displayName;if(!h||!a||!((same(h,home)&&same(a,away))||(same(h,away)&&same(a,home))))return null;const hc=c.find(x=>x.homeAway==='home'),ac=c.find(x=>x.homeAway==='away');return{id:'espn-h2h-'+e.id,eventId:String(e.id),team:home,opp:away,home:same(h,home),gf:n(hc?.score),ga:n(ac?.score),time:e.date||'',h2h:true,espnEvent:e}}).filter(Boolean)}
function fotName(v){return typeof v==='string'?v:v?.name||v?.shortName||v?.cname||''}
function fotScore(v){return n(v?.score??v?.displayScore??v?.goals??v)}
function fotFixtureRows(j,name){const arr=j?.fixtures?.allFixtures?.fixtures||j?.fixtures?.fixtures||j?.fixtures?.allFixtures||j?.matches||[];return(arr||[]).map(e=>{const h=fotName(e?.home),a=fotName(e?.away);if(!h||!a||!e?.id)return null;const home=same(h,name),away=same(a,name);if(!home&&!away)return null;const hs=fotScore(e?.home),as=fotScore(e?.away),tm=e?.status?.utcTime||e?.matchDate||e?.date||e?.time||e?.startTime||'';const past=tm&&new Date(tm).getTime()<Date.now();if(!finished(e)&&!past)return null;return{id:'fot-'+e.id,eventId:String(e.id),fotId:String(e.id),team:name,opp:home?a:h,home,gf:home?hs:as,ga:home?as:hs,time:tm,league:e?.tournament?.name||e?.league?.name||'',fotEvent:e}}).filter(Boolean)}
function searchTeamRows(j){const out=[];const walk=v=>{if(!v||typeof v!=='object')return;if(Array.isArray(v)){for(const x of v)walk(x);return}const id=v?.entity?.id??v?.id,name=v?.entity?.name??v?.name??v?.title,type=String(v?.entity?.type??v?.type??'').toLowerCase();if(id&&name&&(type==='team'||v?.entity?.type==='team'))out.push({id,name});for(const k of Object.keys(v))if(k!=='image'&&k!=='logo')walk(v[k])};walk(j);return out}
async function fotSearch(name){const a=await get(`${F}/data/search/suggest?term=${encodeURIComponent(name)}&hits=50&lang=en`);let rows=searchTeamRows(a);if(!rows.length){const b=await get(`${F}/search/suggest?term=${encodeURIComponent(name)}&hits=50&lang=en`);rows=searchTeamRows(b)}if(!rows.length){const c=await get(`${F}/searchData?term=${encodeURIComponent(name)}`);rows=searchTeamRows(c)}const hit=rows.find(x=>same(x.name,name))||rows[0];return hit?.id||null}
async function fotTeamHistory(id,name){if(!id)return[];const j=await get(`${F}/teams?id=${id}&tab=overview`);let rows=fotFixtureRows(j,name);if(!rows.length){const k=await get(`${F}/teams?id=${id}&tab=fixtures`);rows=fotFixtureRows(k,name)}if(rows.length)return rows;const fallback=j?.overview?.form||[];return fallback.map((x,i)=>{const opp=x?.opponent||x?.opponentName;if(!opp)return null;const parts=String(x?.score||'').split(/[-–]/).map(Number);return{id:`fot-form-${id}-${i}`,eventId:`fot-form-${id}-${i}`,fotId:null,team:name,opp,home:true,gf:Number.isFinite(parts[0])?parts[0]:null,ga:Number.isFinite(parts[1])?parts[1]:null,time:new Date(Date.now()-i*86400000).toISOString(),league:'',fotEvent:x}}).filter(Boolean)}
async function fotH2H(matchId,home,away){if(!matchId)return[];const j=await get(`${F}/matchDetails?matchId=${matchId}`);const rows=j?.content?.h2h?.matches||j?.h2h?.matches||[];return rows.map(e=>{const h=fotName(e?.home||e?.homeTeam),a=fotName(e?.away||e?.awayTeam);if(!h||!a||(!same(h,home)&&!same(a,home)))return null;const hs=fotScore(e?.homeScore??e?.home?.score),as=fotScore(e?.awayScore??e?.away?.score);return{id:'fot-h2h-'+e.id,eventId:String(e.id),team:home,opp:away,home:same(h,home),gf:hs,ga:as,time:e?.matchDate||e?.status?.utcTime||e?.date||'',h2h:true,fotEvent:e}}).filter(Boolean)}
async function sofaH2H(eventId,home,away){if(!eventId)return[];const j=await get(`${S}/event/${eventId}/h2h/events`);const rows=j?.events||[];return rows.map(e=>{const h=e?.homeTeam?.name,a=e?.awayTeam?.name;if(!h||!a||(!same(h,home)||!same(a,away))&&(!same(h,away)||!same(a,home)))return null;return{id:'sofa-h2h-'+e.id,eventId:String(e.id),team:home,opp:away,home:same(h,home),gf:n(e?.homeScore),ga:n(e?.awayScore),time:e.startTimestamp?new Date(e.startTimestamp*1000).toISOString():e.startTime||'',h2h:true,sofaEvent:e}}).filter(Boolean)}
async function coreEvents(id,name){const j=await get(`${EC}/teams/${id}/events?limit=100`);let items=j?.events||j?.items||[];if(items.length&&items[0]?.$ref)items=(await Promise.all(items.slice(0,60).map(x=>get(x.$ref)))).filter(Boolean);return espnRows({events:items},name)}
async function teamHistory(name,ids,slug){const out=[];const code=leagueCode(slug);if(code)out.push(...await leagueRecent(code,name));if(ids?.espnId&&!out.length){let j=await get(`${EW}/all/teams/${ids.espnId}/schedule`);if(!j?.events?.length)j=await get(`${E}/all/teams/${ids.espnId}/schedule`);out.push(...espnRows(j,name));if(!out.length)out.push(...await coreEvents(ids.espnId,name))}if(ids?.fotId&&!out.length)out.push(...await fotTeamHistory(ids.fotId,name));if(ids?.sofaId&&!out.length){const pages=await Promise.all(Array.from({length:8},(_,p)=>get(`${S}/team/${ids.sofaId}/events/last/${p}`)));out.push(...pages.flatMap(x=>sofaRows(x?.events,name)))}const map=new Map();for(const x of out)if(!map.has(x.eventId))map.set(x.eventId,x);return[...map.values()].sort((a,b)=>new Date(b.time||0)-new Date(a.time||0)).slice(0,30)}
async function sofaSearch(name){const j=await get(`${S}/search/all?q=${encodeURIComponent(name)}`);const rows=(j?.results||[]).filter(x=>String(x.entity?.type||'').toLowerCase()==='team');const hit=rows.find(x=>same(x.entity?.name,name))||rows[0];return hit?.entity?.id||null}
async function espnSearch(name){const j=await get(`https://site.api.espn.com/apis/search/v2?query=${encodeURIComponent(name)}&limit=20`);const rows=j?.results||[];const hit=rows.find(x=>same(x?.contents?.[0]?.displayName,name))||rows.find(x=>same(x?.contents?.[0]?.name,name));return hit?.contents?.[0]?.uid?.split('~').pop()||hit?.contents?.[0]?.id||null}
async function idsFor(match,side){const sofaId=side==='home'?match.sofaIdHome:match.sofaIdAway;const espnId=side==='home'?match.espnIdHome:match.espnIdAway;const fotId=side==='home'?match.fotIdHome:match.fotIdAway;const name=side==='home'?match.home:match.away;return{sofaId:sofaId||await sofaSearch(name),espnId:espnId||await espnSearch(name),fotId:fotId||await fotSearch(name)}}
export async function analyzeMatch(match){const [hi,ai]=await Promise.all([idsFor(match,'home'),idsFor(match,'away')]);const code=leagueCode(match.espnSeasonSlug);const [hf,af,sh2h,lh2h]=await Promise.all([teamHistory(match.home,hi,match.espnSeasonSlug),teamHistory(match.away,ai,match.espnSeasonSlug),sofaH2H(match.sofaEventId,match.home,match.away),leagueH2H(code,match.home,match.away)]);let h2hRows=[...sh2h,...lh2h];if(match.fotId&&!h2hRows.length)h2hRows=await fotH2H(match.fotId,match.home,match.away);const h2hMap=new Map();for(const x of [...h2hRows,...hf.filter(x=>same(x.opp,match.away)),...af.filter(x=>same(x.opp,match.home))])if(!h2hMap.has(x.eventId))h2hMap.set(x.eventId,{...x,h2h:true});h2hRows=[...h2hMap.values()].sort((a,b)=>new Date(b.time||0)-new Date(a.time||0)).slice(0,15);const homeRows=[...h2hRows,...hf.filter(x=>!h2hMap.has(x.eventId))].slice(0,16);const awayRows=[...h2hRows.map(x=>({...x,team:match.away,opp:match.home,home:!x.home,gf:x.ga,ga:x.gf})),...af.filter(x=>!h2hMap.has(x.eventId))].slice(0,16);return{...match,homeData:{sofaId:hi.sofaId,espnId:hi.espnId,fotId:hi.fotId},awayData:{sofaId:ai.sofaId,espnId:ai.espnId,fotId:ai.fotId},H:{form:homeRows,stats:homeRows},A:{form:awayRows,stats:awayRows},h2h:h2hRows,h2hCount:h2hRows.length,verifiedStats:0,loading:false}}
export function clearAnalysisCache(){cache.clear()}
