import { todayMatches as rawTodayMatches } from './provider-engine.js';
const S='https://api.sofascore.com/api/v1';
const cache=new Map();
const headers={Accept:'application/json','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36'};
const get=async u=>{if(cache.has(u))return cache.get(u);const p=(async()=>{try{const r=await fetch(u,{headers});if(!r.ok)return null;return await r.json()}catch{return null}})();cache.set(u,p);return p};
const competition=e=>{const t=e?.tournament||{},u=t?.uniqueTournament||t?.uniqueTournamentInfo;return u?.name||t?.name||u?.slug||t?.slug||e?.season?.name||'Altra competizione'};
const mapEvent=e=>e?{league:competition(e),country:e?.tournament?.category?.name||'',sofaIdHome:e?.homeTeam?.id||null,sofaIdAway:e?.awayTeam?.id||null}:null;
const enrichBatch=async rows=>{const out=new Map();for(let i=0;i<rows.length;i+=20){const batch=rows.slice(i,i+20);const vals=await Promise.all(batch.map(x=>get(`${S}/event/${x.eventId}`)));vals.forEach((j,k)=>{const d=mapEvent(j?.event);if(d&&d.league!=='Altra competizione')out.set(batch[k].eventId,d)})}return out};
const recoverFromTeams=async rows=>{const out=new Map();for(let i=0;i<rows.length;i+=20){const batch=rows.slice(i,i+20);const vals=await Promise.all(batch.map(x=>x.sofaIdHome?get(`${S}/team/${x.sofaIdHome}/events/next/0`):Promise.resolve(null)));vals.forEach((j,k)=>{const target=batch[k],e=(j?.events||[]).find(v=>String(v.id)===String(target.eventId));const d=mapEvent(e);if(d&&d.league!=='Altra competizione')out.set(target.eventId,d)})}return out};
export async function todayMatches(date){const rows=await rawTodayMatches(date);const missing=rows.filter(x=>!x.league||x.league==='Calcio'||x.league==='Altra competizione');const byId=await enrichBatch(missing);const still=missing.filter(x=>!byId.has(x.eventId)&&x.sofaIdHome);const recovered=await recoverFromTeams(still);for(const [k,v] of recovered)byId.set(k,v);return rows.map(x=>{const d=byId.get(x.eventId);return d?{...x,...d}:x}).map(x=>({...x,league:x.league&&x.league!=='Calcio'?x.league:'Altra competizione'}));}
