import './style.css';

const app=document.querySelector('#app');
const FOT='https://www.fotmob.com';
const SOFA='https://www.sofascore.com/api/v1';
const ESPN='https://site.api.espn.com/apis/site/v2/sports/soccer/all';
const TSDB='https://www.thesportsdb.com/api/v1/json/123';
const OPEN='https://api.openligadb.de';
const state={loading:false,fixtures:[],source:'',error:null};

const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const pct=x=>`${(Number(x||0)*100).toFixed(1)}%`;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const num=x=>{if(x&&typeof x==='object'){if(x.value!==undefined)return num(x.value);if(x.displayValue!==undefined)return num(x.displayValue);if(x.homeValue!==undefined)return num(x.homeValue);}const m=String(x??'').replace(',','.').match(/-?\d+(?:\.\d+)?/);const n=m?Number(m[0]):NaN;return Number.isFinite(n)?n:null};
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|afc|sk|club|calcio|rotterdam|cf|fk|sc|ac|as)\b/g,'').replace(/[^a-z0-9]/g,'');
const same=(a,b)=>{const x=norm(a),y=norm(b);return !!x&&!!y&&(x===y||x.includes(y)||y.includes(x));};
const isoDay=d=>{const x=new Date(d);return Number.isNaN(x.getTime())?null:x.toISOString().slice(0,10)};
function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${o.year}${o.month}${o.day}`;}
function todayIso(){const s=today();return `${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6)}`;}
async function get(url){const r=await fetch(url,{headers:{Accept:'application/json'}});const t=await r.text();let d;try{d=JSON.parse(t)}catch{throw new Error(`JSON non valido ${r.status}`)}if(!r.ok)throw new Error(`${r.status} ${url}`);return d;}
function empty(){return{n:0,gf:0,ga:0,results:[],stats:[],statSummary:{},statSource:'N/D'};}
function add(form,gf,ga,home,id,time,opp){if(!Number.isFinite(gf)||!Number.isFinite(ga))return;form.n++;form.gf+=gf;form.ga+=ga;form.results.push({gf,ga,home,matchId:String(id),utcTime:time||null,opponent:opp||''});}
function fact(n){let x=1;for(let i=2;i<=n;i++)x*=i;return x;}
function poisson(k,l){return Math.exp(-l)*Math.pow(l,k)/fact(k);}
function prediction(h,a){let lh=1.52,la=1.12;if(h.n)lh=.45*lh+.55*((h.gf/h.n)*.72+(a.n?(a.ga/a.n)*.28:1.1));if(a.n)la=.45*la+.55*((a.gf/a.n)*.72+(h.n?(h.ga/h.n)*.28:1));lh=clamp(lh,.35,3.8);la=clamp(la,.3,3.2);let sum=0,ph=0,pd=0,pa=0,c=[];for(let i=0;i<=7;i++)for(let j=0;j<=7;j++){const p=poisson(i,lh)*poisson(j,la);sum+=p;c.push([i,j,p]);if(i>j)ph+=p;else if(i===j)pd+=p;else pa+=p;}ph/=sum;pd/=sum;pa/=sum;const total=lh+la;return{home:lh,away:la,total,result:{home:ph,draw:pd,away:pa},correctScores:c.sort((x,y)=>y[2]-x[2]).slice(0,5).map(x=>({score:`${x[0]}-${x[1]}`,probability:x[2]/sum}))};}

function statKey(v){const t=String(v||'').toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim();const c=t.replace(/[^a-z0-9]/g,'');if(/shots? on target|shots? on goal|on target|tiri in porta/.test(t)||/shots?ontarget|shots?ongoal|ontarget/.test(c))return'shotsOnTarget';if(/total shots|shots total|shot attempts|tiri totali|tiri$/.test(t)||['shots','totalshots','shotattempts'].includes(c))return'shots';if(/corners?|corner kicks|calci d'angolo/.test(t)||['corners','cornerkicks'].includes(c))return'corners';if(/fouls?|falli/.test(t)||['fouls','totalfouls'].includes(c))return'fouls';if(/yellow cards?|yellow|ammonizioni|cartellini gialli/.test(t)||['yellowcards','yellowcard'].includes(c))return'yellow';if(/offsides?|fuorigioco/.test(t)||['offsides','offside'].includes(c))return'offsides';if(/big chances?/.test(t)||['bigchances','bigchance'].includes(c))return'bigChances';if(/expected goals?|xg/.test(t)||['expectedgoals','expectedgoal'].includes(c))return'xg';return null;}
function aggregate(items){const out={};for(const key of ['shots','shotsOnTarget','corners','fouls','yellow','offsides','bigChances','xg']){const vals=items.map(x=>num(x?.[key])).filter(x=>x!==null);if(!vals.length)continue;const mean=vals.reduce((a,b)=>a+b,0)/vals.length;const sd=Math.sqrt(vals.reduce((a,b)=>a+(b-mean)**2,0)/vals.length);out[key]={n:vals.length,mean,sd};}return out;}
function range(h,a,k){const x=h?.statSummary?.[k],y=a?.statSummary?.[k];if(!x&&!y)return null;const mean=(x?.mean||0)+(y?.mean||0),sd=Math.sqrt((x?.sd||0)**2+(y?.sd||0)**2),w=Math.max(1.5,sd*.75,mean*.10);return{min:Math.max(0,Math.round(mean-w)),max:Math.max(0,Math.round(mean+w))};}
const rangeText=r=>r?`${r.min}-${r.max}`:'N/D';

function walk(obj,out=[]){if(!obj||typeof obj!=='object')return out;if(Array.isArray(obj)){obj.forEach(x=>walk(x,out));return out;}if(obj.home?.name&&obj.away?.name&&(obj.id||obj.matchId))out.push(obj);for(const [k,v] of Object.entries(obj))if(!['squad','players','transfers'].includes(k))walk(v,out);return out;}
function extractFixtures(p){const out=[];for(const lg of p?.leagues||[])for(const m of lg.matches||[])out.push({id:m.id,league:lg.name||m.leagueName||'Calcio',time:m.time,status:m.status,home:{id:m.home?.id,name:m.home?.name},away:{id:m.away?.id,name:m.away?.name}});return out;}
async function fotmobToday(){return extractFixtures(await get(`${FOT}/api/matches?date=${today()}`));}

function fotRows(p){const groups=p?.content?.stats?.Periods?.All?.stats;if(!Array.isArray(groups))return[];return groups.flatMap(g=>Array.isArray(g?.stats)?g.stats:(g&&(g.title||g.key||g.name)?[g]:[]));}
function parseFot(p,team){const out={},home=p?.general?.homeTeam?.name||p?.header?.teams?.[0]?.name||'',away=p?.general?.awayTeam?.name||p?.header?.teams?.[1]?.name||'',ih=same(home,team),ia=same(away,team);if(!ih&&!ia)return out;for(const r of fotRows(p)){const k=statKey(r?.title||r?.key||r?.name),v=r?.stats;if(!k||!Array.isArray(v)||v.length<2)continue;const h=num(v[0]),a=num(v[1]);if(h!==null&&a!==null)out[k]=ih?h:a;}return out;}
const fotCache=new Map();
async function fotStats(id,team){const key=`${id}:${norm(team)}`;if(fotCache.has(key))return fotCache.get(key);let z=null;try{const p=await get(`${FOT}/api/data/matchDetails?matchId=${encodeURIComponent(id)}`);const s=parseFot(p,team);if(Object.keys(s).length)z=s;}catch{}fotCache.set(key,z);return z;}

function sofaRows(p){const a=(p?.statistics||[]).find(x=>String(x?.period||'').toUpperCase()==='ALL')||p?.statistics?.[0];return Array.isArray(a?.groups)?a.groups.flatMap(g=>Array.isArray(g?.statisticsItems)?g.statisticsItems:[]):[];}
function parseSofa(p,team){const e=p?.event||p,home=e?.homeTeam?.name||'',away=e?.awayTeam?.name||'',ih=same(home,team),ia=same(away,team);if(!ih&&!ia)return{};const out={};for(const r of sofaRows(p)){const k=statKey(r?.key||r?.name||r?.title);if(!k)continue;const h=num(r?.homeValue??r?.home),a=num(r?.awayValue??r?.away);if(h!==null&&a!==null)out[k]=ih?h:a;}return out;}
const sofaCache=new Map();
async function sofaStats(id,team,meta){const key=`${id}:${norm(team)}`;if(sofaCache.has(key))return sofaCache.get(key);let z=null;try{const p=await get(`${SOFA}/event/${id}/statistics`);const e={homeTeam:{name:meta?.home?team:(meta?.opponent||'')},awayTeam:{name:meta?.home?(meta?.opponent||''):team}};const s=parseSofa({...p,event:e},team);if(Object.keys(s).length)z=s;}catch{}sofaCache.set(key,z);return z;}
async function sofaSearch(name){try{const p=await get(`${SOFA}/search/all?q=${encodeURIComponent(name)}`);const a=(p?.results||[]).filter(x=>x?.entity?.id);return(a.find(x=>same(x.entity?.name,name))||a[0])?.entity?.id||null;}catch{return null;}}
async function sofaEvents(id,name){const out=[],seen=new Set();for(let page=0;page<4&&out.length<15;page++){let p;try{p=await get(`${SOFA}/team/${id}/events/last/${page}`)}catch{break;}for(const m of p?.events||[]){if(m.status?.type!=='finished')continue;const mid=String(m.id);if(seen.has(mid))continue;seen.add(mid);const hn=m.homeTeam?.name||'',an=m.awayTeam?.name||'',t=m.startTimestamp?new Date(m.startTimestamp*1000).toISOString():null;if(same(hn,name))out.push({matchId:mid,home:true,opponent:an,utcTime:t});else if(same(an,name))out.push({matchId:mid,home:false,opponent:hn,utcTime:t});if(out.length>=15)break;}}return out;}

async function espnScoreboard(day){try{return await get(`${ESPN}/scoreboard?dates=${day.replace(/-/g,'')}`)}catch{return null;}}
function espnEvents(p){return Array.isArray(p?.events)?p.events:[];}
function espnTeams(e){const c=e?.competitions?.[0]?.competitors||[];return{home:c.find(x=>x.homeAway==='home')||c[0],away:c.find(x=>x.homeAway==='away')||c[1]};}
function findEspnEvent(p,home,away){let best=null,score=0;for(const e of espnEvents(p)){const {home:h,away:a}=espnTeams(e),hn=h?.team?.displayName||h?.team?.name||'',an=a?.team?.displayName||a?.team?.name||'';let s=0;if(same(hn,home))s+=2;if(same(an,away))s+=2;if(same(hn,away))s+=.5;if(same(an,home))s+=.5;if(s>score){score=s;best=e;}}return score>=4?best:null;}
function parseEspnSummary(p,team){const out={},teams=p?.boxscore?.teams||[];const t=teams.find(x=>same(x?.team?.displayName||x?.team?.name,team));if(!t)return out;for(const r of t.statistics||[]){const k=statKey(r?.name||r?.label||r?.displayName||r?.shortDisplayName);const v=num(r?.displayValue??r?.value);if(k&&v!==null)out[k]=v;}return out;}
const espnCache=new Map();
async function espnStats(r,team){const key=`${r.matchId}:${norm(team)}`;if(espnCache.has(key))return espnCache.get(key);let z=null;const day=isoDay(r.utcTime);if(day){for(let delta=-1;delta<=1&&!z;delta++){const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+delta);const p=await espnScoreboard(d.toISOString().slice(0,10));const {home,away}=r.home?{home:team,away:r.opponent}:{home:r.opponent,away:team};const e=findEspnEvent(p,home,away);if(e){try{const league=e?.competitions?.[0]?.league?.slug||e?.league?.slug||'all';const sum=await get(`${ESPN}/${encodeURIComponent(league)}/summary?event=${encodeURIComponent(e.id)}`);const s=parseEspnSummary(sum,team);if(Object.keys(s).length)z=s;}catch{}}}}espnCache.set(key,z);return z;}

async function tsdbHistory(name){try{const p=await get(`${TSDB}/searchevents.php?e=${encodeURIComponent(name)}`);return p?.event||[];}catch{return[];}}
async function openHistory(name){return[];}

async function enrich(form,name){const recent=form.results.slice(-5).reverse();const combined=[];const source=[];for(const r of recent){let s=await fotStats(r.matchId,name);if(s){combined.push(s);source.push('FotMob');continue;}const sid=await sofaSearch(name);if(sid){const ev=await sofaEvents(sid,name);const rt=r.utcTime?new Date(r.utcTime).getTime():0;const target=ev.filter(x=>x.home===r.home&&(!rt||!x.utcTime||Math.abs(new Date(x.utcTime).getTime()-rt)<=3*86400000)).sort((a,b)=>Math.abs(new Date(a.utcTime)-new Date(r.utcTime))-Math.abs(new Date(b.utcTime)-new Date(r.utcTime)))[0]||ev.find(x=>same(x.opponent,r.opponent));if(target){s=await sofaStats(target.matchId,name,target);if(s){combined.push(s);source.push('SofaScore');continue;}}}s=await espnStats(r,name);if(s){combined.push(s);source.push('ESPN');continue;}}
form.stats=combined;form.statSummary=aggregate(combined);form.statSource=[...new Set(source)].join('+')||'N/D';return form;}

async function fotmobTeam(id,name){try{const p=await get(`${FOT}/api/data/teams?id=${encodeURIComponent(id)}`);const ms=walk(p).filter(m=>m.status?.finished===true||m.status?.type==='finished'||m.finished===true);const form=empty(),seen=new Set();ms.sort((a,b)=>new Date(b.status?.utcTime||b.utcTime||0)-new Date(a.status?.utcTime||a.utcTime||0));for(const m of ms){const mid=String(m.id||m.matchId);if(seen.has(mid))continue;seen.add(mid);const hn=m.home?.name||'',an=m.away?.name||'',hs=num(m.home?.score??m.homeScore),as=num(m.away?.score??m.awayScore);if(same(hn,name))add(form,hs,as,true,mid,m.status?.utcTime||m.utcTime,an);else if(same(an,name))add(form,as,hs,false,mid,m.status?.utcTime||m.utcTime,hn);if(form.n>=10)break;}if(form.n>=2){await enrich(form,name);return{form,source:'FotMob',teamId:id};}}catch{}return null;}
async function sofaTeam(name){const id=await sofaSearch(name);if(!id)return null;const ev=await sofaEvents(id,name),form=empty();for(const e of ev){try{const p=await get(`${SOFA}/event/${e.matchId}`),m=p?.event,hs=num(m?.homeScore?.current??m?.homeScore?.display),as=num(m?.awayScore?.current??m?.awayScore?.display);if(e.home)add(form,hs,as,true,e.matchId,e.utcTime,e.opponent);else add(form,as,hs,false,e.matchId,e.utcTime,e.opponent);if(form.n>=10)break;}catch{}}if(form.n>=2){await enrich(form,name);return{form,source:'SofaScore',teamId:id};}return null;}
async function history(team){if(team.id){const f=await fotmobTeam(team.id,team.name);if(f)return f;}const s=await sofaTeam(team.name);if(s)return s;const ts=await tsdbHistory(team.name);if(ts.length>=2){const form=empty();for(const m of ts.slice(-10)){const h=num(m.intHomeScore),a=num(m.intAwayScore);if(h===null||a===null)continue;const hn=m.strHomeTeam||'',an=m.strAwayTeam||'';if(same(hn,team.name))add(form,h,a,true,m.idEvent,m.strTimestamp,an);else if(same(an,team.name))add(form,a,h,false,m.idEvent,m.strTimestamp,hn);}if(form.n>=2)return{form,source:'TheSportsDB',teamId:null};}await openHistory(team.name);return{form:empty(),source:'N/D',teamId:team.id||null};}

async function build(){state.loading=true;state.error=null;render();try{const all=await fotmobToday();const fixtures=all.filter(x=>/champions league/i.test(x.league||''));const unique=fixtures.filter((x,i,a)=>a.findIndex(y=>String(y.id)===String(x.id))===i);state.fixtures=await Promise.all(unique.slice(0,12).map(async f=>{const[h,a]=await Promise.all([history(f.home),history(f.away)]);return{...f,history:{home:h,away:a},prediction:prediction(h.form,a.form),reliability:clamp((Math.min(h.form.n,10)+Math.min(a.form.n,10))/20,0,1)}}));state.source='FotMob + SofaScore + ESPN + TheSportsDB/OpenLigaDB fallback';}catch(e){state.error=e;state.fixtures=[];state.source='';}state.loading=false;render();}
function time(v){try{return new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return'--:--'}}
function card(f){const p=f.prediction,q=f.history,r=p.result,st={shots:range(q.home.form,q.away.form,'shots'),shotsOnTarget:range(q.home.form,q.away.form,'shotsOnTarget'),corners:range(q.home.form,q.away.form,'corners'),fouls:range(q.home.form,q.away.form,'fouls'),yellow:range(q.home.form,q.away.form,'yellow'),offsides:range(q.home.form,q.away.form,'offsides')},hc=Math.min(q.home.form.n,10)+Math.min(q.away.form.n,10),sc=(q.home.form.stats?.length||0)+(q.away.form.stats?.length||0),sources=[q.home.form.statSource,q.away.form.statSource].filter(x=>x&&x!=='N/D');return`<article class="match-card"><div class="match-meta">${esc(f.league)} · ${time(f.status?.utcTime||f.time)} · TEST APK MULTI-SOURCE</div><div class="teams-line"><strong>${esc(f.home.name)}</strong><span>VS</span><strong>${esc(f.away.name)}</strong></div><div class="today-prob"><span>1 <b>${pct(r.home)}</b></span><span>X <b>${pct(r.draw)}</b></span><span>2 <b>${pct(r.away)}</b></span></div><div class="pick">Gol attesi <b>${p.home.toFixed(2)}-${p.away.toFixed(2)}</b> · Gol totali <b>${Math.max(0,Math.round(p.total-.7))}-${Math.round(p.total+1)}</b></div><div class="quality">Casa: <b>${q.home.form.n}</b> gare (${esc(q.home.source)}) · Trasferta: <b>${q.away.form.n}</b> gare (${esc(q.away.source)})</div><h4>Range statistiche previste</h4><div class="stat-grid compact"><div><span>Tiri totali</span><b>${rangeText(st.shots)}</b></div><div><span>Tiri in porta</span><b>${rangeText(st.shotsOnTarget)}</b></div><div><span>Corner</span><b>${rangeText(st.corners)}</b></div><div><span>Falli</span><b>${rangeText(st.fouls)}</b></div><div><span>Cartellini</span><b>${rangeText(st.yellow)}</b></div><div><span>Fuorigioco</span><b>${rangeText(st.offsides)}</b></div></div><h4>Top risultati</h4><div class="score-list">${p.correctScores.map(x=>`<div><span>${x.score}</span><b>${pct(x.probability)}</b></div>`).join('')}</div><div class="quality">Cronologia: <b>${hc}/20 gare</b> · Statistiche dettagliate: <b>${sc}/10 partite</b> · Fonte stats: <b>${esc([...new Set(sources)].join('+')||'N/D')}</b></div></article>`;}
function render(){app.innerHTML=`<main class="shell"><header><div class="brand"><span class="ball">⚽</span><div><h1>Match Probability AI</h1><small>APK · motore dati multi-source</small></div></div><button id="refresh" class="icon">↻</button></header><section class="hero"><span class="eyebrow">TEST APK · NO VERCEL</span><h2>Partite di oggi</h2><p>FotMob come base, con fallback automatici SofaScore, ESPN, TheSportsDB e OpenLigaDB. Le statistiche vengono cercate fonte per fonte senza chiamare <code>/api/today</code>.</p></section><div id="result">${state.loading?'<section class="card result"><h3>Recupero dati multi-source...</h3><p>Calendario → cronologia → statistiche FotMob → SofaScore → ESPN → fallback.</p></section>':state.error?`<section class="card result"><div class="error">${esc(state.error.message||state.error)}</div><p>Errore nel recupero diretto dei provider.</p></section>`:`<section class="card result"><span class="eyebrow">${esc(todayIso())}</span><h3>${state.fixtures.length} partite Champions League</h3><p>${esc(state.source)}</p><div class="today-list">${state.fixtures.map(card).join('')}</div></section>`}</div><nav><button class="active">●<small>Oggi</small></button><button>⌂<small>Analisi</small></button><button>◈<small>Modello AI</small></button><button>◉<small>Dati</small></button></nav></main>`;const b=document.querySelector('#refresh');if(b)b.onclick=build;}
build();
