const API='https://match-probability-ai.forzajuve9314.workers.dev';
import './style.css';

const state={league:'Serie A',teams:[],home:null,away:null,tab:'analysis'};
const app=document.querySelector('#app');
const leagues=['Serie A','Premier League','La Liga','Bundesliga','Ligue 1','Champions League'];
const pct=x=>`${(Number(x||0)*100).toFixed(1)}%`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const apiGet=async path=>{const r=await fetch(`${API}${path}`,{headers:{Accept:'application/json'}});const text=await r.text();let d;try{d=JSON.parse(text)}catch{throw new Error(`Risposta API non valida (${r.status})`)}if(!r.ok)throw new Error(d.error||`Errore API ${r.status}`);return d};

function render(){
 app.innerHTML=`<main class="shell">
 <header><div class="brand"><span class="ball">⚽</span><div><h1>Match Probability AI</h1><small>Motore predittivo calcistico</small></div></div><button id="refresh" class="icon">↻</button></header>
 <section class="hero"><span class="eyebrow">AI PREDICTION ENGINE</span><h2>Analizza una partita<br>con i dati storici</h2><p>Poisson + forma storica + fattore casa + simulazione Monte Carlo.</p></section>
 <section class="card controls"><label>Campionato<select id="league">${leagues.map(x=>`<option>${x}</option>`).join('')}</select></label><div class="teams"><label>Casa<select id="home"><option>Caricamento…</option></select></label><label>Trasferta<select id="away"><option>Caricamento…</option></select></label></div><button id="predict" class="primary">ANALIZZA PARTITA <span>→</span></button><div id="error" class="error"></div></section>
 <div id="result"></div>
 <nav><button data-tab="analysis" class="${state.tab==='analysis'?'active':''}">⌂<small>Analisi</small></button><button data-tab="model" class="${state.tab==='model'?'active':''}">◈<small>Modello AI</small></button><button data-tab="data" class="${state.tab==='data'?'active':''}">◉<small>Dati</small></button></nav>
 </main>`;
 document.querySelector('#league').value=state.league;
 document.querySelector('#league').onchange=e=>{state.league=e.target.value;state.home=state.away=null;loadTeams()};
 document.querySelector('#refresh').onclick=loadTeams;
 document.querySelector('#predict').onclick=predict;
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();if(state.tab==='model')backtest();else if(state.tab==='data')status();else loadTeams()});
 fillTeams();
}
function fillTeams(){for(const id of ['home','away']){const s=document.querySelector('#'+id);if(!s)continue;const old=state[id];s.innerHTML=state.teams.length?state.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join(''):'<option value="">Nessuna squadra disponibile</option>';if(old&&state.teams.some(t=>String(t.id)===String(old)))s.value=old}}
async function loadTeams(){const err=document.querySelector('#error');if(err)err.textContent='';state.teams=[];fillTeams();try{const d=await apiGet(`/api/teams?league=${encodeURIComponent(state.league)}`);state.teams=Array.isArray(d)?d:(d.teams||d.results||[]);if(!state.teams.length)throw new Error(`Nessuna squadra trovata per ${state.league}`);state.home=String(state.teams[0].id);state.away=String(state.teams[Math.min(1,state.teams.length-1)].id);fillTeams()}catch(e){if(err)err.textContent=e.message}}
async function predict(){const h=document.querySelector('#home')?.value,a=document.querySelector('#away')?.value;if(!h||!a||h===a){document.querySelector('#error').textContent='Scegli due squadre diverse.';return}state.home=h;state.away=a;const btn=document.querySelector('#predict');btn.disabled=true;btn.innerHTML='CALCOLO AI…';document.querySelector('#error').textContent='';try{const d=await apiGet(`/api/predict?home=${encodeURIComponent(h)}&away=${encodeURIComponent(a)}`);showPrediction(d)}catch(e){document.querySelector('#error').textContent=e.message}finally{btn.disabled=false;btn.innerHTML='ANALIZZA PARTITA <span>→</span>'}}
async function simulate(){try{return await apiPost('/api/simulate',{homeTeamId:Number(state.home),awayTeamId:Number(state.away),runs:10000})}catch(e){return null}}
async function apiPost(path,body){const r=await fetch(`${API}${path}`,{method:'POST',headers:{'content-type':'application/json',Accept:'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||`Errore API ${r.status}`);return d}
function showPrediction(d){const h=d.homeTeam||state.teams.find(x=>String(x.id)===String(state.home))?.name||'Casa',a=d.awayTeam||state.teams.find(x=>String(x.id)===String(state.away))?.name||'Trasferta',p=d.result||{},m=d.markets||{};document.querySelector('#result').innerHTML=`<section class="card result"><div class="match"><strong>${esc(h)}</strong><span>VS</span><strong>${esc(a)}</strong></div><div class="prob"><div><b>${pct(p.home)}</b><span>1 · Casa</span></div><div><b>${pct(p.draw)}</b><span>X · Pareggio</span></div><div><b>${pct(p.away)}</b><span>2 · Ospite</span></div></div><div class="bar"><i style="width:${Math.max(3,p.home*100)}%"></i><i style="width:${Math.max(3,p.draw*100)}%"></i><i style="width:${Math.max(3,p.away*100)}%"></i></div><div class="grid"><article><span>⚽ Gol attesi</span><b>${Number(d.expectedGoals?.home||0).toFixed(2)} - ${Number(d.expectedGoals?.away||0).toFixed(2)}</b></article><article><span>🔥 Over 2.5</span><b>${pct(m.over25)}</b></article><article><span>🎯 Gol/Gol</span><b>${pct(m.bttsYes)}</b></article><article><span>📊 Affidabilità</span><b>${pct(d.dataQuality?.reliability)}</b></article></div><button id="simulate" class="secondary">🎲 SIMULA 10.000 PARTITE</button><div id="simResult"></div><div class="quality">${esc(d.model||'Modello predittivo')} · Qualità dati: <b>${esc(d.dataQuality?.level||'n/d')}</b></div></section>`;document.querySelector('#simulate').onclick=async()=>{const b=document.querySelector('#simulate');b.disabled=true;b.textContent='SIMULAZIONE…';const s=await simulate();document.querySelector('#simResult').innerHTML=s?`<div class="simulation"><b>Monte Carlo</b><span>Casa ${pct(s.homeWin)} · X ${pct(s.draw)} · Ospite ${pct(s.awayWin)} · Over 2.5 ${pct(s.over25)}</span></div>`:'<div class="quality">Simulazione non disponibile.</div>';b.disabled=false;b.textContent='🎲 SIMULA 10.000 PARTITE'}}
async function backtest(){const box=document.querySelector('#result');box.innerHTML='<section class="card result"><span class="eyebrow">MODELLO AI</span><h3>Validazione walk-forward</h3><p>Controllo automatico sulle partite storiche disponibili…</p></section>';try{const d=await apiGet(`/api/backtest?league=${encodeURIComponent(state.league)}&minHistory=3`);box.innerHTML=`<section class="card result"><span class="eyebrow">MODELLO AI</span><h3>Validazione ${esc(state.league)}</h3><div class="big">${pct(d.accuracy)}</div><p>Accuracy su <b>${d.evaluated}</b> partite valutate</p><div class="grid"><article><span>Brier Score</span><b>${Number(d.brier).toFixed(3)}</b></article><article><span>Log Loss</span><b>${Number(d.logLoss).toFixed(3)}</b></article></div><div class="quality">Walk-forward: il modello non usa il futuro per prevedere il passato.</div></section>`}catch(e){box.innerHTML=`<section class="card result"><div class="error">${esc(e.message)}</div></section>`}}
async function status(){const box=document.querySelector('#result');box.innerHTML='<section class="card result"><span class="eyebrow">DATABASE</span><p>Caricamento dati…</p></section>';try{const d=await apiGet('/api/data/status');box.innerHTML=`<section class="card result"><span class="eyebrow">DATABASE</span><h3>Dati disponibili</h3><div class="big">${d.matches}</div><p>partite storiche · <b>${d.teamsWithStats}</b> squadre con statistiche</p><div class="quality">Backend online · D1 · aggiornamento automatico</div></section>`}catch(e){box.innerHTML=`<section class="card result"><div class="error">${esc(e.message)}</div></section>`}}

render();loadTeams();
