import './style.css';
import { todayMatches, findTeamIds, enrichHistory, diagnostics, clearProviderCache } from './provider-engine.js';
const app=document.querySelector('#app');
const BUILD='73';
const STAT=[['shots','Tiri','🎯'],['shotsOnTarget','Tiri in porta','🥅'],['corners','Corner','◈'],['fouls','Falli','⚑'],['yellow','Cartellini','🟨'],['offsides','Fuorigioco','↗'],['throwIns','Rimesse','↔'],['saves','Parate','🧤']];
const state={date:'',matches:[],out:[],tab:'today',market:'all',league:'all',query:'',busy:false,done:0,choice:{},favorites:new Set(JSON.parse(localStorage.getItem('mp_fav')||'[]'))};
const teamCache=new Map();
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const n=x=>{if(x&&typeof x==='object')x=x.value??x.current??x.normaltime??x.score??x.displayValue;if(typeof x==='string'&&x.includes('/'))x=x.split('/')[0];const m=String(x??'').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null};
const get=async u=>{try{const r=await fetch(u,{headers:{Accept:'application/json'}});if(!r.ok)return null;return await r.json()}catch{return null}};
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const quant=(a,p)=>{if(!a.length)return null;const v=[...a].sort((x,y)=>x-y),z=(v.length-1)*p,i=Math.floor(z),j=Math.ceil(z);return i===j?v[i]:v[i]+(v[j]-v[i])*(z-i)};
const venue=(t,s)=>((s==='home'?t.H?.stats:t.A?.stats)||[]).filter(x=>s==='home'?x.home===true:x.home===false);
function range(a){if(!a.length)return null;const e=mean(a),lo=Math.max(0,Math.floor(quant(a,.25))),hi=Math.max(lo,Math.ceil(quant(a,.75))),c=Math.max(30,Math.min(97,Math.round(100-(Math.max(1,hi-lo)/Math.max(1,e))*60)));return{expected:e,lo,hi,sample:a.length,consistency:c}}
function save(t,s){const own=venue(t,s),opp=venue(t,s==='home'?'away':'home'),sot=opp.map(x=>x.data?.shotsOnTarget).filter(Number.isFinite),g=opp.map(x=>x.ga).filter(Number.isFinite);const a=sot.length?sot.map((v,i)=>Math.max(0,v-(g[i]??mean(g)??0))):own.map(x=>x.data?.saves).filter(Number.isFinite);return range(a)}
function forecast(t,k,s){if(k==='saves')return save(t,s);const rows=s==='total'?[...venue(t,'home'),...venue(t,'away')]:venue(t,s);return range(rows.map(x=>x.data?.[k]).filter(Number.isFinite))}
function choice(t){return state.choice[t.id]||{market:'shotsOnTarget',side:'total'}}
function best(t){return STAT.map(x=>{const m=forecast(t,x[0],'total');return m?{...x,m}:null}).filter(Boolean).sort((a,b)=>b.m.consistency-a.m.consistency)[0]}
function logo(id){return id?`<img class="team-logo" src="https://api.sofascore.com/api/v1/team/${encodeURIComponent(id)}/image" alt="" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'/>`:''}
function crest(name,id){const initials=String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();return `<span class="crest-wrap">${logo(id)}<span class="crest-fallback">${esc(initials||'?')}</span></span>`}
function formBadges(rows){return rows.slice(0,5).map(r=>r.gf>r.ga?'W':r.gf===r.ga?'D':'L').map(x=>`<span class="form ${x.toLowerCase()}">${x}</span>`).join('')||'<span class="form empty">—</span>'}
function groups(){const map=new Map();for(const t of state.out){if(state.league!=='all'&&t.league!==state.league)continue;const q=norm(state.query);if(q&&!norm(`${t.home} ${t.away} ${t.league}`).includes(q))continue;if(state.tab==='favorites'&&!state.favorites.has(String(t.id)))continue;const k=t.league||'Calcio';if(!map.has(k))map.set(k,[]);map.get(k).push(t)}return [...map.entries()]}
function probs(t){const h=t.H?.form||[],a=t.A?.form||[];if(h.length<2||a.length<2)return null;const hg=mean(h.map(x=>x.gf).filter(Number.isFinite))??0,ag=mean(a.map(x=>x.gf).filter(Number.isFinite))??0,ha=mean(h.map(x=>x.ga).filter(Number.isFinite))??0,aa=mean(a.map(x=>x.ga).filter(Number.isFinite))??0;const x=Math.max(.15,(hg+aa)/2),y=Math.max(.15,(ag+ha)/2),total=x+y;let p1=Math.round(100*x/(total+0.8)),p2=Math.round(100*y/(total+0.8)),px=100-p1-p2;p1=Math.max(5,p1);p2=Math.max(5,p2);px=Math.max(5,100-p1-p2);const sum=p1+px+p2;return[Math.round(p1*100/sum),Math.round(px*100/sum),Math.round(p2*100/sum)]}
function matchCard(t){const p=probs(t),hp=t.homeData?.sofaId,ap=t.awayData?.sofaId,formH=t.H?.form||[],formA=t.A?.form||[],fav=state.favorites.has(String(t.id));return `<article class="match-card" id="match-${esc(t.id)}"><div class="match-meta"><span>${esc(t.country||'')} ${esc(t.league||'Calcio')}</span><span>◷ ${t.time?new Date(t.time).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}):'—'}</span><button class="fav ${fav?'on':''}" data-fav="${esc(t.id)}">${fav?'★':'☆'}</button></div><div class="match-row"><button class="team-cell" data-side="home" data-id="${esc(t.id)}">${crest(t.home,hp)}<div><b>${esc(t.home)}</b><span>${formBadges(formH)}</span></div></button><div class="vs">VS</div><button class="team-cell away" data-side="away" data-id="${esc(t.id)}"><div><b>${esc(t.away)}</b><span>${formBadges(formA)}</span></div>${crest(t.away,ap)}</button><div class="ai-prob"><small>1X2 AI</small><div><b>${p?p[0]+'%':'—'}</b><b>${p?p[1]+'%':'—'}</b><b>${p?p[2]+'%':'—'}</b></div><div class="prob-label"><span>1</span><span>X</span><span>2</span></div></div><button class="arrow" data-openmatch="${esc(t.id)}">›</button></div><div class="market-line">${[['shots','🎯 Tiri'],['shotsOnTarget','🥅 Tiri in porta'],['corners','◈ Corner'],['fouls','⚑ Falli'],['yellow','🟨 Cartellini'],['offsides','▥ Over/Under']].map(x=>`<button data-market-filter="${x[0]}" class="${state.market===x[0]?'active':''}">${x[1]}</button>`).join('')}</div></article>`}
function hero(){const active=diagnostics().filter(x=>x.ok).length,analyzed=state.out.filter(x=>best(x)).length;return `<section class="hero67"><div class="hero-photo"></div><div class="hero-copy"><div class="eyebrow">AI FOOTBALL INTELLIGENCE · BUILD ${BUILD}</div><h1>ANALISI DI OGGI</h1><h2>${state.date?new Date(`${state.date}T12:00:00`).toLocaleDateString('it-IT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}):''}</h2><p>Statistiche, probabilità e segnali AI<br>per tutte le partite di oggi.</p></div><div class="hero-stats"><div><span>⚽</span><b>${state.matches.length}</b><small>Partite oggi</small></div><div><span>▥</span><b>${STAT.length}</b><small>Mercati</small></div><div><span>🌐</span><b>${active}</b><small>Fonti attive</small></div><div><span>🧠</span><b>${analyzed}</b><small>Analizzate</small></div></div><div class="league-tabs"><button data-league="all" class="${state.league==='all'?'active':''}">🌐 Tutti</button>${[...new Set(state.matches.map(x=>x.league||'Calcio'))].slice(0,5).map((x,i)=>`<button data-league="${esc(x)}" class="${state.league===x?'active':''}">${['🇮🇹','🇬🇧','🇪🇸','🇩🇪','🇫🇷'][i]||'⚽'} ${esc(x)}</button>`).join('')}<button>›</button></div><div class="view-tabs"><button class="active">☷ &nbsp; Partite</button><button data-tab="analysis">🏆 &nbsp; Classifica</button><button data-tab="stats">▥ &nbsp; Statistiche</button></div></section>`}
function today(){const flat=groups().flatMap(x=>x[1]);return `${hero()}<section class="today-head"><div><h2>Partite di oggi (${flat.length})</h2><span>🔴 Live &nbsp; ${flat.filter(x=>x.status==='live').length||0}</span></div><button class="time-sort">Orario⌄</button></section><section class="match-list">${flat.map(matchCard).join('')||'<div class="empty-panel">Nessuna partita trovata.</div>'}</section><div class="load-more">Carica altre partite⌄ <small>${flat.length} di ${state.matches.length}</small></div><section class="markets-footer"><h3>Mercati disponibili</h3><div>${[['all','🎯 Tiri'],['shotsOnTarget','🥅 Tiri in porta'],['corners','◈ Corner'],['fouls','⚑ Falli'],['yellow','🟨 Cartellini'],['offsides','▥ Over/Under']].map(x=>`<button data-market-filter="${x[0]}" class="${state.market===x[0]?'active':''}">${x[1]}</button>`).join('')}</div></section>`}
function analysis(){const gs=groups();return `<section class="page67"><div class="eyebrow">ANALISI · BUILD ${BUILD}</div><h1>Quadro dei campionati</h1><p>Classifica e qualità statistica per ogni campionato.</p>${gs.map(([name,ms])=>`<button class="analysis-league" data-league="${esc(name)}"><span>🏆</span><b>${esc(name)}</b><strong>${ms.length}</strong></button>`).join('')}</section>`}
function stats(){const rows=state.out.map(best).filter(Boolean).sort((a,b)=>b.m.consistency-a.m.consistency);return `<section class="page67"><div class="eyebrow">STATISTICHE · BUILD ${BUILD}</div><h1>Statistiche AI</h1><p>Le migliori metriche disponibili sui dati reali.</p><div class="stats-board">${rows.slice(0,30).map((x,i)=>`<div><span>#${i+1}</span><b>${x[2]} ${x[1]}</b><strong>${x.m.lo}–${x.m.hi}</strong><small>${x.m.sample} campioni · ${x.m.consistency}% coerenza</small></div>`).join('')||'<div class="empty-panel">Dati in raccolta…</div>'}</div></section>`}
function data(){const d=diagnostics(),names=['SofaScore','FotMob','ESPN','TheSportsDB','OpenLigaDB','API-Football'];return `<section class="page67"><div class="eyebrow">DATI REALI · BUILD ${BUILD}</div><h1>Fonti & qualità</h1><p>Solo provider realmente verificati dalla build.</p><div class="source-panel">${names.map(name=>{const x=d.find(y=>y.name===name)||{ok:false};return `<div class="source-row ${x.ok?'ok':'ko'}"><span></span><div><b>${name}</b><small>${x.ok?'Risposta valida':'Non disponibile / non configurato'}</small></div><strong>${x.ok?'ATTIVA':'OFFLINE'}</strong></div>`}).join('')}</div></section>`}
function ai(){const rows=state.out.map((t,i)=>({t,i,b:best(t)})).filter(x=>x.b).sort((a,b)=>b.b.m.consistency-a.b.m.consistency);return `<section class="page67"><div class="eyebrow">MODELLO AI · BUILD ${BUILD}</div><h1>Centro decisionale</h1><p>Partite ordinate per coerenza statistica.</p><div class="ai-board"><div class="ai-board-head"><div class="ai-orb">✦</div><div><b>AI Statistical Engine</b><small>${rows.length}/${state.matches.length} analizzate</small></div></div>${rows.slice(0,30).map((r,i)=>`<button class="ai-rank" data-open="${r.i}"><span>${i+1}</span><b>${esc(r.t.home)} vs ${esc(r.t.away)}</b><strong>${r.b.m.consistency}%</strong></button>`).join('')||'<div class="empty-panel">Dati in raccolta…</div>'}</div></section>`}
function render(){let body=state.tab==='today'?today():state.tab==='analysis'?analysis():state.tab==='stats'?stats():state.tab==='ai'?ai():state.tab==='favorites'?today():data();app.innerHTML=`<div class="app-shell"><header class="app-header"><div class="brand"><div class="brand-mark">⚽</div><div><b>Match Probability</b><small>AI FOOTBALL LAB · BUILD ${BUILD}</small></div></div><div class="header-icons"><button>⌕</button><button>♧</button><button>⚙</button><button id="refresh">↻</button></div></header>${body}<nav>${[['today','⌂','Oggi'],['analysis','▥','Analisi'],['ai','✦','AI Model'],['favorites','☆','Preferiti'],['data','◎','Dati']].map(x=>`<button class="${state.tab===x[0]?'active':''}" data-tab="${x[0]}"><span>${x[1]}</span><small>${x[2]}</small></button>`).join('')}</nav></div>`;bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelectorAll('[data-league]').forEach(b=>b.onclick=()=>{state.league=b.dataset.league;state.tab='today';render()});document.querySelectorAll('[data-market-filter]').forEach(b=>b.onclick=()=>{state.market=b.dataset.marketFilter;render()});document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{const id=b.dataset.id;state.choice[id]={...(state.choice[id]||{}),side:b.dataset.side};render()});document.querySelectorAll('[data-openmatch]').forEach(b=>b.onclick=()=>document.querySelector('#match-'+b.dataset.openmatch)?.scrollIntoView({behavior:'smooth',block:'center'}));document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const id=String(b.dataset.fav);state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('mp_fav',JSON.stringify([...state.favorites]));render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const t=state.out[Number(b.dataset.open)];if(t){state.tab='today';render();setTimeout(()=>document.querySelector('#match-'+t.id)?.scrollIntoView({behavior:'smooth',block:'center'}),80)}});document.querySelectorAll('#refresh').forEach(b=>b.onclick=build);const input=document.querySelector('#match-search');if(input){input.oninput=()=>{state.query=input.value;render();setTimeout(()=>document.querySelector('#match-search')?.focus(),0)}}}
async function analyze(m){const key=m.home+'|'+m.away;if(teamCache.has(key))return teamCache.get(key);const p=(async()=>{const [hi,ai]=await Promise.all([findTeamIds(m.home),findTeamIds(m.away)]);const [hf,af]=await Promise.all([fastHistory(m.home,hi),fastHistory(m.away,ai)]);const [hs,as]=await Promise.all([Promise.all(hf.slice(0,3).map(x=>enrichHistory(x,m.home))),Promise.all(af.slice(0,3).map(x=>enrichHistory(x,m.away)))]);return{...m,homeData:hi,awayData:ai,H:{form:hf,stats:hs},A:{form:af,stats:as},loading:false}})();teamCache.set(key,p);return p}
async function fastHistory(name,ids){const sofa=ids?.sofaId?Promise.all(Array.from({length:2},(_,p)=>get(`https://api.sofascore.com/api/v1/team/${ids.sofaId}/events/last/${p}`))).then(xs=>xs.flatMap(j=>(j?.events||[]).map(m=>{const h=m.homeTeam?.name,a=m.awayTeam?.name,hg=n(m.homeScore),ag=n(m.awayScore),home=norm(h)===norm(name)||norm(h).includes(norm(name));if(!h||!a||hg==null||ag==null||String(m.status?.type).toLowerCase()!=='finished'||(!home&&!norm(a).includes(norm(name))))return null;return{id:'sofa-'+m.id,sofaId:String(m.id),team:name,opp:home?a:h,home,gf:home?hg:ag,ga:home?ag:hg,time:m.startTimestamp?new Date(m.startTimestamp*1000).toISOString():''}}).filter(Boolean))):Promise.resolve([]);const fot=ids?.fotId?get(`https://www.fotmob.com/api/data/teams?id=${ids.fotId}`).then(j=>{const out=[];const walk=o=>{if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(walk);return}if(o.home?.name&&o.away?.name&&o.id){const h=o.home.name,a=o.away.name,hg=n(o.home.score),ag=n(o.away.score),home=norm(h)===norm(name)||norm(h).includes(norm(name));if(hg!=null&&ag!=null&&(home||norm(a).includes(norm(name))))out.push({id:'fot-'+o.id,team:name,opp:home?a:h,home,gf:home?hg:ag,ga:home?ag:hg,time:o.status?.utcTime||o.time||''})}Object.values(o).forEach(walk)};walk(j);return out.slice(0,12)}):Promise.resolve([]);const rows=(await Promise.all([sofa,fot])).flat();const map=new Map();for(const r of rows){const k=norm(r.team)+'|'+norm(r.opp)+'|'+String(r.time).slice(0,10);if(!map.has(k))map.set(k,r)}return[...map.values()].sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,10)}
async function build(){if(state.busy)return;state.busy=true;state.date=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());state.tab='today';state.league='all';state.market='all';state.query='';state.done=0;state.choice={};clearProviderCache();app.innerHTML=`<div class="boot"><div class="boot-orb">⚽</div><div class="eyebrow">AI FOOTBALL INTELLIGENCE · BUILD ${BUILD}</div><h2>Match Probability</h2><p>Carico le partite di giornata e preparo i dati reali in parallelo…</p><div class="loader"></div></div>`;try{state.matches=await todayMatches(state.date);state.out=state.matches.map(m=>({...m,H:{form:[],stats:[]},A:{form:[],stats:[]},homeData:{},awayData:{},loading:true}));render();let next=0;const worker=async()=>{while(true){const i=next++;if(i>=state.matches.length)return;try{state.out[i]=await analyze(state.matches[i])}catch(e){state.out[i]={...state.matches[i],H:{form:[],stats:[]},A:{form:[],stats:[]},homeData:{},awayData:{},loading:false,error:String(e?.message||e)}}state.done++;render()}};await Promise.all(Array.from({length:12},()=>worker()));render()}catch(e){state.matches=[];state.out=[];app.innerHTML=`<div class="boot"><div class="eyebrow">ERRORE DATI</div><h2>Impossibile caricare le partite</h2><p>${esc(e?.message||e)}</p><button id="refresh">Riprova</button>`;document.querySelector('#refresh').onclick=build}finally{state.busy=false}}
build();
