import './style.css';
import { todayMatches, findTeamIds, enrichHistory, diagnostics, clearProviderCache } from './provider-engine.js';

const app=document.querySelector('#app');
const BUILD='68';
const STAT=[['shots','Tiri','🎯'],['shotsOnTarget','Tiri in porta','🥅'],['corners','Corner','◈'],['fouls','Falli','⚑'],['yellow','Cartellini','🟨'],['offsides','Fuorigioco','↗'],['throwIns','Rimesse','↔'],['saves','Parate','🧤']];
const state={date:'',matches:[],out:[],tab:'today',market:'all',league:'all',query:'',busy:false,done:0,choice:{},openLeagues:new Set()};
const teamCache=new Map();
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const n=x=>{if(x&&typeof x==='object')x=x.value??x.current??x.normaltime??x.score??x.displayValue;if(typeof x==='string'&&x.includes('/'))x=x.split('/')[0];const m=String(x??'').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null};
const get=async u=>{try{const r=await fetch(u,{headers:{Accept:'application/json'}});if(!r.ok)return null;return await r.json()}catch{return null}};
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const quant=(a,p)=>{if(!a.length)return null;const v=[...a].sort((x,y)=>x-y),z=(v.length-1)*p,i=Math.floor(z),j=Math.ceil(z);return i===j?v[i]:v[i]+(v[j]-v[i])*(z-i)};
const venue=(t,s)=>((s==='home'?t.H?.stats:t.A?.stats)||[]).filter(x=>s==='home'?x.home===true:x.home===false);
function range(a){if(!a.length)return null;const e=mean(a),lo=Math.max(0,Math.floor(quant(a,.25))),hi=Math.max(lo,Math.ceil(quant(a,.75))),c=Math.max(30,Math.min(97,Math.round(100-(Math.max(1,hi-lo)/Math.max(1,e))*60)));return{expected:e,lo,hi,sample:a.length,consistency:c}}
function save(t,s){const own=venue(t,s),opp=venue(t,s==='home'?'away':'home'),sot=opp.map(x=>x.data?.shotsOnTarget).filter(Number.isFinite),g=opp.map(x=>x.ga).filter(Number.isFinite);const a=sot.length?sot.map((v,i)=>Math.max(0,v-(g[i]??mean(g)??0))):own.map(x=>x.data?.saves).filter(Number.isFinite);return range(a)}
function forecast(t,k,s){if(k==='saves')return save(t,s);const rows=s==='total'?[...venue(t,'home'),...venue(t,'away')]:venue(t,s);return range(rows.map(x=>x.data?.[k]).filter(Number.isFinite))}
function choice(t){return state.choice[t.id]||{market:'shotsOnTarget',side:'total'}}
function best(t){return STAT.map(x=>{const m=forecast(t,x[0],'total');return m?{...x,m}:null}).filter(Boolean).sort((a,b)=>b.m.consistency-a.m.consistency)[0]}
function logo(id,name){return id?`<img class="team-logo" src="https://api.sofascore.com/api/v1/team/${encodeURIComponent(id)}/image" alt="" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid' />`:''}
function crest(name,id){const initials=String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();return `<span class="crest-wrap">${logo(id,name)}<span class="crest-fallback">${esc(initials||'?')}</span></span>`}
function formBadges(rows){return rows.slice(0,5).map(r=>r.gf>r.ga?'W':r.gf===r.ga?'D':'L').map(x=>`<span class="form ${x.toLowerCase()}">${x}</span>`).join('')||'<span class="form empty">—</span>'}
function teamData(t,side){return side==='home'?t.homeData||{}:t.awayData||{}}
function leagueGroups(){const map=new Map();for(const t of state.out){if(state.league!=='all'&&t.league!==state.league)continue;const q=norm(state.query);if(q&&!norm(`${t.home} ${t.away} ${t.league}`).includes(q))continue;const k=t.league||'Calcio';if(!map.has(k))map.set(k,[]);map.get(k).push(t)}return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]))}
function matchCard(t,i){const c=choice(t),h=venue(t,'home'),a=venue(t,'away'),b=best(t),m=forecast(t,c.market,c.side);const hp=t.homeData?.sofaId,ap=t.awayData?.sofaId;const label=c.side==='home'?'Casa':c.side==='away'?'Trasferta':'Totale';const market=STAT.find(x=>x[0]===c.market)||STAT[1];const formH=t.H?.form||[],formA=t.A?.form||[];return `<article class="match-card ${i===0?'featured':''}" id="match-${esc(t.id)}"><div class="match-top"><div><span class="league-name">⚽ ${esc(t.league||'Calcio')}</span><span class="match-time">${t.time?new Date(t.time).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}):'—'}</span></div><span class="signal-pill ${b&&b.m.consistency>=80?'good':b&&b.m.consistency>=65?'mid':'low'}">${b?b.m.consistency+'%':'—'}</span></div><div class="match-main"><button class="team-block" data-side="home" data-id="${esc(t.id)}">${crest(t.home,hp)}<span class="team-info"><b>${esc(t.home)}</b><small>CASA · ${h.length} gare</small><span class="form-row">${formBadges(formH)}</span></span></button><div class="versus"><strong>VS</strong><small>${t.time?new Date(t.time).toLocaleDateString('it-IT',{day:'2-digit',month:'2-digit'}):''}</small></div><button class="team-block away" data-side="away" data-id="${esc(t.id)}"><span class="team-info right"><b>${esc(t.away)}</b><small>TRASFERTA · ${a.length} gare</small><span class="form-row right">${formBadges(formA)}</span></span>${crest(t.away,ap)}</button></div><div class="match-actions"><button data-openmatch="${esc(t.id)}">📊 Statistiche</button><button data-side="total" data-id="${esc(t.id)}" class="${c.side==='total'?'active':''}">Totale</button><button data-side="home" data-id="${esc(t.id)}" class="${c.side==='home'?'active':''}">Casa</button><button data-side="away" data-id="${esc(t.id)}" class="${c.side==='away'?'active':''}">Trasferta</button></div><div class="ai-strip"><div class="ai-badge">✦ AI</div><div class="ai-copy"><b>${market[2]} ${market[1]}</b><span>${label} · ${m?`stima ${m.expected.toFixed(1)}`:'dati in raccolta'}</span></div><strong>${m?m.lo+'–'+m.hi:'N/D'}</strong></div><div class="mini-markets">${STAT.filter(x=>state.market==='all'||state.market===x[0]).slice(0,4).map(x=>{const z=forecast(t,x[0],c.side);return `<button data-market="${x[0]}" data-id="${esc(t.id)}" class="mini-market ${c.market===x[0]?'selected':''}"><span>${x[2]}</span><b>${z?z.lo+'–'+z.hi:'—'}</b><small>${x[1]}</small></button>`}).join('')}</div><details class="match-details"><summary>Apri analisi completa</summary><div class="detail-grid">${STAT.map(x=>{const z=forecast(t,x[0],c.side);return `<button data-market="${x[0]}" data-id="${esc(t.id)}" class="detail-stat"><span>${x[2]} ${x[1]}</span><b>${z?z.lo+'–'+z.hi:'N/D'}</b><small>${z?`stima ${z.expected.toFixed(1)} · ${z.sample} campioni · ${z.consistency}%`: 'dati non disponibili'}</small></button>`}).join('')}</div></details></article>`}
function leagueSection(name,matches,index){const open=state.openLeagues.has(name)||state.openLeagues.size===0;const scores=matches.map(best).filter(Boolean).map(x=>x.m.consistency);const avg=scores.length?Math.round(mean(scores)):0;return `<section class="league-section"><button class="league-header" data-league-toggle="${esc(name)}"><div class="league-title"><span class="league-ball">⚽</span><span><b>${esc(name)}</b><small>${matches.length} ${matches.length===1?'partita':'partite'} · analisi AI</small></span></div><div class="league-score"><span>${avg?avg+'%':'—'}</span><small>coerenza</small><i>${open?'⌃':'⌄'}</i></div></button>${open?`<div class="league-matches">${matches.map((t,j)=>matchCard(t,index+j)).join('')}</div>`:''}</section>`}
function statsHero(active){const done=state.out.filter(x=>!x.loading).length;const groups=leagueGroups();return `<section class="hero hero-sport"><div class="stadium-glow"></div><div class="eyebrow">AI FOOTBALL INTELLIGENCE · BUILD ${BUILD}</div><h1>Analisi di oggi</h1><p>${state.date?new Date(`${state.date}T12:00:00`).toLocaleDateString('it-IT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}):''}</p><div class="hero-cards"><div><span>🏟️</span><b>${state.matches.length}</b><small>Partite</small></div><div><span>🏆</span><b>${groups.length}</b><small>Campionati</small></div><div><span>🧠</span><b>${done}</b><small>Analizzate</small></div><div><span>🌐</span><b>${active}</b><small>Fonti</small></div></div></section>`}
function renderToday(){const active=diagnostics().filter(x=>x.ok).length;const groups=leagueGroups();return `${statsHero(active)}<section class="controls"><div class="search-box">⌕<input id="match-search" value="${esc(state.query)}" placeholder="Cerca squadra o campionato…" /></div><div class="league-chips"><button data-league="all" class="${state.league==='all'?'active':''}">Tutti</button>${[...new Set(state.matches.map(x=>x.league||'Calcio'))].slice(0,10).map(x=>`<button data-league="${esc(x)}" class="${state.league===x?'active':''}">${esc(x)}</button>`).join('')}</div><div class="market-chips">${[['all','Tutti'],...STAT.map(x=>[x[0],x[2]+' '+x[1]])].map(x=>`<button data-market-filter="${x[0]}" class="${state.market===x[0]?'active':''}">${x[1]}</button>`).join('')}</div></section><section class="list-head"><div><span class="eyebrow">PROGRAMMA GIORNALIERO</span><h2>${groups.reduce((n,g)=>n+g[1].length,0)} partite · ${groups.length} campionati</h2></div><button id="refresh" class="refresh">↻</button></section><div class="league-list">${groups.map((g,i)=>leagueSection(g[0],g[1],i*100)).join('')||'<div class="empty-panel">Nessuna partita trovata.</div>'}</div>`}
function renderAnalysis(){const groups=leagueGroups();return `<section class="hero compact"><div class="eyebrow">ANALISI · BUILD ${BUILD}</div><h1>Quadro dei campionati</h1><p>Ogni campionato mostra le proprie partite e la qualità statistica disponibile.</p></section><section class="league-overview">${groups.map(([name,ms])=>{const bs=ms.map(best).filter(Boolean).sort((a,b)=>b.m.consistency-a.m.consistency);return `<button class="overview-card" data-league="${esc(name)}"><div class="overview-top"><span>🏆</span><b>${esc(name)}</b><strong>${ms.length}</strong></div><small>${bs.length?`Top segnale ${bs[0].m.consistency}% · ${bs[0][2]} ${bs[0][1]}`:'Dati in raccolta'}</small><div class="overview-matches">${ms.slice(0,3).map(t=>`<span>${esc(t.home)} <i>vs</i> ${esc(t.away)}</span>`).join('')}</div></button>`}).join('')}</section>`}
function renderAI(){const rows=state.out.map((t,i)=>({t,i,b:best(t)})).filter(x=>x.b).sort((a,b)=>b.b.m.consistency-a.b.m.consistency);return `<section class="hero compact"><div class="eyebrow">MODELLO AI · BUILD ${BUILD}</div><h1>Centro decisionale</h1><p>Le partite sono ordinate per coerenza statistica, senza inventare valori mancanti.</p></section><section class="ai-board"><div class="ai-board-head"><div class="ai-orb">✦</div><div><b>AI Statistical Engine</b><small>${state.out.filter(x=>!x.loading).length}/${state.matches.length} analizzate · ${new Set(state.out.map(x=>x.league)).size} campionati</small></div></div>${rows.slice(0,20).map((r,i)=>`<button class="ai-rank" data-open="${r.i}"><span>${i+1}</span><div>${crest(r.t.home,r.t.homeData?.sofaId)}<section><b>${esc(r.t.home)} <i>vs</i> ${esc(r.t.away)}</b><small>${esc(r.t.league||'Calcio')} · ${r.b[2]} ${r.b[1]} · ${r.b.m.lo}–${r.b.m.hi}</small></section></div><strong>${r.b.m.consistency}%</strong></button>`).join('')||'<div class="empty-panel">Dati in raccolta…</div>'}</section>`}
function renderData(){const d=diagnostics();const names=['SofaScore','FotMob','ESPN','TheSportsDB','OpenLigaDB','API-Football'];return `<section class="hero compact"><div class="eyebrow">DATI REALI · BUILD ${BUILD}</div><h1>Fonti & qualità</h1><p>La schermata mostra solo provider realmente verificati dalla build.</p></section><section class="source-panel">${names.map(name=>{const x=d.find(y=>y.name===name)||{ok:false};return `<div class="source-row ${x.ok?'ok':'ko'}"><span></span><div><b>${name}</b><small>${x.ok?'Risposta valida':'Non disponibile / non configurato'}</small></div><strong>${x.ok?'ATTIVA':'OFFLINE'}</strong></div>`}).join('')}</section>`}
function render(){const active=diagnostics().filter(x=>x.ok).length;let body=state.tab==='today'?renderToday():state.tab==='analysis'?renderAnalysis():state.tab==='ai'?renderAI():renderData();app.innerHTML=`<div class="app-shell"><header class="app-header"><div class="brand"><div class="brand-mark">⚽</div><div><b>Match Probability</b><small>AI FOOTBALL LAB · BUILD ${BUILD}</small></div></div><button class="header-btn" id="refresh">↻</button></header>${body}<nav>${[['today','⌂','Oggi'],['analysis','◈','Campionati'],['ai','✦','AI Model'],['data','◎','Dati']].map(x=>`<button class="${state.tab===x[0]?'active':''}" data-tab="${x[0]}"><span>${x[1]}</span><small>${x[2]}</small></button>`).join('')}</nav></div>`;bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelectorAll('[data-league]').forEach(b=>b.onclick=()=>{state.league=b.dataset.league;state.tab='today';render()});document.querySelectorAll('[data-market-filter]').forEach(b=>b.onclick=()=>{state.market=b.dataset.marketFilter;render()});document.querySelectorAll('[data-league-toggle]').forEach(b=>b.onclick=()=>{const x=b.dataset.leagueToggle;if(state.openLeagues.has(x))state.openLeagues.delete(x);else state.openLeagues.add(x);render()});document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{const id=b.dataset.id;state.choice[id]={...(state.choice[id]||{}),side:b.dataset.side};render()});document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>{const id=b.dataset.id;state.choice[id]={...(state.choice[id]||{}),market:b.dataset.market};render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const t=state.out[Number(b.dataset.open)];if(t){state.tab='today';state.league='all';state.query='';render();setTimeout(()=>document.querySelector('#match-'+t.id)?.scrollIntoView({behavior:'smooth',block:'center'}),80)}});document.querySelectorAll('[data-openmatch]').forEach(b=>b.onclick=()=>{const el=document.querySelector('#match-'+b.dataset.openmatch);el?.querySelector('.match-details')?.setAttribute('open','');el?.scrollIntoView({behavior:'smooth',block:'center'})});document.querySelectorAll('#refresh').forEach(b=>b.onclick=build);const input=document.querySelector('#match-search');if(input){input.oninput=()=>{state.query=input.value;const y=window.scrollY;render();window.scrollTo(0,y);setTimeout(()=>document.querySelector('#match-search')?.focus(),0)}}}
async function analyze(m){const key=m.home+'|'+m.away;if(teamCache.has(key))return teamCache.get(key);const p=(async()=>{const [hi,ai]=await Promise.all([findTeamIds(m.home),findTeamIds(m.away)]);const [hf,af]=await Promise.all([fastHistory(m.home,hi),fastHistory(m.away,ai)]);const [hs,as]=await Promise.all([Promise.all(hf.slice(0,8).map(x=>enrichHistory(x,m.home))),Promise.all(af.slice(0,8).map(x=>enrichHistory(x,m.away)))]);return{...m,homeData:hi,awayData:ai,H:{form:hf,stats:hs},A:{form:af,stats:as},loading:false}})();teamCache.set(key,p);return p}
async function fastHistory(name,ids){const sofa=ids?.sofaId?Promise.all(Array.from({length:6},(_,p)=>get(`https://api.sofascore.com/api/v1/team/${ids.sofaId}/events/last/${p}`))).then(xs=>xs.flatMap(j=>(j?.events||[]).map(m=>{const h=m.homeTeam?.name,a=m.awayTeam?.name,hg=n(m.homeScore),ag=n(m.awayScore);const home=norm(h)===norm(name)||norm(h).includes(norm(name));if(!h||!a||hg==null||ag==null||String(m.status?.type).toLowerCase()!=='finished'||(!home&&!((norm(a)===norm(name))||norm(a).includes(norm(name)))))return null;return{id:'sofa-'+m.id,sofaId:String(m.id),team:name,opp:home?a:h,home,gf:home?hg:ag,ga:home?ag:hg,time:m.startTimestamp?new Date(m.startTimestamp*1000).toISOString():''}}).filter(Boolean))):Promise.resolve([]);const fot=ids?.fotId?get(`https://www.fotmob.com/api/data/teams?id=${ids.fotId}`).then(j=>{const out=[];const walk=o=>{if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(walk);return}if(o.home?.name&&o.away?.name&&o.id){const h=o.home.name,a=o.away.name,hg=n(o.home.score),ag=n(o.away.score),home=norm(h)===norm(name)||norm(h).includes(norm(name));if(hg!=null&&ag!=null&&(home||norm(a).includes(norm(name))))out.push({id:'fot-'+o.id,team:name,opp:home?a:h,home,gf:home?hg:ag,ga:home?ag:hg,time:o.status?.utcTime||o.time||''})}Object.values(o).forEach(walk)};walk(j);return out.slice(0,15)}):Promise.resolve([]);const espn=Promise.resolve([]);const rows=(await Promise.all([sofa,fot,espn])).flat();const m=new Map();for(const r of rows){const k=norm(r.team)+'|'+norm(r.opp)+'|'+String(r.time).slice(0,10);if(!m.has(k))m.set(k,r)}return[...m.values()].sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,12)}
async function build(){if(state.busy)return;state.busy=true;state.date=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());state.tab='today';state.league='all';state.market='all';state.query='';state.done=0;state.choice={};state.openLeagues=new Set();clearProviderCache();app.innerHTML=`<div class="boot"><div class="boot-orb">⚽</div><div class="eyebrow">AI FOOTBALL INTELLIGENCE · BUILD ${BUILD}</div><h2>Match Probability</h2><p>Carico tutte le partite di giornata, raggruppo i campionati e preparo le statistiche squadra per squadra…</p><div class="loader"></div></div>`;try{state.matches=await todayMatches(state.date);state.out=state.matches.map(m=>({...m,H:{form:[],stats:[]},A:{form:[],stats:[]},homeData:{},awayData:{},loading:true}));render();let next=0;const worker=async()=>{while(true){const i=next++;if(i>=state.matches.length)return;try{state.out[i]=await analyze(state.matches[i])}catch(e){state.out[i]={...state.matches[i],H:{form:[],stats:[]},A:{form:[],stats:[]},homeData:{},awayData:{},loading:false,error:String(e?.message||e)}}state.done++;render()}};await Promise.all([worker(),worker(),worker(),worker()]);render()}catch(e){state.matches=[];state.out=[];app.innerHTML=`<div class="boot"><div class="eyebrow">ERRORE DATI</div><h2>Impossibile caricare le partite</h2><p>${esc(e?.message||e)}</p><button class="secondary" id="refresh">Riprova</button>`;document.querySelector('#refresh').onclick=build}finally{state.busy=false}}
build();
