import './style.css';
import { todayMatches, findTeamIds, teamHistory, enrichHistory, diagnostics, clearProviderCache } from './provider-engine.js';

const app=document.querySelector('#app');
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const state={date:'',matches:[],out:[],tab:'today',filter:'all',busy:false,mode:{},choice:{},done:0};
const teamCache=new Map();
const STAT_DEFS=[['shots','Tiri','🎯'],['shotsOnTarget','Tiri in porta','🥅'],['corners','Corner','◈'],['fouls','Falli','⚑'],['yellow','Cartellini','🟨'],['offsides','Fuorigioco','↗'],['throwIns','Rimesse laterali','↔'],['saves','Parate','🧤']];
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const vals=(rows,k)=>rows.map(x=>x.data?.[k]).filter(Number.isFinite);
const q=(a,p)=>{if(!a.length)return null;const v=[...a].sort((x,y)=>x-y),z=(v.length-1)*p,i=Math.floor(z),j=Math.ceil(z);return i===j?v[i]:v[i]+(v[j]-v[i])*(z-i)};
const venue=(t,s)=>((s==='home'?t.H?.stats:t.A?.stats)||[]).filter(x=>s==='home'?x.home===true:x.home===false);
const modeLabel=s=>s==='home'?'Casa':s==='away'?'Trasferta':'Totale gara';
function forecast(t,k,s='total'){
  if(k==='saves'){
    const own=venue(t,s),opp=venue(t,s==='home'?'away':'home'),sot=vals(opp,'shotsOnTarget'),g=vals(opp,'ga');
    if(sot.length){const a=sot.map((x,i)=>Math.max(0,x-(g[i]??mean(g)??0)));return range(a)}
    return range(vals(own,'saves'));
  }
  const a=s==='total'?[...venue(t,'home'),...venue(t,'away')]:venue(t,s);return range(vals(a,k));
}
function range(a){if(!a.length)return null;const e=mean(a),lo=Math.max(0,Math.floor(q(a,.25))),hi=Math.max(lo,Math.ceil(q(a,.75))),spread=Math.max(1,hi-lo),cons=Math.max(30,Math.min(97,Math.round(100-(spread/Math.max(1,e))*60)));return{expected:e,lo,hi,sample:a.length,consistency:cons,values:a.slice(0,8)}}
function sourceList(t,k,s='total'){const rows=s==='total'?[...venue(t,'home'),...venue(t,'away')]:venue(t,s);return[...new Set(rows.flatMap(x=>x.sources||[]))]}
function choice(t){return state.choice[t.id]||{market:'shotsOnTarget',side:state.mode[t.id]||'total'} }
function insight(t){const a=STAT_DEFS.map(([k,l,i])=>({k,l,i,m:forecast(t,k)})).filter(x=>x.m).sort((x,y)=>y.m.consistency-x.m.consistency);return a[0]||null}
function metricTile(t,k,l,i,side){const m=forecast(t,k,side);return `<button class="metric stat-metric ${m?'':'disabled'}" data-market="${k}" data-id="${esc(t.id)}"><div class="metric-top"><span>${i} ${l}</span><em class="signal ${m&&m.consistency>=80?'high':m&&m.consistency>=65?'mid':'low'}">${m?m.consistency+'%':'N/D'}</em></div><b>${m?m.lo+'–'+m.hi:'N/D'}</b><small>${m?'stima '+m.expected.toFixed(1)+' · '+m.sample+' campioni':'dati non disponibili'}</small></button>`}
function card(t,index){
  const c=choice(t),h=venue(t,'home'),a=venue(t,'away'),best=insight(t),src=[...new Set([...sourceList(t,c.market,'home'),...sourceList(t,c.market,'away')])];
  const selected=STAT_DEFS.find(x=>x[0]===c.market)||STAT_DEFS[0];
  const dm=c.side==='home'?forecast(t,c.market,'home'):c.side==='away'?forecast(t,c.market,'away'):forecast(t,c.market,'total');
  return `<article id="match-${index}" class="match-card ${index===0?'featured':''}">
    <div class="match-head"><div><div class="match-meta">${esc(t.league||'Calcio')} · ${t.time?new Date(t.time).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}):'—'}</div><span class="tag">AI STAT ENGINE</span></div><span class="confidence ${best&&best.m.consistency>=80?'high':best?'mid':'low'}">${best?best.m.consistency+'%':'—'} coerenza</span></div>
    <div class="teams"><button class="team-title" data-side="home" data-id="${esc(t.id)}"><b>${esc(t.home)}</b><small>CASA · ${h.length} gare</small></button><span>VS</span><button class="team-title" data-side="away" data-id="${esc(t.id)}"><b>${esc(t.away)}</b><small>TRASFERTA · ${a.length} gare</small></button></div>
    <div class="view-switch">${[['total','◉ Totale gara'],['home','⌂ Casa'],['away','↗ Trasferta']].map(x=>`<button data-side="${x[0]}" data-id="${esc(t.id)}" class="${c.side===x[0]?'active':''}">${x[1]}</button>`).join('')}</div>
    <div class="decision-panel"><div class="decision-head"><div class="ai-icon">✦</div><div><strong>AI Decision Studio</strong><p>Scegli il mercato e il lato. L'AI usa solo statistiche storiche realmente disponibili.</p></div></div>
      <div class="choice-label">Mercato</div><div class="choice-grid">${STAT_DEFS.map(x=>`<button class="choice-chip ${c.market===x[0]?'active':''}" data-market="${x[0]}" data-id="${esc(t.id)}">${x[2]} ${x[1]}</button>`).join('')}</div>
      <div class="choice-label">Lato</div><div class="choice-side-grid">${[['total','Totale gara'],['home','Casa'],['away','Trasferta']].map(x=>`<button class="choice-side ${c.side===x[0]?'active':''}" data-side="${x[0]}" data-id="${esc(t.id)}">${x[1]}</button>`).join('')}</div>
      <div class="ai-answer">${dm?`<div><span>${selected[2]} ${selected[1]}</span><b>${modeLabel(c.side)}</b></div><strong>${dm.lo}–${dm.hi}</strong><small>stima centrale ${dm.expected.toFixed(1)} · ${dm.consistency}% coerenza · ${dm.sample} campioni</small><p>${src.length?'Fonti: '+esc(src.join(' · ')):'Nessuna fonte statistica valida per questo mercato.'}</p>`:'<strong>Dati in raccolta</strong><p>Attendo lo storico reale delle due squadre. Non viene inventato alcun valore.</p>'}</div>
    </div>
    <div class="metrics-title"><b>Mercati · ${modeLabel(c.side)}</b><span>${STAT_DEFS.filter(x=>forecast(t,x[0],c.side)).length}/8 disponibili</span></div>
    <div class="metrics">${STAT_DEFS.filter(x=>state.filter==='all'||state.filter===x[0]).map(x=>metricTile(t,x[0],x[1],x[2],c.side)).join('')}</div>
    <div class="history-line"><span>Casa <b>${h.length}</b> · Trasferta <b>${a.length}</b></span><span>${src.length?esc(src.join(' + ')):'raccolta dati…'}</span></div>
    <details class="details-content"><summary>Confronta Casa ↔ Trasferta</summary>${STAT_DEFS.map(x=>{const hm=forecast(t,x[0],'home'),am=forecast(t,x[0],'away');return hm||am?`<div class="split-row"><span>${x[2]} ${x[1]}</span><b>${hm?hm.expected.toFixed(1):'—'}</b><i>vs</i><b>${am?am.expected.toFixed(1):'—'}</b></div>`:''}).join('')||'<div class="empty-stat">Dati insufficienti</div>'}</details>
  </article>`;
}
function sourceCard(x){const e=String(x.error||''),limited=/429|rate/i.test(e);return `<div class="source-row ${x.ok?'ok':limited?'limited':'ko'}"><span class="source-status ${x.ok?'ok':limited?'limited':'ko'}"></span><div><b>${esc(x.name)}</b><small>${x.ok?'Risposta valida ricevuta':limited?'Limite richieste raggiunto':'Nessuna risposta valida'}</small></div><strong>${x.ok?'ATTIVA':limited?'LIMITATA':'OFFLINE'}</strong></div>`}
function render(){const active=diagnostics().filter(x=>x.ok).length,analyzed=state.out.filter(x=>!x.loading).length;let body='';
 if(state.tab==='data'){const names=['SofaScore','FotMob','ESPN','TheSportsDB','OpenLigaDB'];const d=diagnostics();body=`<section class="hero"><div class="eyebrow">DATI REALI · BUILD 66</div><h2>Fonti & qualità</h2><p>L'app interroga direttamente le fonti disponibili nell'APK. Un provider viene indicato attivo solo dopo una risposta valida.</p><div class="quality-pill">● ${active} fonti hanno risposto</div></section><section class="panel source-panel"><div class="panel-head"><div><span class="eyebrow">LIVE PROVIDERS</span><h3>Connessioni reali</h3></div><button class="refresh" id="refresh">↻</button></div>${names.map(n=>sourceCard(d.find(x=>x.name===n)||{name:n,ok:false,error:''})).join('')}<div class="source-note"><b>Nota</b><p>API a pagamento o con chiave non vengono dichiarate attive senza configurazione reale. I dati mancanti restano N/D.</p></div></section>`}
 else if(state.tab==='ai'){const rows=state.out.map((t,i)=>({t,i,b:insight(t)})).filter(x=>x.b).sort((a,b)=>b.b.m.consistency-a.b.m.consistency);body=`<section class="hero"><div class="eyebrow">MODELLO AI · BUILD 66</div><h2>Centro decisionale</h2><p>Nessun risultato esatto: ranking dei segnali statistici su 8 mercati.</p></section><section class="panel"><div class="ai-summary"><div class="ai-orb">✦</div><div><b>AI Statistical Engine</b><p>${analyzed}/${state.matches.length} analizzate · ${active} fonti attive</p></div></div><div class="ranking">${rows.slice(0,12).map((r,i)=>`<button class="rank-row" data-open="${r.i}"><span class="rank-number">${i+1}</span><div><b>${esc(r.t.home)} <i>vs</i> ${esc(r.t.away)}</b><small>${r.b.i} ${r.b.l}: ${r.b.m.lo}–${r.b.m.hi} · stima ${r.b.m.expected.toFixed(1)}</small></div><strong>${r.b.m.consistency}%</strong></button>`).join('')||'<div class="empty-panel">Dati in raccolta…</div>'}</div></section>`}
 else if(state.tab==='analysis'){body=`<section class="hero"><div class="eyebrow">ANALISI · BUILD 66</div><h2>Quadro statistico</h2><p>Seleziona una gara per vedere il confronto Casa/Trasferta e tutti gli 8 mercati.</p></section><section class="panel"><div class="feature-grid"><span>📊 <b>${state.matches.length}</b><small>partite</small></span><span>🧠 <b>${analyzed}</b><small>analisi completate</small></span><span>🌐 <b>${active}</b><small>fonti attive</small></span><span>⚡ <b>8</b><small>mercati</small></span></div><div class="section-label">Partite analizzate</div><div class="analysis-list">${state.out.filter(x=>!x.loading).slice(0,15).map((t,i)=>`<button class="analysis-row" data-open="${state.out.indexOf(t)}"><div><b>${esc(t.home)} <i>vs</i> ${esc(t.away)}</b><small>${insight(t)?insight(t).i+' '+insight(t).m.lo+'–'+insight(t).m.hi:'Dati in raccolta'}</small></div><strong>${insight(t)?.m.consistency||'—'}${insight(t)?'%':''}</strong></button>`).join('')||'<div class="empty-panel">Analisi in raccolta…</div>'}</div></section>`}
 else {const filters=[['all','Tutti'],...STAT_DEFS.map(x=>[x[0],x[2]+' '+x[1]])];body=`<section class="hero"><div class="eyebrow">AI FOOTBALL INTELLIGENCE · BUILD 66</div><h2>Statistiche di oggi</h2><p>Interfaccia BUILD 60, con motore statistico reale: <b>tiri, porta, corner, falli, cartellini, fuorigioco, rimesse laterali e parate</b>.</p><div class="hero-stats"><div><b>${state.matches.length}</b><span>partite</span></div><div><b>${analyzed}/${state.matches.length}</b><span>analizzate</span></div><div><b>${active}</b><span>fonti attive</span></div></div></section><section class="panel"><div class="filter-bar">${filters.map(x=>`<button class="filter-chip ${state.filter===x[0]?'active':''}" data-filter="${x[0]}">${x[1]}</button>`).join('')}</div><div class="panel-head"><div><span class="eyebrow">${esc(state.date)}</span><h3>Analisi statistiche AI</h3></div><button class="refresh" id="refresh">↻</button></div><div class="today-list">${state.out.map((t,i)=>card(t,i)).join('')||'<div class="empty-panel">Nessuna partita disponibile.</div>'}</div></section>`}
 app.innerHTML=`<div class="app-shell"><header class="app-header"><div class="brand"><div class="brand-mark">⚽</div><div><b>Match Probability</b><small>AI FOOTBALL LAB · BUILD 66</small></div></div><button class="header-btn" id="refresh">↻</button></header>${body}<nav>${[['today','⌂','Oggi'],['analysis','◈','Analisi'],['ai','✦','AI Model'],['data','◎','Dati']].map(x=>`<button class="${state.tab===x[0]?'active':''}" data-tab="${x[0]}"><span>${x[1]}</span><small>${x[2]}</small></button>`).join('')}</nav></div>`;
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});document.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{const id=b.dataset.id;state.choice[id]={...(state.choice[id]||{}),side:b.dataset.side};state.mode[id]=b.dataset.side;render()});document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>{const id=b.dataset.id;state.choice[id]={...(state.choice[id]||{}),market:b.dataset.market};render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{state.tab='today';render();setTimeout(()=>document.querySelector('#match-'+b.dataset.open)?.scrollIntoView({behavior:'smooth',block:'start'}),60)});document.querySelectorAll('#refresh').forEach(b=>b.onclick=build);
}
async function analyzeOne(m){const key=m.home+'|'+m.away;if(teamCache.has(key))return teamCache.get(key);const p=(async()=>{const [hi,ai]=await Promise.all([findTeamIds(m.home),findTeamIds(m.away)]);const [hf,af]=await Promise.all([teamHistory(m.home,hi),teamHistory(m.away,ai)]);const [hs,as]=await Promise.all([Promise.all(hf.slice(0,10).map(x=>enrichHistory(x,m.home))),Promise.all(af.slice(0,10).map(x=>enrichHistory(x,m.away)))]);return{...m,H:{form:hf,stats:hs},A:{form:af,stats:as},loading:false}})();teamCache.set(key,p);return p}
async function build(){if(state.busy)return;state.busy=true;state.date=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());state.tab='today';state.filter='all';state.done=0;state.choice={};state.mode={};clearProviderCache();app.innerHTML='<div class="boot"><div class="boot-orb">✦</div><div class="eyebrow">AI FOOTBALL INTELLIGENCE · BUILD 66</div><h2>Match Probability AI</h2><p>Raccolta partite e statistiche reali da più fonti…</p><div class="loader"></div></div>';try{const matches=await todayMatches(state.date);state.matches=matches;state.out=matches.map(m=>({...m,H:{form:[],stats:[]},A:{form:[],stats:[]},loading:true}));render();let next=0;const worker=async()=>{while(true){const i=next++;if(i>=matches.length)return;try{state.out[i]=await analyzeOne(matches[i])}catch(e){state.out[i]={...matches[i],H:{form:[],stats:[]},A:{form:[],stats:[]},loading:false,error:String(e?.message||e)}}state.done++;render()}};await Promise.all([worker(),worker(),worker(),worker()]);render()}catch(e){state.matches=[];state.out=[];app.innerHTML=`<div class="boot"><div class="eyebrow">ERRORE DATI</div><h2>Impossibile caricare le partite</h2><p>${esc(e?.message||e)}</p><button class="secondary" id="refresh">Riprova</button>`;document.querySelector('#refresh').onclick=build}finally{state.busy=false}}
build();
