import './style-v2.css';
import { todayMatches, diagnostics, clearProviderCache } from './provider-engine-v2.js';
import { analyzeMatch, clearAnalysisCache } from './analysis-engine-v2.js';
import { SOURCE_REGISTRY, sourceModeLabel } from './source-registry.js';
const app=document.querySelector('#app');
const BUILD='82';
const STAT=[['shots','Tiri','🎯'],['shotsOnTarget','Tiri in porta','🥅'],['corners','Corner','◈'],['fouls','Falli','⚑'],['yellow','Cartellini','🟨'],['offsides','Fuorigioco','▥'],['throwIns','Rimesse','↔'],['saves','Parate','🧤']];
const state={date:'',matches:[],out:[],tab:'today',market:'all',league:'all',busy:false,completed:0,errors:0,favorites:new Set(JSON.parse(localStorage.getItem('mp_fav')||'[]'))};
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const quant=(a,p)=>{if(!a.length)return null;const v=[...a].sort((x,y)=>x-y),z=(v.length-1)*p,i=Math.floor(z),j=Math.ceil(z);return i===j?v[i]:v[i]+(v[j]-v[i])*(z-i)};
const rowsFor=(t,side)=>((side==='home'?t.H?.stats:t.A?.stats)||[]);
function range(a){if(!a.length)return null;const e=mean(a),lo=Math.max(0,Math.floor(quant(a,.25))),hi=Math.max(lo,Math.ceil(quant(a,.75)));return{expected:e,lo,hi,sample:a.length,consistency:Math.max(35,Math.min(97,Math.round(100-(Math.max(1,hi-lo)/Math.max(1,e))*50)))}}
function forecast(t,k,side='total'){const r=side==='total'?[...rowsFor(t,'home'),...rowsFor(t,'away')]:rowsFor(t,side);return range(r.map(x=>x.data?.[k]).filter(Number.isFinite))}
function aggregate(k){return range(state.out.flatMap(t=>[...rowsFor(t,'home'),...rowsFor(t,'away')].map(x=>x.data?.[k]).filter(Number.isFinite)))}
function verifiedCount(){return state.out.filter(x=>Number(x?.verifiedStats||0)>0).length}
function progressText(){return `${state.completed}/${state.matches.length} analizzate`+(state.errors?` · ${state.errors} senza dati`:'' )}
function crest(name,id){const initials=String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();return `<span class="crest-wrap">${id?`<img class="team-logo" src="https://api.sofascore.com/api/v1/team/${encodeURIComponent(id)}/image" alt="" loading="lazy" onerror="this.remove();this.nextElementSibling.style.display='grid'">`:''}<span class="crest-fallback">${esc(initials||'?')}</span></span>`}
function form(rows){const r=rows.filter(x=>Number.isFinite(x.gf)&&Number.isFinite(x.ga)).slice(0,5);return r.map(x=>x.gf>x.ga?'W':x.gf===x.ga?'D':'L').map(x=>`<i class="form ${x.toLowerCase()}">${x}</i>`).join('')||'<i class="form empty">—</i>'}
function canonicalLeague(x){const s=String(x||'').trim();if(!s||/^regular season$/i.test(s)||/^altra competizione$/i.test(s))return 'Campionato non identificato';const k=s.toLowerCase().replace(/\s+/g,' ');const m={'2. bundesliga':'2. Bundesliga','german 2 bundesliga':'2. Bundesliga','turkish super lig':'Turkish Super Lig','danish superliga':'Danish Superliga','austrian bundesliga':'Austrian Bundesliga','keuken kampioen divisie':'Eerste Divisie','eerste divisie':'Eerste Divisie','scottish championship':'Scottish Championship','allsvenskan':'Allsvenskan','serie b':'Serie B','serie a':'Serie A','bundesliga':'Bundesliga','ligue 1':'Ligue 1','ligue 2':'Ligue 2','eredivisie':'Eredivisie','laliga':'LaLiga','la liga':'LaLiga','premier league':'Premier League'};return m[k]||s}
function groups(){const m=new Map();for(const t of state.out){if(Number(t?.verifiedStats||0)<=0)continue;if(state.tab==='favorites'&&!state.favorites.has(String(t.id)))continue;if(state.league!=='all'&&canonicalLeague(t.league)!==state.league)continue;const k=canonicalLeague(t.league);if(!m.has(k))m.set(k,[]);m.get(k).push(t)}return[...m.entries()]}
function probs(t){const h=(t.H?.form||[]).filter(x=>Number.isFinite(x.gf)&&Number.isFinite(x.ga)).slice(0,6),a=(t.A?.form||[]).filter(x=>Number.isFinite(x.gf)&&Number.isFinite(x.ga)).slice(0,6);if(h.length<3||a.length<3)return null;const hg=mean(h.map(x=>x.gf)),ag=mean(a.map(x=>x.gf)),ha=mean(h.map(x=>x.ga)),aa=mean(a.map(x=>x.ga));const home=Math.max(.15,(hg+aa)/2),away=Math.max(.15,(ag+ha)/2),draw=Math.max(.18,1-Math.abs(home-away)*.18),raw=[home,draw,away],sum=raw.reduce((s,x)=>s+x,0),scaled=raw.map(x=>x/sum*100),base=scaled.map(Math.floor),rem=100-base.reduce((s,x)=>s+x,0);scaled.map((x,i)=>({i,r:x-base[i]})).sort((x,y)=>y.r-x.r).slice(0,rem).forEach(x=>base[x.i]++);return base}
function decision(t){const p=probs(t);if(!p)return null;const max=Math.max(...p),idx=p.indexOf(max);const quality=Number(t.verifiedStats||0)>=2?'Alta':Number(t.verifiedStats||0)===1?'Media':'Bassa';return{p,max,pick:['1','X','2'][idx],quality}}
function proof(t){if(t.loading)return `<span class="pending">◌ Analisi in corso…</span>`;const bits=[];if(t.h2hCount)bits.push(`✓ ${t.h2hCount} H2H`);if(t.verifiedStats)bits.push(`✓ ${t.verifiedStats} profili statistici`);return bits.join(' · ')||'<span class="muted">Dati statistici non disponibili per questa partita</span>'}
function matchCard(t){if(Number(t?.verifiedStats||0)<=0)return '';const p=probs(t),d=decision(t),fav=state.favorites.has(String(t.id)),league=canonicalLeague(t.league);return `<article class="match-card ${t.loading?'loading':''}" id="match-${esc(t.id)}"><div class="match-meta"><span>${esc(t.country||'')} · ${esc(league)}</span><span>◷ ${t.time?new Date(t.time).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}):'—'}</span><button class="fav ${fav?'on':''}" data-fav="${esc(t.id)}">${fav?'★':'☆'}</button></div><div class="match-main"><div class="team-side home"><div class="team-name"><b>${esc(t.home)}</b><span>${form(t.H?.form||[])}</span></div>${crest(t.home,t.homeData?.sofaId)}</div><div class="center-vs"><span>VS</span><button data-openmatch="${esc(t.id)}">›</button></div><div class="team-side away">${crest(t.away,t.awayData?.sofaId)}<div class="team-name"><b>${esc(t.away)}</b><span>${form(t.A?.form||[])}</span></div></div></div><div class="ai-box"><small>1X2 AI</small><div class="prob-grid">${p?`<b>${p[0]}%</b><b>${p[1]}%</b><b>${p[2]}%</b>`:'<b>—</b><b>—</b><b>—</b>'}</div><div class="prob-label"><span>1</span><span>X</span><span>2</span></div></div>${d?`<div class="ai-decision"><div><small>AI DECISION</small><b>${d.pick} · ${d.max}%</b></div><span>Affidabilità dati: ${d.quality}</span></div>`:''}<div class="market-line">${STAT.slice(0,6).map(x=>{const z=forecast(t,x[0]);return `<button data-market-filter="${x[0]}" class="${state.market===x[0]?'active':''}">${x[2]} ${x[1]}${z?` · ${z.lo}–${z.hi}`:''}</button>`}).join('')}</div><div class="match-proof">${proof(t)}</div></article>`}
function hero(){const active=diagnostics().filter(x=>x.ok).length;return `<section class="hero77"><div class="hero-glow"></div><div class="hero-copy"><div class="eyebrow">AI FOOTBALL INTELLIGENCE · BUILD ${BUILD}</div><h1>ANALISI DI OGGI</h1><h2>${state.date?new Date(`${state.date}T12:00:00`).toLocaleDateString('it-IT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}):''}</h2><p>Statistiche, probabilità e segnali AI<br>solo per le partite con dati verificabili.</p></div><div class="hero-ball">⚽</div><div class="hero-stats"><div><span>⚽</span><b>${state.out.filter(x=>Number(x?.verifiedStats||0)>0).length}</b><small>Partite con dati</small></div><div><span>▥</span><b>${STAT.length}</b><small>Mercati</small></div><div><span>🌐</span><b>${active}</b><small>Fonti attive</small></div><div><span>🧠</span><b>${verifiedCount()}</b><small>Statistiche verificate</small></div></div><div class="progress77"><span>Motore dati</span><b>${progressText()}</b><i><em style="width:${state.matches.length?Math.round(state.completed/state.matches.length*100):0}%"></em></i></div><div class="league-tabs"><button data-league="all" class="${state.league==='all'?'active':''}">🌐 Tutti</button>${[...new Set(state.out.filter(x=>Number(x?.verifiedStats||0)>0).map(x=>canonicalLeague(x.league)))].slice(0,8).map((x,i)=>`<button data-league="${esc(x)}" class="${state.league===x?'active':''}">${['🇮🇹','🇬🇧','🇪🇸','🇩🇪','🇫🇷','🇳🇱','🇵🇹','🇧🇷'][i]||'⚽'} ${esc(x)}</button>`).join('')}</div><div class="view-tabs"><button class="active">☷ &nbsp; Partite</button><button data-tab="analysis">🏆 &nbsp; Classifica</button><button data-tab="stats">▥ &nbsp; Statistiche</button></div></section>`}
function today(){const flat=groups().flatMap(x=>x[1]);return `${hero()}<section class="today-head"><div><h2>${state.tab==='favorites'?'Preferiti':'Partite di oggi'} (${flat.length})</h2><span>🔴 Live &nbsp; ${flat.filter(x=>['inprogress','live'].includes(x.status)).length} · ${progressText()}</span></div><button class="time-sort">Orario⌄</button></section><section class="match-list">${flat.map(matchCard).join('')||'<div class="empty-panel">Nessuna partita con statistiche verificabili.</div>'}</section><div class="load-more">Solo partite con statistiche verificabili <small>${flat.length} disponibili</small></div>`}
function analysis(){const gs=groups();return `<section class="page77"><div class="eyebrow">ANALISI · BUILD ${BUILD}</div><h1>Campionati verificati (${gs.length})</h1><p>Solo competizioni con dati statistici verificabili. I nomi vengono normalizzati quando la competizione è riconoscibile.</p>${gs.map(([name,ms])=>`<button class="analysis-league" data-league="${esc(name)}"><span>🏆</span><b>${esc(name)}</b><strong>${ms.length}</strong></button>`).join('')||'<div class="empty-panel">Nessun campionato con dati verificati.</div>'}</section>`}
function stats(){const agg=STAT.map(x=>({x,m:aggregate(x[0])})).filter(z=>z.m);return `<section class="page77"><div class="eyebrow">STATISTICHE · BUILD ${BUILD}</div><h1>Statistiche AI</h1><p>Valori provenienti da profili statistici reali di squadra; nessun numero inventato per riempire le schede.</p><div class="stats-board">${agg.map(z=>`<div><span>${z.x[2]}</span><b>${z.x[1]}</b><strong>${z.m.lo}–${z.m.hi}</strong><small>${z.m.sample} profili · media ${z.m.expected.toFixed(1)} · ${z.m.consistency}% coerenza</small></div>`).join('')||'<div class="empty-panel">Nessun dato verificato ancora.</div>'}</div></section>`}
function ai(){const rows=state.out.filter(t=>Number(t?.verifiedStats||0)>0).map((t,i)=>({t,i,d:decision(t)})).filter(x=>x.d).sort((a,b)=>b.d.max-a.d.max||b.d.p[0]-a.d.p[0]);return `<section class="page77"><div class="eyebrow">MODELLO AI · BUILD ${BUILD}</div><h1>Centro decisionale</h1><p>Classifica ordinata dalla probabilità 1X2 più alta. L'affidabilità dei dati è mostrata separatamente e non viene confusa con la probabilità.</p><div class="ai-board"><div class="ai-board-head"><div class="ai-orb">✦</div><div><b>AI Decision Engine</b><small>Probabilità 1X2 · affidabilità dati separata · ${verifiedCount()} analizzate</small></div></div>${rows.slice(0,60).map((r,i)=>`<button class="ai-rank" data-open="${r.i}"><span>${i+1}</span><b>${esc(r.t.home)} vs ${esc(r.t.away)}</b><strong>${r.d.pick} · ${r.d.max}%</strong><small>1 ${r.d.p[0]}% · X ${r.d.p[1]}% · 2 ${r.d.p[2]}% · Dati ${r.d.quality}</small></button>`).join('')||'<div class="empty-panel">Nessuna partita con dati verificati.</div>'}</div></section>`}
function data(){const d=diagnostics();return `<section class="page77"><div class="eyebrow">DATI REALI · BUILD ${BUILD}</div><h1>Fonti & qualità</h1><p>Le API automatiche forniscono i numeri. Forum e community vengono usati solo come segnali qualitativi e mai trasformati in statistiche senza verifica.</p><div class="source-panel">${SOURCE_REGISTRY.map(s=>{const x=d.find(y=>y.name===s.name),active=x?.ok===true;return `<div class="source-row ${active?'ok':''}"><span></span><div><b>${esc(s.name)}</b><small>${esc(s.kind)}</small></div><strong>${active?'ATTIVA':sourceModeLabel(s.mode)}</strong></div>`}).join('')}</div></section>`}
function render(){const body=state.tab==='today'||state.tab==='favorites'?today():state.tab==='analysis'?analysis():state.tab==='stats'?stats():state.tab==='ai'?ai():data();app.innerHTML=`<div class="app-shell"><header class="app-header"><div class="brand"><div class="brand-mark">⚽</div><div><b>Match Probability</b><small>AI FOOTBALL LAB · BUILD ${BUILD}</small></div></div><div class="header-icons"><button>⌕</button><button>♧</button><button>⚙</button></div></header>${body}<nav>${[['today','⌂','Oggi'],['analysis','▥','Analisi'],['ai','✦','AI Model'],['favorites','☆','Preferiti'],['data','◎','Dati']].map(x=>`<button class="${state.tab===x[0]?'active':''}" data-tab="${x[0]}"><span>${x[1]}</span><small>${x[2]}</small></button>`).join('')}</nav></div>`;bind()}
let renderTimer=0;function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(render,180)}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelectorAll('[data-league]').forEach(b=>b.onclick=()=>{state.league=b.dataset.league;state.tab='today';render()});document.querySelectorAll('[data-market-filter]').forEach(b=>b.onclick=()=>{state.market=b.dataset.marketFilter;render()});document.querySelectorAll('[data-openmatch]').forEach(b=>b.onclick=()=>document.querySelector('#match-'+b.dataset.openmatch)?.scrollIntoView({behavior:'smooth',block:'center'}));document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const id=String(b.dataset.fav);state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('mp_fav',JSON.stringify([...state.favorites]));render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const t=state.out[Number(b.dataset.open)];if(t){state.tab='today';render();setTimeout(()=>document.querySelector('#match-'+t.id)?.scrollIntoView({behavior:'smooth',block:'center'}),80)}})}
async function build(){if(state.busy)return;state.busy=true;state.completed=0;state.errors=0;state.date=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());state.tab='today';state.league='all';state.market='all';clearProviderCache();clearAnalysisCache();app.innerHTML=`<div class="boot"><div class="boot-orb">⚽</div><div class="eyebrow">AI FOOTBALL INTELLIGENCE · BUILD ${BUILD}</div><h2>Match Probability</h2><p>Raccolgo le partite reali di oggi. Poi analizzo forma, H2H e statistiche; alla fine mostro solo quelle con dati verificabili.</p><div class="loader"></div></div>`;try{state.matches=await todayMatches(state.date);state.out=state.matches.map(m=>({...m,H:{form:[],stats:[]},A:{form:[],stats:[]},homeData:{sofaId:m.sofaIdHome||null},awayData:{sofaId:m.sofaIdAway||null},loading:true}));render();let next=0;const worker=async()=>{while(true){const i=next++;if(i>=state.matches.length)return;try{state.out[i]=await analyzeMatch(state.matches[i])}catch(e){state.errors++;state.out[i]={...state.matches[i],H:{form:[],stats:[]},A:{form:[],stats:[]},homeData:{sofaId:state.matches[i].sofaIdHome||null},awayData:{sofaId:state.matches[i].sofaIdAway||null},loading:false,error:String(e?.message||e)}}state.completed++;scheduleRender()}};await Promise.all(Array.from({length:12},()=>worker()));state.out=state.out.filter(t=>Number(t?.verifiedStats||0)>0);state.matches=[...state.out];state.completed=state.matches.length;render()}catch(e){state.matches=[];state.out=[];app.innerHTML=`<div class="boot"><div class="eyebrow">ERRORE DATI</div><h2>Impossibile caricare le partite</h2><p>${esc(e?.message||e)}</p>`}finally{state.busy=false}}
build();