const F='https://www.fotmob.com';
const S='https://api.sofascore.com/api/v1';
const E='https://site.api.espn.com/apis/site/v2/sports/soccer/all';
const EW='https://site.web.api.espn.com/apis/site/v2/sports/soccer/all';
const T='https://www.thesportsdb.com/api/v1/json/123';
const O='https://api.openligadb.de';

export const PROVIDERS=['SofaScore','FotMob','ESPN','TheSportsDB','OpenLigaDB','API-Football','Sportmonks','Football-Data.org','GoalServe','AllSportsAPI','SportsDataIO','Sportradar','Highlightly','RapidAPI Sports APIs','Flashscore','Livescore','Soccerway','Goal.com','ESPN.com','Eurosport','Tuttosport','Sky Sport','La Gazzetta','OneFootball','FotMob.com','AiScore','365Scores','BeSoccer','Soccer24','Forza Football','LiveScore','ScoreBat','BetExplorer','WhoScored','FlashFootball','Goaloo','SportyTrader','Scores24','LivesoccerTV'];

const cache=new Map();
const status={};
const n=x=>{if(x&&typeof x==='object')x=x.value??x.displayValue??x.current??x.normaltime??x.score??x.homeValue;if(typeof x==='string'&&x.includes('/'))x=x.split('/')[0];const m=String(x??'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null};
const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|afc|sk|club|calcio|rotterdam|cf|fk|sc|ac|as|sv|bk|kv)\b/g,'').replace(/[^a-z0-9]/g,'');
const similar=(a,b)=>{if(!a||!b)return false;const x=a.length<b.length?a:b,y=a.length<b.length?b:a;if(x.length<5)return false;let hits=0;for(let i=0;i<=x.length-4;i++)if(y.includes(x.slice(i,i+4)))hits++;return hits>=Math.max(1,Math.floor(x.length/5))};
const same=(a,b)=>{a=norm(a);b=norm(b);return!!a&&!!b&&(a===b||a.includes(b)||b.includes(a)||similar(a,b))};
const date=x=>{if(!x)return'';const d=new Date(x);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const key=v=>{const t=String(v||'').replace(/([a-z])([A-Z])/g,'$1 $2').toLowerCase().replace(/[_-]/g,' '),c=t.replace(/[^a-z0-9]/g,'');if(c==='totalshots'||c==='totalshotsonGoal'.toLowerCase()||/total shots|shot attempts|^shots$|shots total/.test(t))return'shots';if(c==='shotsongoal'||c==='shotsontarget'||/shots? on target|shots? on goal|on target/.test(t))return'shotsOnTarget';if(c==='cornerkicks'||/corner/.test(t))return'corners';if(c==='fouls'||/foul/.test(t))return'fouls';if(c==='yellowcards'||/yellow|ammon/.test(t))return'yellow';if(c==='offsides'||/offside/.test(t))return'offsides';if(c==='expectedgoals'||/expected goal|^xg/.test(t))return'xg';if(c==='bigchancecreated'||c==='bigchancescreated'||/big chance/.test(t))return'bigChances';return null};

async function get(url,provider){const k=provider+'|'+url;if(cache.has(k))return cache.get(k);const p=(async()=>{try{const r=await fetch(url,{headers:{Accept:'application/json'}});const text=await r.text();let j;try{j=JSON.parse(text)}catch{throw Error('JSON '+r.status)}if(!r.ok)throw Error('HTTP '+r.status);status[provider]={ok:true,error:''};return j}catch(e){status[provider]={ok:false,error:String(e?.message||e)};return null}})();cache.set(k,p);return p}

function fotStats(p,team){const rows=p?.content?.stats?.Periods?.All?.stats||p?.content?.stats?.Periods?.all?.stats||[],h=p?.general?.homeTeam?.name||p?.header?.teams?.[0]?.name||'',a=p?.general?.awayTeam?.name||p?.header?.teams?.[1]?.name||'',o={};for(const g of rows)for(const r of(Array.isArray(g?.stats)?g.stats:[g])){const k=key(r?.key||r?.title||r?.name),v=r?.stats;if(k&&Array.isArray(v)&&v.length>1){const hv=n(v[0]),av=n(v[1]);if(hv!=null&&av!=null)o[k]=same(h,team)?hv:same(a,team)?av:null}}return o}
function sofaStats(p,team,e){const groups=(p?.statistics||[]).find(x=>String(x.period).toUpperCase()==='ALL')?.groups||[],h=e?.homeTeam?.name||e?.homeTeam?.shortName||'',a=e?.awayTeam?.name||e?.awayTeam?.shortName||'',o={};for(const g of groups)for(const r of g.statisticsItems||[]){const k=key(r.key||r.name||r.title),hv=n(r.homeValue??r.home),av=n(r.awayValue??r.away);if(k&&hv!=null&&av!=null)o[k]=same(h,team)?hv:same(a,team)?av:null}return o}
function espnStats(p,team){const t=(p?.boxscore?.teams||[]).find(x=>same(x.team?.displayName||x.team?.name,team)),o={};for(const r of t?.statistics||[]){const k=key(r.name||r.label||r.abbreviation),v=n(r.displayValue??r.value);if(k&&v!=null)o[k]=v}return o}
function tsStats(p,team,e){const rows=(p?.eventstats||[]).flatMap(x=>x.eventstats||x.stats||[]),o={};for(const r of rows){const k=key(r.strStat||r.strName||r.name),a=n(r.intHome??r.home),b=n(r.intAway??r.away);if(k&&a!=null&&b!=null)o[k]=same(e?.strHomeTeam,team)?a:b}return o}

function fromSofaEvents(events,name){const out=[];for(const m of events||[]){const st=String(m.status?.type||'').toLowerCase();if(st!=='finished'&&st!=='ended')continue;const h=m.homeTeam?.name,a=m.awayTeam?.name,hg=n(m.homeScore?.current??m.homeScore?.normaltime),ag=n(m.awayScore?.current??m.awayScore?.normaltime);if(hg==null||ag==null)continue;if(same(h,name))out.push({id:'sofa-'+m.id,sofaId:String(m.id),team:name,opp:a,home:true,gf:hg,ga:ag,time:m.startTimestamp?new Date(m.startTimestamp*1000).toISOString():m.startTime||'',sofaEvent:m});else if(same(a,name))out.push({id:'sofa-'+m.id,sofaId:String(m.id),team:name,opp:h,home:false,gf:ag,ga:hg,time:m.startTimestamp?new Date(m.startTimestamp*1000).toISOString():m.startTime||'',sofaEvent:m})}return out}
async function sofaTeam(name,sofaId){const out=[];if(!sofaId)return out;for(let p=0;p<12&&out.length<15;p++){const j=await get(`${S}/team/${sofaId}/events/last/${p}`,'SofaScore');out.push(...fromSofaEvents(j?.events,name))}return out}
async function sofaDays(name,days=300){const out=[];const base=new Date(`${today()}T12:00:00Z`);const ds=[];for(let i=1;i<=days;i++){const d=new Date(base);d.setUTCDate(d.getUTCDate()-i);ds.push(d.toISOString().slice(0,10))}for(let i=0;i<ds.length;i+=12){const b=ds.slice(i,i+12),vals=await Promise.all(b.map(d=>get(`${S}/sport/football/scheduled-events/${d}`,'SofaScore')));for(const j of vals)out.push(...fromSofaEvents(j?.events,name));if(out.length>=15)break}return out}

function fromFotTeam(p,name){const all=[];const walk=o=>{if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(walk);return}if(o.home?.name&&o.away?.name&&o.id)all.push(o);if(o.homeTeam?.name&&o.awayTeam?.name&&o.id)all.push({id:o.id,home:o.homeTeam,away:o.awayTeam,status:o.status,time:o.time});Object.values(o).forEach(v=>walk(v))};walk(p);const seen=new Set();return all.map(m=>{if(seen.has(String(m.id)))return null;seen.add(String(m.id));const h=m.home?.name,a=m.away?.name,hg=n(m.home?.score),ag=n(m.away?.score),home=same(h,name),away=same(a,name);return(hg!=null&&ag!=null&&(home||away))?{id:'fot-'+m.id,fotId:String(m.id),team:name,opp:home?a:h,home,gf:home?hg:ag,ga:home?ag:hg,time:m.status?.utcTime||m.time||''}:null}).filter(Boolean)}
async function fotTeam(name,fotId){if(!fotId)return[];const j=await get(`${F}/api/data/teams?id=${fotId}`,'FotMob');return fromFotTeam(j,name).sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,15)}

function fromEspnEvents(events,name){const out=[];for(const e of events||[]){const c=e.competitions?.[0]?.competitors||[],h=c.find(x=>x.homeAway==='home')||c[0],a=c.find(x=>x.homeAway==='away')||c[1],hs=n(h?.score),as=n(a?.score),hn=h?.team?.displayName,an=a?.team?.displayName;if(!hn||!an||hs==null||as==null)continue;if(same(hn,name)||same(an,name)){const home=same(hn,name);out.push({id:'espn-'+e.id,espnId:String(e.id),team:name,opp:home?an:hn,home,gf:home?hs:as,ga:home?as:hs,time:e.date||''})}}return out}
async function espnTeam(name){const end=new Date(`${today()}T12:00:00Z`),start=new Date(end);start.setUTCDate(start.getUTCDate()-180);const a=start.toISOString().slice(0,10).replace(/-/g,''),b=end.toISOString().slice(0,10).replace(/-/g,'');for(const base of [E,EW]){const j=await get(`${base}/scoreboard?dates=${a}-${b}`,'ESPN');const r=fromEspnEvents(j?.events,name);if(r.length)return r.sort((x,y)=>new Date(y.time)-new Date(x.time)).slice(0,15)}return[]}

async function tsTeam(name){const q=encodeURIComponent(name);const s=await get(`${T}/searchteams.php?t=${q}`,'TheSportsDB'),teams=s?.teams||[];const team=teams.find(x=>same(x.strTeam,name))||teams[0];if(!team?.idTeam)return[];const j=await get(`${T}/eventslast.php?id=${team.idTeam}`,'TheSportsDB');return(j?.results||j?.events||[]).map(e=>{const h=e.strHomeTeam,a=e.strAwayTeam,hg=n(e.intHomeScore),ag=n(e.intAwayScore),home=same(h,name);return(hg!=null&&ag!=null&&(home||same(a,name)))?{id:'ts-'+e.idEvent,tsId:String(e.idEvent),team:name,opp:home?a:h,home,gf:home?hg:ag,ga:home?ag:hg,time:e.strTimestamp||e.dateEvent||''}:null}).filter(Boolean).slice(0,15)}
async function openLigaTeam(name){const j=await get(`${O}/getmatchesbyteam/${encodeURIComponent(name)}/8/0`,'OpenLigaDB');const a=Array.isArray(j)?j:[];return a.map(m=>{const h=m.team1?.teamName,a=m.team2?.teamName,home=same(h,name),res=m.matchResults?.find?.(x=>Number(x.resultTypeID)===2)||m.matchResults?.[0],hg=n(res?.pointsTeam1),ag=n(res?.pointsTeam2);return hg!=null&&ag!=null&&(home||same(a,name))?{id:'old-'+(m.matchID||m.matchId),team:name,opp:home?a:h,home,gf:home?hg:ag,ga:home?ag:hg,time:m.matchDateTime}:null}).filter(Boolean).slice(0,15)}

export async function findTeamIds(name){const [s,f]=await Promise.all([get(`${S}/search/all?q=${encodeURIComponent(name)}`,'SofaScore'),get(`${F}/api/data/search/suggest?term=${encodeURIComponent(name)}&hits=20&lang=en`,'FotMob')]);const sr=(s?.results||[]).filter(x=>String(x.entity?.type||'').toLowerCase()==='team'),st=sr.find(x=>same(x.entity?.name,name))||sr[0];const fa=f?.results||f?.suggestions||[],ft=fa.find(x=>same(x.title||x.name||x.entity?.name,name))||fa.find(x=>String(x.type||x.entity?.type||'').toLowerCase()==='team')||fa[0];return{sofaId:st?.entity?.id||null,fotId:ft?.id||ft?.entity?.id||ft?.team?.id||null}}

function dedupe(rows){const m=new Map();for(const r of rows){if(!r?.team||!r?.opp||r.gf==null||r.ga==null)continue;const d=date(r.time),k=norm(r.team)+'|'+norm(r.opp)+'|'+(d||String(r.id||''));if(!m.has(k))m.set(k,{...r});else{const e=m.get(k);m.set(k,{...e,...r,sofaId:e.sofaId||r.sofaId,fotId:e.fotId||r.fotId,espnId:e.espnId||r.espnId,tsId:e.tsId||r.tsId,sofaEvent:e.sofaEvent||r.sofaEvent})}}return[...m.values()].sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,10)}

export async function teamHistory(name,ids={}){const [s,f,e,t,o]=await Promise.allSettled([sofaTeam(name,ids.sofaId),fotTeam(name,ids.fotId),espnTeam(name),tsTeam(name),openLigaTeam(name)]);let rows=[s,f,e,t,o].flatMap(x=>x.status==='fulfilled'?x.value:[]),result=dedupe(rows);if(result.length<10){const extra=await sofaDays(name,300);result=dedupe([...result,...extra])}return result.slice(0,10)}

async function matchForProvider(r,provider){const d=date(r.time);if(provider==='SofaScore'&&r.sofaId)return r.sofaEvent||{id:r.sofaId,homeTeam:{name:r.home?r.team:r.opp},awayTeam:{name:r.home?r.opp:r.team}};if(provider==='FotMob'&&r.fotId)return{id:r.fotId};if(provider==='ESPN'&&r.espnId)return{id:r.espnId};if(provider==='TheSportsDB'&&r.tsId)return{idEvent:r.tsId,strHomeTeam:r.home?r.team:r.opp,strAwayTeam:r.home?r.opp:r.team};if(provider==='FotMob'){const j=await get(`${F}/api/data/matches?date=${d.replace(/-/g,'')}&timezone=Europe%2FRome`,'FotMob');return(j?.leagues||[]).flatMap(l=>l.matches||[]).find(m=>same(m.home?.name,r.home?r.team:r.opp)&&same(m.away?.name,r.home?r.opp:r.team))||null}if(provider==='ESPN'){const j=await get(`${E}/scoreboard?dates=${d.replace(/-/g,'')}`,'ESPN');return(j?.events||[]).find(e=>{const c=e.competitions?.[0]?.competitors||[],h=c.find(x=>x.homeAway==='home')||c[0],a=c.find(x=>x.homeAway==='away')||c[1];return same(h?.team?.displayName,r.home?r.team:r.opp)&&same(a?.team?.displayName,r.home?r.opp:r.team)})||null}if(provider==='TheSportsDB'){const j=await get(`${T}/eventsday.php?d=${d}&s=Soccer`,'TheSportsDB');return(j?.events||[]).find(e=>same(e.strHomeTeam,r.home?r.team:r.opp)&&same(e.strAwayTeam,r.home?r.opp:r.team))||null}return null}

async function providerStats(r,team,provider){try{const e=await matchForProvider(r,provider);if(!e)return{};if(provider==='SofaScore')return sofaStats(await get(`${S}/event/${e.id}/statistics`,'SofaScore'),team,e);if(provider==='FotMob')return fotStats(await get(`${F}/api/data/matchDetails?matchId=${e.id}`,'FotMob'),team);if(provider==='ESPN')return espnStats(await get(`${E}/summary?event=${e.id}`,'ESPN'),team);if(provider==='TheSportsDB')return tsStats(await get(`${T}/lookupeventstats.php?id=${e.idEvent}`,'TheSportsDB'),team,e)}catch{}return{}}
function median(a){const x=a.filter(v=>v!=null).sort((a,b)=>a-b);if(!x.length)return null;const i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}
export async function enrichHistory(r,team){const providers=['SofaScore','FotMob','ESPN','TheSportsDB'];const results=await Promise.all(providers.map(p=>providerStats(r,team,p)));const data={},sources=[];for(const k of ['shots','shotsOnTarget','corners','fouls','yellow','offsides','xg','bigChances']){const vals=results.map(x=>x[k]).filter(v=>v!=null);const v=median(vals);if(v!=null)data[k]=v}providers.forEach((p,i)=>{if(Object.keys(results[i]).length)sources.push(p)});return{...r,data,sources,providerValues:results}}

export async function todayMatches(d=today()){const [s,f,e]=await Promise.all([get(`${S}/sport/football/scheduled-events/${d}`,'SofaScore'),get(`${F}/api/data/matches?date=${d.replace(/-/g,'')}&timezone=Europe%2FRome`,'FotMob'),get(`${E}/scoreboard?dates=${d.replace(/-/g,'')}`,'ESPN')]);const out=[];const add=(m,kind)=>{if(!m)return;const h=kind==='f'?m.home?.name:kind==='e'?m.competitions?.[0]?.competitors?.find(x=>x.homeAway==='home')?.team?.displayName:m.homeTeam?.name;const a=kind==='f'?m.away?.name:kind==='e'?m.competitions?.[0]?.competitors?.find(x=>x.homeAway==='away')?.team?.displayName:m.awayTeam?.name;if(!h||!a)return;const ex=out.find(x=>same(x.home,h)&&same(x.away,a));if(ex){ex.sofaId=ex.sofaId|| (kind==='s'?String(m.id):null);ex.fotId=ex.fotId|| (kind==='f'?String(m.id):null);ex.espnId=ex.espnId|| (kind==='e'?String(m.id):null);ex.sofaEvent=ex.sofaEvent||(kind==='s'?m:null)}else out.push({id:String(m.id),home:h,away:a,time:kind==='f'?m.status?.utcTime||m.time:kind==='e'?m.date:m.startTimestamp?new Date(m.startTimestamp*1000).toISOString():'',league:kind==='f'?'Calcio':kind==='e'?m.league?.name||'Calcio':m.tournament?.name||'Calcio',sofaId:kind==='s'?String(m.id):null,fotId:kind==='f'?String(m.id):null,espnId:kind==='e'?String(m.id):null,sofaEvent:kind==='s'?m:null})};(s?.events||[]).forEach(m=>add(m,'s'));(f?.leagues||[]).forEach(l=>(l.matches||[]).forEach(m=>add(m,'f')));(e?.events||[]).forEach(m=>add(m,'e'));return out.filter(x=>x.home&&x.away).slice(0,20)}

export function diagnostics(){return Object.entries(status).map(([name,v])=>({name,...v}));}
