const F='https://www.fotmob.com';
const S='https://api.sofascore.com/api/v1';
const E='https://site.api.espn.com/apis/site/v2/sports/soccer/all';
const cache=new Map(),status={};
const headers={Accept:'application/json','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36'};
const isoDay=x=>{const d=new Date(x);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)};
const n=x=>{if(x&&typeof x==='object')x=x.current??x.normaltime??x.displayValue??x.value??x.score;if(typeof x==='string'&&x.includes('/'))x=x.split('/')[0];const m=String(x??'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null};
const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|afc|sk|club|cf|fk|sc|ac|as|sv|bk|kv)\b/g,'').replace(/[^a-z0-9]/g,'');
const get=async(url,provider='SofaScore')=>{const k=provider+'|'+url;if(cache.has(k))return cache.get(k);const p=(async()=>{try{const r=await fetch(url,{headers});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();status[provider]={ok:true,error:''};return j}catch(e){status[provider]={ok:false,error:String(e?.message||e)};return null}})();cache.set(k,p);return p};
const league=e=>{const t=e?.tournament||{},u=t?.uniqueTournament||t?.uniqueTournamentInfo;return u?.name||t?.name||u?.slug||t?.slug||e?.season?.name||'Altra competizione'};
const sofa=e=>{const h=e?.homeTeam?.name,a=e?.awayTeam?.name;if(!h||!a||!e?.id)return null;return{id:'sofa-'+e.id,eventId:String(e.id),customId:e.customId||'',sofaIdHome:e.homeTeam?.id||null,sofaIdAway:e.awayTeam?.id||null,home:h,away:a,league:league(e),country:e?.tournament?.category?.name||'',time:e.startTimestamp?new Date(e.startTimestamp*1000).toISOString():e.startTime||'',status:String(e.status?.type||'').toLowerCase(),homeScore:n(e.homeScore),awayScore:n(e.awayScore),source:'SofaScore'}};
function fot(j,date){const out=[];const walk=o=>{if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(walk);return}const h=o.home?.name||o.homeTeam?.name,a=o.away?.name||o.awayTeam?.name,id=o.id;if(h&&a&&id){const tm=o.status?.utcTime||o.time||o.date||'',lg=typeof o.league==='string'?o.league:o.league?.name||o.tournament?.name||o.competition?.name||o.competition?.league?.name||'';if(isoDay(tm)===date)out.push({id:'fot-'+id,eventId:String(id),home:h,away:a,league:lg||'Altra competizione',country:o.league?.country||o.tournament?.country||'',time:tm,status:String(o.status?.type||'notstarted').toLowerCase(),source:'FotMob'})}Object.values(o).forEach(walk)};walk(j);const seen=new Set();return out.filter(x=>{const k=norm(x.home)+'|'+norm(x.away)+'|'+x.time;if(seen.has(k))return false;seen.add(k);return true})}
function espn(j,date){return(j?.events||[]).map(e=>{const c=e.competitions?.[0]?.competitors||[],h=c.find(x=>x.homeAway==='home')||c[0],a=c.find(x=>x.homeAway==='away')||c[1];if(!h?.team?.displayName||!a?.team?.displayName)return null;const tm=e.date||'',lg=e.league?.name||e.competition?.name||e.season?.displayName||'';return isoDay(tm)===date?{id:'espn-'+e.id,eventId:String(e.id),home:h.team.displayName,away:a.team.displayName,league:lg||'Altra competizione',country:'',time:tm,status:String(e.status?.type?.name||'notstarted').toLowerCase(),source:'ESPN'}:null}).filter(Boolean)}
function merge(rows,date){const m=new Map();for(const r of rows){if(!r.home||!r.away||isoDay(r.time)!==date)continue;const k=norm(r.home)+'|'+norm(r.away)+'|'+isoDay(r.time);if(!m.has(k)||r.source==='SofaScore')m.set(k,r)}return[...m.values()].sort((a,b)=>new Date(a.time)-new Date(b.time))}
export async function todayMatches(date){const [s,f,e]=await Promise.all([get(`${S}/sport/football/scheduled-events/${date}`,'SofaScore'),get(`${F}/api/data/matches?date=${date.replaceAll('-','')}`,'FotMob'),get(`${E}/scoreboard?dates=${date.replaceAll('-','')}`,'ESPN')]);const out=merge([...(s?.events||[]).map(sofa).filter(Boolean),...fot(f,date),...espn(e,date)],date);status.SofaScore={ok:Boolean(s?.events?.length),error:''};status.FotMob={ok:Boolean(f),error:''};status.ESPN={ok:Boolean(e),error:''};return out}
export function diagnostics(){return Object.entries(status).map(([name,x])=>({name,ok:Boolean(x?.ok),error:x?.error||''}))}
export function clearProviderCache(){cache.clear();for(const k of Object.keys(status))delete status[k]}
