const F='https://www.fotmob.com';
const S='https://api.sofascore.com/api/v1';
const E='https://site.api.espn.com/apis/site/v2/sports/soccer/all';
const cache=new Map(),status={};
export const PROVIDERS=['SofaScore','FotMob','ESPN'];
const n=x=>{if(x&&typeof x==='object')x=x.current??x.normaltime??x.displayValue??x.value??x.score;if(typeof x==='string'&&x.includes('/'))x=x.split('/')[0];const m=String(x??'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?+m[0]:null};
const norm=x=>String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|afc|sk|club|cf|fk|sc|ac|as|sv|bk|kv)\b/g,'').replace(/[^a-z0-9]/g,'');
const same=(a,b)=>{const x=norm(a),y=norm(b);return!!x&&!!y&&(x===y||x.includes(y)||y.includes(x))};
const isoDay=x=>{const d=new Date(x);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const key=v=>{const t=String(v||'').replace(/([a-z])([A-Z])/g,'$1 $2').toLowerCase().replace(/[_-]/g,' '),c=t.replace(/[^a-z0-9]/g,'');if(c==='totalshots'||/total shots|shot attempts|^shots$/.test(t))return'shots';if(/shots? on target|shots? on goal|on target/.test(t)||c==='shotsontarget')return'shotsOnTarget';if(/corner/.test(t))return'corners';if(/foul/.test(t))return'fouls';if(/yellow|booking|caution/.test(t))return'yellow';if(/offside/.test(t))return'offsides';if(/throw.?in/.test(t))return'throwIns';if(/save|goalkeeper save/.test(t))return'saves';if(/red card|redcard/.test(t))return'red';if(/expected goal|^xg/.test(t))return'xg';return null};
async function get(url,provider='SofaScore',headers={}){const k=provider+'|'+url;if(cache.has(k))return cache.get(k);const p=(async()=>{try{const r=await fetch(url,{headers:{Accept:'application/json',...headers}});const text=await r.text();if(!r.ok)throw Error('HTTP '+r.status);const j=JSON.parse(text);status[provider]={ok:true,error:''};return j}catch(e){status[provider]={ok:false,error:String(e?.message||e)};return null}})();cache.set(k,p);return p}
function leagueOf(e){const c=e?.tournament?.category?.name||e?.category?.name||e?.homeTeam?.country?.name||'';const l=e?.tournament?.name||e?.uniqueTournament?.name||e?.tournament?.uniqueTournament?.name||e?.league?.name||'';return l?`${c&&c!==l?c+' · ':''}${l}`:c||'Calcio';}
function statusType(e){return String(e?.status?.type||'').toLowerCase()}
function sofaEvent(e){const h=e?.homeTeam?.name,a=e?.awayTeam?.name;if(!h||!a||!e?.id)return null;const ts=e.startTimestamp?new Date(e.startTimestamp*1000).toISOString():e.startTime||'';return{id:'sofa-'+e.id,eventId:String(e.id),customId:e.customId||'',sofaIdHome:e.homeTeam?.id||null,sofaIdAway:e.awayTeam?.id||null,home:h,away:a,league:leagueOf(e),country:e?.tournament?.category?.name||'',time:ts,status:statusType(e),homeScore:n(e.homeScore),awayScore:n(e.awayScore),source:'SofaScore'};}
function fotMatches(j,date){const out=[];const walk=o=>{if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(walk);return}const h=o.home?.name||o.homeTeam?.name,a=o.away?.name||o.awayTeam?.name,id=o.id;if(h&&a&&id){const tm=o.status?.utcTime||o.time||o.date||'';if(!date||isoDay(tm)===date)out.push({id:'fot-'+id,eventId:String(id),home:h,away:a,league:o.league?.name||o.tournament?.name||o.competition?.name||'Calcio',country:o.league?.country||o.tournament?.country||'',time:tm,status:String(o.status?.type||'notstarted').toLowerCase(),source:'FotMob'})}Object.values(o).forEach(walk)};walk(j);const seen=new Set();return out.filter(x=>{const k=x.home+'|'+x.away+'|'+x.time;if(seen.has(k))return false;seen.add(k);return true})}
function espnMatches(j,date){return(j?.events||[]).map(e=>{const c=e.competitions?.[0]?.competitors||[],h=c.find(x=>x.homeAway==='home')||c[0],a=c.find(x=>x.homeAway==='away')||c[1];if(!h?.team?.displayName||!a?.team?.displayName)return null;const tm=e.date||'';return isoDay(tm)===date?{id:'espn-'+e.id,eventId:String(e.id),home:h.team.displayName,away:a.team.displayName,league:e.league?.name||e.season?.slug||'Calcio',country:'',time:tm,status:String(e.status?.type?.name||'notstarted').toLowerCase(),source:'ESPN'}:null}).filter(Boolean)}
function mergeMatches(rows,date){const m=new Map();for(const r of rows){if(!r.home||!r.away)continue;if(date&&isoDay(r.time)!==date)continue;const k=norm(r.home)+'|'+norm(r.away)+'|'+isoDay(r.time);if(!m.has(k)||r.source==='SofaScore')m.set(k,r)}return[...m.values()].sort((a,b)=>new Date(a.time)-new Date(b.time))}
export async function todayMatches(date=today()){
 const [s1,s2,f,e]=await Promise.all([
  get(`${S}/sport/football/scheduled-events/${date}`,'SofaScore'),
  get(`${S}/sport/football/scheduled-events/${date}/inverse`,'SofaScore'),
  get(`${F}/api/data/matches?date=${date.replaceAll('-','')}`,'FotMob'),
  get(`${E}/scoreboard?dates=${date.replaceAll('-','')}`,'ESPN')
 ]);
 const rows=[...(s1?.events||[]).map(sofaEvent).filter(Boolean),...(s2?.events||[]).map(sofaEvent).filter(Boolean),...fotMatches(f,date),...espnMatches(e,date)];
 const out=mergeMatches(rows,date);status.SofaScore={ok:Boolean(s1?.events?.length||s2?.events?.length),error:''};status.FotMob={ok:Boolean(f),error:''};status.ESPN={ok:Boolean(e),error:''};return out;
}
function fromSofaHistory(events,name){return(events||[]).map(e=>{const h=e?.homeTeam?.name,a=e?.awayTeam?.name,hg=n(e?.homeScore),ag=n(e?.awayScore),st=statusType(e);if(!h||!a||hg==null||ag==null||!['finished','ended','afterpenalties','afterextra'].includes(st))return null;if(same(h,name))return{id:'sofa-'+e.id,eventId:String(e.id),sofaId:String(e.id),team:name,opp:a,home:true,gf:hg,ga:ag,time:e.startTimestamp?new Date(e.startTimestamp*1000).toISOString():e.startTime||'',sofaEvent:e};if(same(a,name))return{id:'sofa-'+e.id,eventId:String(e.id),sofaId:String(e.id),team:name,opp:h,home:false,gf:ag,ga:hg,time:e.startTimestamp?new Date(e.startTimestamp*1000).toISOString():e.startTime||'',sofaEvent:e};return null}).filter(Boolean)}
async function teamHistory(name,sofaId){if(!sofaId)return[];const pages=await Promise.all(Array.from({length:4},(_,p)=>get(`${S}/team/${sofaId}/events/last/${p}`,'SofaScore')));const m=new Map();for(const x of pages.flatMap(j=>fromSofaHistory(j?.events,name))){const k=x.eventId;if(!m.has(k))m.set(k,x)}return[...m.values()].sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,16)}
async function h2h(eventId){if(!eventId)return[];const j=await get(`${S}/event/${eventId}/h2h/events`,'SofaScore');return fromSofaHistory(j?.events,'__H2H_NEVER__')}
function h2hRaw(events,home,away){const out=[];for(const e of events||[]){const h=e?.homeTeam?.name,a=e?.awayTeam?.name,hg=n(e?.homeScore),ag=n(e?.awayScore),st=statusType(e);if(!h||!a||hg==null||ag==null||!['finished','ended','afterpenalties','afterextra'].includes(st))continue;if((same(h,home)&&same(a,away))||(same(h,away)&&same(a,home)))out.push({id:'sofa-'+e.id,eventId:String(e.id),team:home,opp:same(h,home)?a:h,home:same(h,home),gf:same(h,home)?hg:ag,ga:same(h,home)?ag:hg,time:e.startTimestamp?new Date(e.startTimestamp*1000).toISOString():e.startTime||'',sofaEvent:e,h2h:true});}return out.sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,10)}
async function eventStats(eventId,team){const j=await get(`${S}/event/${eventId}/statistics`,'SofaScore');const groups=(j?.statistics||[]).find(x=>String(x.period).toUpperCase()==='ALL')?.groups||[];const e=j?.event||{};const h=e.homeTeam?.name||'',a=e.awayTeam?.name||'';const o={};for(const g of groups)for(const r of g.statisticsItems||[]){const k=key(r.key||r.name||r.title),hv=n(r.homeValue??r.home),av=n(r.awayValue??r.away);if(k&&hv!=null&&av!=null)o[k]=same(h,team)?hv:same(a,team)?av:null}return o}
export async function enrichHistory(row,team){if(!row)return null;let data={};if(row.eventId&&row.id?.startsWith('sofa-')){try{data=await eventStats(row.eventId,team)}catch{}}return{...row,data}}
export async function findTeamIds(name){const q=encodeURIComponent(name);const [s,f]=await Promise.all([get(`${S}/search/all?q=${q}`,'SofaScore'),get(`${F}/api/data/search/suggest?term=${q}&hits=20&lang=en`,'FotMob')]);const sr=(s?.results||[]).filter(x=>String(x.entity?.type||'').toLowerCase()==='team'),st=sr.find(x=>same(x.entity?.name,name))||sr[0],fa=f?.results||f?.suggestions||[],ft=fa.find(x=>same(x.title||x.name||x.entity?.name,name))||fa.find(x=>String(x.type||x.entity?.type||'').toLowerCase()==='team')||fa[0];return{sofaId:st?.entity?.id||null,fotId:ft?.id||ft?.entity?.id||ft?.team?.id||null}}
export async function analyzeMatch(match){
 const hi=await findTeamIds(match.home),ai=await findTeamIds(match.away);
 const [hf,af,hh]=await Promise.all([teamHistory(match.home,hi.sofaId),teamHistory(match.away,ai.sofaId),h2h(match.eventId)]);
 const h2hRows=h2hRaw(hh?.length?hh:[],match.home,match.away);
 const chosenH=[...h2hRows,...hf.filter(x=>!h2hRows.some(y=>y.eventId===x.eventId))].slice(0,10);
 const chosenA=[...h2hRows.map(x=>({...x,team:match.away,opp:match.home,home:!x.home,gf:x.ga,ga:x.gf})),...af.filter(x=>!h2hRows.some(y=>y.eventId===x.eventId))].slice(0,10);
 const statsRows=await Promise.all(h2hRows.slice(0,6).map(x=>enrichHistory(x,match.home)));
 const hs=await Promise.all(chosenH.slice(0,8).map(x=>x.data?x:enrichHistory(x,match.home)));
 const as=await Promise.all(chosenA.slice(0,8).map(x=>x.data?x:enrichHistory(x,match.away)));
 return{...match,homeData:hi,awayData:ai,H:{form:chosenH,stats:hs.filter(Boolean)},A:{form:chosenA,stats:as.filter(Boolean)},h2h:h2hRows,loading:false,h2hCount:h2hRows.length,verifiedStats:statsRows.filter(x=>Object.keys(x?.data||{}).length).length};
}
export function diagnostics(){return Object.entries(status).map(([name,x])=>({name,ok:Boolean(x?.ok),error:x?.error||''}))}
export function clearProviderCache(){cache.clear();for(const k of Object.keys(status))delete status[k]}
