interface Env { DB: D1Database; }
type Hist={n:number;gf:number;ga:number;homeN:number;homeGF:number;homeGA:number;awayN:number;awayGF:number;awayGA:number};
type Match={home_team_id:number;away_team_id:number;home_goals:number;away_goals:number};
const empty=():Hist=>({n:0,gf:0,ga:0,homeN:0,homeGF:0,homeGA:0,awayN:0,awayGF:0,awayGA:0});
function add(h:Hist,gf:number,ga:number,home:boolean){h.n++;h.gf+=gf;h.ga+=ga;if(home){h.homeN++;h.homeGF+=gf;h.homeGA+=ga}else{h.awayN++;h.awayGF+=gf;h.awayGA+=ga}}
function avg(v:number,n:number,f:number){return n?v/n:f}
function features(h:Hist,a:Hist){const hf=avg(h.homeGF,h.homeN,avg(h.gf,h.n,1.35)),ha=avg(h.homeGA,h.homeN,avg(h.ga,h.n,1.35)),af=avg(a.awayGF,a.awayN,avg(a.gf,a.n,1.15)),aa=avg(a.awayGA,a.awayN,avg(a.ga,a.n,1.15));return [1,hf,ha,af,aa,hf-aa,af-ha,Math.min(h.n,20)/20,Math.min(a.n,20)/20]}
function softmax(z:number[]){const m=Math.max(...z),e=z.map(v=>Math.exp(Math.max(-30,Math.min(30,v-m)))),s=e.reduce((a,b)=>a+b,0);return e.map(v=>v/s)}
function dot(w:number[],x:number[]){let s=0;for(let i=0;i<x.length;i++)s+=w[i]*x[i];return s}
export async function runMLBacktest(env:Env,leagueName:string,minHistory:number){const league=await env.DB.prepare('SELECT id FROM leagues WHERE name=?').bind(leagueName).first<any>();if(!league)throw new Error(`Campionato non trovato: ${leagueName}`);const rows=await env.DB.prepare('SELECT home_team_id,away_team_id,home_goals,away_goals FROM matches WHERE league_id=? AND home_goals IS NOT NULL AND away_goals IS NOT NULL ORDER BY kickoff ASC,id ASC').bind(Number(league.id)).all<Match>();const hist=new Map<number,Hist>();const w=[new Array(9).fill(0),new Array(9).fill(0),new Array(9).fill(0)];let evaluated=0,correct=0,brier=0,logLoss=0;for(const m of rows.results||[]){const h=hist.get(Number(m.home_team_id))||empty(),a=hist.get(Number(m.away_team_id))||empty();if(h.n>=minHistory&&a.n>=minHistory){const x=features(h,a),p=softmax(w.map(v=>dot(v,x))),actual=Number(m.home_goals)>Number(m.away_goals)?0:Number(m.home_goals)===Number(m.away_goals)?1:2,pred=p[0]>=p[1]&&p[0]>=p[2]?0:p[2]>=p[0]&&p[2]>=p[1]?2:1;if(pred===actual)correct++;for(let c=0;c<3;c++){const err=(c===actual?1:0)-p[c];for(let j=0;j<x.length;j++)w[c][j]+=0.025*err*x[j]}brier+=(p[0]-(actual===0?1:0))**2+(p[1]-(actual===1?1:0))**2+(p[2]-(actual===2?1:0))**2;logLoss+=-Math.log(Math.max(1e-12,p[actual]));evaluated++}add(h,Number(m.home_goals),Number(m.away_goals),true);add(a,Number(m.away_goals),Number(m.home_goals),false);hist.set(Number(m.home_team_id),h);hist.set(Number(m.away_team_id),a)}const accuracy=evaluated?correct/evaluated:0,brierScore=evaluated?brier/evaluated:0,ll=evaluated?logLoss/evaluated:0;return{method:'online multinomial logistic regression',evaluated,accuracy,brier:brierScore,logLoss:ll,features:['gol fatti casa','gol subiti casa','gol fatti trasferta','gol subiti trasferta','differenziali offensivi/difensivi','volume storico']}}
