import type { IncomingMessage, ServerResponse } from 'node:http';

const SNAPSHOT_URL = 'https://raw.githubusercontent.com/anonimatoxx11xx-dev/match-probability-ai/main/data/api-football/latest.json';
const LEAGUES = new Set([39, 135, 140, 78, 61, 2]);
const LEAGUE_NAMES: Record<number, string> = {39:'Premier League',135:'Serie A',140:'La Liga',78:'Bundesliga',61:'Ligue 1',2:'Champions League'};

type Stats = {matches:number;gf:number;ga:number;shots:number;sot:number;corners:number;fouls:number;saves:number;cards:number;hm:number;hgf:number;hga:number;am:number;agf:number;aga:number};
type Team = {apiId:number;name:string;leagueId:number};
const empty = (): Stats => ({matches:0,gf:0,ga:0,shots:0,sot:0,corners:0,fouls:0,saves:0,cards:0,hm:0,hgf:0,hga:0,am:0,agf:0,aga:0});
const n=(v:any)=>Number(v ?? 0)||0;
const clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
const key=(leagueId:number,apiId:number)=>`${leagueId}:${apiId}`;
function canon(s:string){const x=String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();const a:Record<string,string>={'internazionale':'inter','inter milan':'inter','fc internazionale milano':'inter','inter milano':'inter','ac milan':'milan','as roma':'roma','ssc napoli':'napoli','bayern munich':'fc bayern munchen','bayern munchen':'fc bayern munchen','borussia dortmund':'dortmund','manchester city fc':'manchester city','aston villa fc':'aston villa','porto fc':'fc porto','fc porto':'fc porto','villarreal cf':'villarreal'};return a[x]||x}
function tokens(s:string){return new Set(canon(s).split(' ').filter(x=>x.length>2&&!['fc','cf','kv','club','calcio'].includes(x)))}
function matchTeam(name:string,teams:Team[],leagueId?:number){const exact=canon(name);const pool=leagueId?teams.filter(t=>t.leagueId===leagueId):teams;const same=pool.filter(t=>canon(t.name)===exact);if(same.length)return same[0];const wanted=tokens(name);let best:Team|undefined,score=0;for(const t of pool){const tt=tokens(t.name);let hit=0;for(const x of wanted)if(tt.has(x))hit++;const denom=Math.max(wanted.size,tt.size);const s=denom?hit/denom:0;if(s>score){score=s;best=t}}return score>=0.7?best:null}

let snapshotCache:any=null;
let snapshotAt=0;
async function snapshot(){if(snapshotCache&&Date.now()-snapshotAt<300000)return snapshotCache;const r=await fetch(SNAPSHOT_URL,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`Snapshot HTTP ${r.status}`);const x=await r.json();if(!x?.generatedAt||!Array.isArray(x.fixtures))throw new Error('Snapshot non valido');snapshotCache=x;snapshotAt=Date.now();return x}
function completed(f:any){return f?.goals?.home!=null&&f?.goals?.away!=null}
function updateStats(map:Map<string,Stats>,f:any){const lid=n(f.league?.id),h=n(f.home?.id),a=n(f.away?.id);if(!lid||!h||!a||f.goals?.home==null||f.goals?.away==null)return;const hs=f.stats?.home||{},as=f.stats?.away||{},H=map.get(key(lid,h))||empty(),A=map.get(key(lid,a))||empty();H.matches++;H.gf+=n(f.goals.home);H.ga+=n(f.goals.away);H.shots+=n(hs.shots);H.sot+=n(hs.sot);H.corners+=n(hs.corners);H.fouls+=n(hs.fouls);H.saves+=n(hs.saves);H.cards+=n(hs.cards);H.hm++;H.hgf+=n(f.goals.home);H.hga+=n(f.goals.away);A.matches++;A.gf+=n(f.goals.away);A.ga+=n(f.goals.home);A.shots+=n(as.shots);A.sot+=n(as.sot);A.corners+=n(as.corners);A.fouls+=n(as.fouls);A.saves+=n(as.saves);A.cards+=n(as.cards);A.am++;A.agf+=n(f.goals.away);A.aga+=n(f.goals.home);map.set(key(lid,h),H);map.set(key(lid,a),A)}
function buildStats(snap:any){const map=new Map<string,Stats>();for(const f of snap.fixtures||[]){if(completed(f)&&LEAGUES.has(n(f.league?.id)))updateStats(map,f)}return map}
function predict(h:Stats,a:Stats){const hw=h.hm/(h.hm+8),aw=a.am/(a.am+8);const hgf=h.hm?h.hgf/h.hm:h.matches?h.gf/h.matches:1.35,hga=h.hm?h.hga/h.hm:h.matches?h.ga/h.matches:1.35,agf=a.am?a.agf/a.am:a.matches?a.gf/a.matches:1.15,aga=a.am?a.aga/a.am:a.matches?a.ga/a.matches:1.15,ogf=h.matches?h.gf/h.matches:1.35,oga=h.matches?h.ga/h.matches:1.35,oagf=a.matches?a.gf/a.matches:1.15,oaga=a.matches?a.ga/a.matches:1.15;const lh=clamp(((hgf*hw+ogf*(1-hw))*.55+(aga*aw+oaga*(1-aw))*.45)*1.05,.2,3.8),la=clamp(((agf*aw+oagf*(1-aw))*.55+(hga*hw+oga*(1-hw))*.45)*.95,.15,3.5);const pois=(l:number,k:number)=>{let p=Math.exp(-l);for(let i=1;i<=k;i++)p*=l/i;return p};const dh=Array.from({length:9},(_,k)=>pois(lh,k)),da=Array.from({length:9},(_,k)=>pois(la,k)),sh=dh.reduce((x,y)=>x+y,0),sa=da.reduce((x,y)=>x+y,0);const score:number[][]=Array.from({length:9},()=>Array(9).fill(0));let home=0,draw=0,away=0;for(let i=0;i<9;i++)for(let j=0;j<9;j++){const p=dh[i]/sh*da[j]/sa;score[i][j]=p;if(i>j)home+=p;else if(i===j)draw+=p;else away+=p}const sum=(fn:(i:number,j:number)=>boolean)=>{let z=0;for(let i=0;i<9;i++)for(let j=0;j<9;j++)if(fn(i,j))z+=score[i][j];return z};const cs:any[]=[];for(let i=0;i<=5;i++)for(let j=0;j<=5;j++)cs.push({score:`${i}-${j}`,probability:score[i][j]});cs.sort((x,y)=>y.probability-x.probability);const min=Math.min(h.matches,a.matches),rel=clamp(.35+Math.min(min,30)/30*.65,.35,1);return{expectedGoals:{home:lh,away:la,total:lh+la},result:{home,draw,away},doubleChance:{'1X':home+draw,'X2':draw+away,'12':home+away},drawNoBet:{home:home/(home+away||1),away:away/(home+away||1),drawRefund:draw},markets:{over05:sum((i,j)=>i+j>=1),under05:sum((i,j)=>i+j<1),over15:sum((i,j)=>i+j>=2),under15:sum((i,j)=>i+j<2),over25:sum((i,j)=>i+j>=3),under25:sum((i,j)=>i+j<3),over35:sum((i,j)=>i+j>=4),under35:sum((i,j)=>i+j<4),over45:sum((i,j)=>i+j>=5),under45:sum((i,j)=>i+j<5),bttsYes:sum((i,j)=>i>0&&j>0),bttsNo:sum((i,j)=>i===0||j===0)},correctScores:cs.slice(0,10),expectedStats:{shots:h.matches&&a.matches?h.shots/h.matches+a.shots/a.matches:0,sot:h.matches&&a.matches?h.sot/h.matches+a.sot/a.matches:0,corners:h.matches&&a.matches?h.corners/h.matches+a.corners/a.matches:0,fouls:h.matches&&a.matches?h.fouls/h.matches+a.fouls/a.matches:0,saves:h.matches&&a.matches?h.saves/h.matches+a.saves/a.matches:0,cards:h.matches&&a.matches?h.cards/h.matches+a.cards/a.matches:0},dataQuality:{homeMatches:h.matches,awayMatches:a.matches,minMatches:min,level:min>=20?'high':min>=8?'medium':'low',reliability:rel},reliability:rel,model:'Poisson + home/away splits + historical team averages + home advantage'}}
function metric(probs:number[],actual:number){return probs.reduce((s,p,i)=>s+(p-(i===actual?1:0))**2,0)}
function backtestPoisson(snap:any,leagueName:string,minHistory:number){const lid=Number(Object.entries(LEAGUE_NAMES).find(([,v])=>v===leagueName)?.[0]||0);const fs=(snap.fixtures||[]).filter((f:any)=>completed(f)&&n(f.league?.id)===lid).sort((a:any,b:any)=>new Date(a.date||0).getTime()-new Date(b.date||0).getTime());const m=new Map<string,Stats>();let evaluated=0,correct=0,brier=0,logLoss=0;for(const f of fs){const h=m.get(key(lid,n(f.home?.id))),a=m.get(key(lid,n(f.away?.id)));if(h&&a&&h.matches>=minHistory&&a.matches>=minHistory){const p=predict(h,a).result,arr=[p.home,p.draw,p.away],actual=n(f.goals.home)>n(f.goals.away)?0:n(f.goals.home)===n(f.goals.away)?1:2;brier+=metric(arr,actual);logLoss-=Math.log(Math.max(arr[actual],1e-9));if(arr.indexOf(Math.max(...arr))===actual)correct++;evaluated++}updateStats(m,f)}return{method:'walk-forward',evaluated,accuracy:evaluated?correct/evaluated:0,brier:evaluated?brier/evaluated:0,logLoss:evaluated?logLoss/evaluated:0}}
function backtestML(snap:any,leagueName:string,minHistory:number){const lid=Number(Object.entries(LEAGUE_NAMES).find(([,v])=>v===leagueName)?.[0]||0);const fs=(snap.fixtures||[]).filter((f:any)=>completed(f)&&n(f.league?.id)===lid).sort((a:any,b:any)=>new Date(a.date||0).getTime()-new Date(b.date||0).getTime());const m=new Map<string,Stats>(),w=Array.from({length:3},()=>Array(11).fill(0));const feats=['home attack','home defence','away attack','away defence','home form','away form','goal differential','home shots','away shots'];let evaluated=0,correct=0,brier=0,logLoss=0;const features=(h:Stats,a:Stats)=>{const v=[h.hm?h.hgf/h.hm:1.35,h.hm?h.hga/h.hm:1.35,a.am?a.agf/a.am:1.15,a.am?a.aga/a.am:1.15,h.matches?(h.gf-h.ga)/h.matches:0,a.matches?(a.gf-a.ga)/a.matches:0,(h.matches?h.gf-h.ga:0)-(a.matches?a.gf-a.ga:0),h.matches?h.shots/h.matches:0,a.matches?a.shots/a.matches:0];return [1,...v.map((x,i)=>i>=7?x/10:x)]};const soft=(z:number[])=>{const e=z.map(v=>Math.exp(Math.max(-20,Math.min(20,v)))),s=e.reduce((a,b)=>a+b,0);return e.map(v=>v/s)};const dot=(r:number[],x:number[])=>r.reduce((s,v,i)=>s+v*x[i],0);const train=(x:number[],y:number)=>{const p=soft(w.map(r=>dot(r,x))),lr=.03,l2=.0005;for(let c=0;c<3;c++){const g=(c===y?1:0)-p[c];for(let j=0;j<x.length;j++)w[c][j]=(1-lr*l2)*w[c][j]+lr*g*x[j]}};for(const f of fs){const h=m.get(key(lid,n(f.home?.id))),a=m.get(key(lid,n(f.away?.id)));if(h&&a&&h.matches>=minHistory&&a.matches>=minHistory){const x=features(h,a),p=soft(w.map(r=>dot(r,x))),actual=n(f.goals.home)>n(f.goals.away)?0:n(f.goals.home)===n(f.goals.away)?1:2;brier+=metric(p,actual);logLoss-=Math.log(Math.max(p[actual],1e-9));if(p.indexOf(Math.max(...p))===actual)correct++;evaluated++;train(x,actual)}updateStats(m,f)}return{method:'walk-forward-online-logistic',evaluated,accuracy:evaluated?correct/evaluated:0,brier:evaluated?brier/evaluated:0,logLoss:evaluated?logLoss/evaluated:0,features:feats}}

async function espn(date:string){const d=date.replace(/-/g,''),leagues:[string,string][]=[['ita.1','Serie A'],['eng.1','Premier League'],['esp.1','La Liga'],['ger.1','Bundesliga'],['fra.1','Ligue 1'],['uefa.champions','Champions League']],all:any[]=[];for(const [slug,name] of leagues){const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/soccer/${slug}/scoreboard?dates=${d}`);if(!r.ok)continue;const x=await r.json() as any;for(const e of x.events||[]){const c=e.competitions?.[0],cs=c?.competitors||[],home=cs.find((z:any)=>z.homeAway==='home'),away=cs.find((z:any)=>z.homeAway==='away');if(home&&away)all.push({fixtureId:e.id,date:e.date,league:{name,country:''},status:c?.status?.type?.shortDetail||'NS',homeApiId:null,awayApiId:null,homeName:home.team?.displayName||home.team?.name,awayName:away.team?.displayName||away.team?.name})}}return all}
async function apiFootball(date:string){const k=process.env.API_FOOTBALL_KEY;if(!k)throw new Error('Nessun dato ESPN disponibile e API_FOOTBALL_KEY non configurata');const r=await fetch(`https://v3.football.api-sports.io/fixtures?date=${encodeURIComponent(date)}&timezone=Europe%2FRome`,{headers:{'x-apisports-key':k,accept:'application/json'}});if(!r.ok)throw new Error(`API-Football HTTP ${r.status}`);const x=await r.json() as any;return(x.response||[]).filter((f:any)=>LEAGUES.has(n(f.league?.id))).map((f:any)=>({fixtureId:f.fixture?.id,date:f.fixture?.date,league:{name:f.league?.name,country:f.league?.country},status:f.fixture?.status?.short||'NS',homeApiId:f.teams?.home?.id,awayApiId:f.teams?.away?.id,homeName:f.teams?.home?.name,awayName:f.teams?.away?.name}))}
function romeDate(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return `${p.find(x=>x.type==='year')?.value}-${p.find(x=>x.type==='month')?.value}-${p.find(x=>x.type==='day')?.value}`}
async function todayData(snap:any,date:string){let fixtures:any[]=[];let source='ESPN';try{fixtures=await espn(date)}catch(_){fixtures=[]}if(!fixtures.length){fixtures=await apiFootball(date);source='API-Football'}const stats=buildStats(snap),teams=snap.teams as Team[];const out=fixtures.map(f=>{const lid=Number(Object.entries(LEAGUE_NAMES).find(([,v])=>v===f.league?.name)?.[0]||0);const h=(f.homeApiId?teams.find(t=>n(t.apiId)===n(f.homeApiId)&&(!lid||t.leagueId===lid)):null)||matchTeam(f.homeName,teams,lid);const a=(f.awayApiId?teams.find(t=>n(t.apiId)===n(f.awayApiId)&&(!lid||t.leagueId===lid)):null)||matchTeam(f.awayName,teams,lid);const hs=h?stats.get(key(h.leagueId,h.apiId)):null,as=a?stats.get(key(a.leagueId,a.apiId)):null;let prediction=null,reason=null;if(hs&&as)prediction=predict(hs,as);else reason=h&&a?'Statistiche storiche insufficienti':'Squadra non ancora associata ai dati storici';return{fixtureId:f.fixtureId,date:f.date,league:f.league,status:f.status||'NS',home:{id:h?.apiId??null,name:f.homeName},away:{id:a?.apiId??null,name:f.awayName},prediction,reason,source}});out.sort((a,b)=>new Date(a.date).getTime()-new Date(b.date).getTime());return{date,timezone:'Europe/Rome',source,matches:out.length,fixtures:out}}
function send(res:ServerResponse,status:number,data:any,cache=0){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('access-control-allow-origin','*');res.setHeader('access-control-allow-methods','GET,POST,OPTIONS');res.setHeader('access-control-allow-headers','content-type');if(cache)res.setHeader('cache-control',`public, s-maxage=${cache}, stale-while-revalidate=${Math.min(cache*2,3600)}`);res.end(JSON.stringify(data))}
async function body(req:IncomingMessage){let s='';for await(const c of req as any)s+=c;return s?JSON.parse(s):{}}

export default async function handler(req:IncomingMessage,res:ServerResponse){if(req.method==='OPTIONS')return send(res,200,{ok:true});const raw=(req.url||'').split('?')[0].replace(/^\/api\/?/,'').replace(/\/$/,'');const q=new URL(req.url||'http://localhost',`http://${req.headers.host||'localhost'}`).searchParams;try{const snap=await snapshot();
if(raw==='health')return send(res,200,{ok:true,service:'match-probability-ai',version:'vercel-1.0.0',backend:'Vercel Functions'});
if(raw==='provider/test')return send(res,200,{ok:true,provider:'ESPN primary + API-Football fallback',configured:Boolean(process.env.API_FOOTBALL_KEY)});
if(raw==='data/status')return send(res,200,{ok:true,matches:(snap.fixtures||[]).filter(completed).length,teamsWithStats:buildStats(snap).size,generatedAt:snap.generatedAt,season:snap.season,mode:snap.mode},3600);
if(raw==='leagues')return send(res,200,snap.leagues||[],3600);
if(raw==='teams'){const league=q.get('league');const list=(snap.teams||[]).filter((t:any)=>!league||LEAGUE_NAMES[n(t.leagueId)]===league).map((t:any)=>({id:t.apiId,name:t.name,league:LEAGUE_NAMES[n(t.leagueId)]})).sort((a:any,b:any)=>a.name.localeCompare(b.name));return send(res,200,list,3600)}
if(raw==='today'||raw==='warm'){const d=await todayData(snap,q.get('date')||romeDate());return send(res,200,d,raw==='today'?300:60)}
if(raw==='predict'){let hv=q.get('home'),av=q.get('away');if(req.method==='POST'){const b=await body(req);hv=String(b.homeTeamId??b.home??'');av=String(b.awayTeamId??b.away??'')}const teams=snap.teams as Team[];const find=(v:string|null)=>{if(!v)return null;const id=Number(v);if(Number.isFinite(id)&&id>0)return teams.find(t=>t.apiId===id)||null;return teams.find(t=>canon(t.name)===canon(v))||matchTeam(v,teams)};const h=find(hv),a=find(av);if(!h||!a||h.apiId===a.apiId)return send(res,400,{error:'Squadre home/away non valide'});const stats=buildStats(snap),hs=stats.get(key(h.leagueId,h.apiId)),as=stats.get(key(a.leagueId,a.apiId));if(!hs||!as)return send(res,404,{error:'Statistiche squadra non disponibili'});return send(res,200,{homeTeam:h.name,awayTeam:a.name,...predict(hs,as)},300)}
if(raw==='simulate'&&req.method==='POST'){const b=await body(req),teams=snap.teams as Team[];const find=(v:any)=>{const id=Number(v);return Number.isFinite(id)&&id>0?teams.find(t=>t.apiId===id):teams.find(t=>canon(t.name)===canon(String(v||'')))};const h=find(b.homeTeamId??b.home),a=find(b.awayTeamId??b.away);if(!h||!a)return send(res,400,{error:'Squadre non valide'});const s=buildStats(snap),hs=s.get(key(h.leagueId,h.apiId)),as=s.get(key(a.leagueId,a.apiId));if(!hs||!as)return send(res,404,{error:'Statistiche non disponibili'});const base=predict(hs,as),runs=clamp(Math.round(Number(b.runs||10000)),1000,100000);let hw=0,d=0,aw=0,o=0;const sample=(l:number)=>{const L=Math.exp(-l);let k=0,p=1;do{k++;p*=Math.random()}while(p>L&&k<20);return k-1};for(let i=0;i<runs;i++){const x=sample(base.expectedGoals.home),y=sample(base.expectedGoals.away);if(x>y)hw++;else if(x===y)d++;else aw++;if(x+y>=3)o++}return send(res,200,{homeTeam:h.name,awayTeam:a.name,runs,homeWin:hw/runs,draw:d/runs,awayWin:aw/runs,over25:o/runs,expectedGoals:base.expectedGoals})}
if(raw==='backtest'||raw==='ml/backtest'){const league=q.get('league')||'Serie A',min=Math.max(1,Number(q.get('minHistory')||3));const r=raw==='backtest'?backtestPoisson(snap,league,min):backtestML(snap,league,min);return send(res,200,r,1800)}
return send(res,404,{error:'Not found'});}catch(e){return send(res,500,{error:e instanceof Error?e.message:String(e)})}}
