const SNAPSHOT_URL='https://raw.githubusercontent.com/anonimatoxx11xx-dev/match-probability-ai/main/data/api-football/latest.json';
const LEAGUES:any={'Serie A':135,'Premier League':39,'La Liga':140,'Bundesliga':78,'Ligue 1':61,'Champions League':2};
const n=(x:any)=>Number(x??0)||0;
const key=(l:number,t:number)=>`${l}:${t}`;
type S={m:number;gf:number;ga:number;hm:number;hgf:number;hga:number;am:number;agf:number;aga:number};
const empty=():S=>({m:0,gf:0,ga:0,hm:0,hgf:0,hga:0,am:0,agf:0,aga:0});
function add(map:Map<string,S>,f:any){const l=n(f.league?.id),h=n(f.home?.id),a=n(f.away?.id);if(!l||!h||!a||f.goals?.home==null||f.goals?.away==null)return;let H=map.get(key(l,h))||empty(),A=map.get(key(l,a))||empty();H.m++;H.gf+=n(f.goals.home);H.ga+=n(f.goals.away);H.hm++;H.hgf+=n(f.goals.home);H.hga+=n(f.goals.away);A.m++;A.gf+=n(f.goals.away);A.ga+=n(f.goals.home);A.am++;A.agf+=n(f.goals.away);A.aga+=n(f.goals.home);map.set(key(l,h),H);map.set(key(l,a),A)}
function pred(h:S,a:S){const hw=h.hm/(h.hm+8),aw=a.am/(a.am+8);const hgf=h.hm?h.hgf/h.hm:1.35,hga=h.hm?h.hga/h.hm:1.35,agf=a.am?a.agf/a.am:1.15,aga=a.am?a.aga/a.am:1.15;const lh=Math.max(.2,Math.min(3.8,((hgf*hw+(h.m?h.gf/h.m:1.35)*(1-hw))*.55+(aga*aw+(a.m?a.ga/a.m:1.15)*(1-aw))*.45)*1.05));const la=Math.max(.15,Math.min(3.5,((agf*aw+(a.m?a.gf/a.m:1.15)*(1-aw))*.55+(hga*hw+(h.m?h.ga/h.m:1.35)*(1-hw))*.45)*.95));const p=(l:number,k:number)=>{let x=Math.exp(-l);for(let i=1;i<=k;i++)x*=l/i;return x};const ph=Array.from({length:9},(_,i)=>p(lh,i)),pa=Array.from({length:9},(_,i)=>p(la,i));const sh=ph.reduce((a,b)=>a+b,0),sa=pa.reduce((a,b)=>a+b,0);let r=[0,0,0];for(let i=0;i<9;i++)for(let j=0;j<9;j++){const x=ph[i]/sh*pa[j]/sa;i>j?r[0]+=x:i===j?r[1]+=x:r[2]+=x}return r}
function metric(p:number[],y:number){return p.reduce((s,x,i)=>s+(x-(i===y?1:0))**2,0)}
export default async function handler(req:any,res:any){try{const u=new URL(req.url||'http://localhost',`http://${req.headers?.host||'localhost'}`),league=u.searchParams.get('league')||'Serie A',min=Math.max(1,Number(u.searchParams.get('minHistory')||3)),lid=LEAGUES[league];if(!lid)return res.status(400).json({error:'Campionato non valido'});const rr=await fetch(SNAPSHOT_URL,{headers:{accept:'application/json'}});if(!rr.ok)throw new Error(`Snapshot HTTP ${rr.status}`);const snap=await rr.json();const fs=(snap.fixtures||[]).filter((f:any)=>n(f.league?.id)===lid&&f.goals?.home!=null&&f.goals?.away!=null).sort((a:any,b:any)=>new Date(a.date||0).getTime()-new Date(b.date||0).getTime());const m=new Map<string,S>(),out={method:'walk-forward',league,evaluated:0,accuracy:0,brier:0,logLoss:0};let correct=0;for(const f of fs){const h=m.get(key(lid,n(f.home?.id))),a=m.get(key(lid,n(f.away?.id)));if(h&&a&&h.m>=min&&a.m>=min){const p=pred(h,a),y=n(f.goals.home)>n(f.goals.away)?0:n(f.goals.home)===n(f.goals.away)?1:2;out.brier+=metric(p,y);out.logLoss-=Math.log(Math.max(p[y],1e-9));if(p.indexOf(Math.max(...p))===y)correct++;out.evaluated++}add(m,f)}out.accuracy=out.evaluated?correct/out.evaluated:0;if(out.evaluated){out.brier/=out.evaluated;out.logLoss/=out.evaluated}res.setHeader('Cache-Control','public, s-maxage=1800, stale-while-revalidate=3600');return res.status(200).json(out)}catch(e:any){return res.status(500).json({error:String(e?.message||e),code:'BACKTEST_FAILED'})}}