const SNAPSHOT_URL='https://raw.githubusercontent.com/anonimatoxx11xx-dev/match-probability-ai/main/data/api-football/latest.json';
const SOFA_BASES=['https://api.sofascore.app/api/v1','https://api.sofascore.com/api/v1'];
const ESPN_BASE='https://site.api.espn.com/apis/site/v2/sports/soccer';
const LEAGUES:any={'Premier League':39,'Serie A':135,'La Liga':140,'LaLiga':140,'Bundesliga':78,'Ligue 1':61,'UEFA Champions League':2,'Champions League':2,'Championship':0,'EFL Cup':0,'Carabao Cup':0};
const ESPN_LEAGUES:any={'eng.1':['Premier League',39],'ita.1':['Serie A',135],'esp.1':['La Liga',140],'ger.1':['Bundesliga',78],'fra.1':['Ligue 1',61],'uefa.champions':['Champions League',2],'eng.2':['Championship',0],'eng.league_cup':['EFL Cup',0]};
type S={matches:number;gf:number;ga:number;hm:number;hgf:number;hga:number;am:number;agf:number;aga:number;shots:number;sot:number;corners:number;fouls:number;saves:number;cards:number};
const empty=():S=>({matches:0,gf:0,ga:0,hm:0,hgf:0,hga:0,am:0,agf:0,aga:0,shots:0,sot:0,corners:0,fouls:0,saves:0,cards:0});
const n=(v:any)=>Number(v??0)||0;
const clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
const canon=(s:any)=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
async function get(url:string){const r=await fetch(url,{headers:{accept:'application/json','user-agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function sofa(path:string){let e:any;for(const b of SOFA_BASES)try{return await get(b+path)}catch(x){e=x}throw e||new Error('SofaScore unavailable')}
function add(m:Map<string,S>,key:string,g:number,ga:number,home:boolean,stats:any={}){const s=m.get(key)||empty();s.matches++;s.gf+=g;s.ga+=ga;if(home){s.hm++;s.hgf+=g;s.hga+=ga}else{s.am++;s.agf+=g;s.aga+=ga}s.shots+=n(stats.shots);s.sot+=n(stats.sot);s.corners+=n(stats.corners);s.fouls+=n(stats.fouls);s.saves+=n(stats.saves);s.cards+=n(stats.cards);m.set(key,s)}
function build(snap:any){const m=new Map<string,S>();for(const f of snap.fixtures||[]){if(f?.goals?.home==null||f?.goals?.away==null)continue;const lid=n(f.league?.id),h=n(f.home?.id),a=n(f.away?.id);if(!lid||!h||!a)continue;add(m,`${lid}:${h}`,n(f.goals.home),n(f.goals.away),true,f.stats?.home||{});add(m,`${lid}:${a}`,n(f.goals.away),n(f.goals.home),false,f.stats?.away||{})}return m}
function team(snap:any,name:string,lid:number){const wanted=canon(name).split(' ').filter(x=>x.length>2);let best:any=null,score=0;for(const t of snap.teams||[]){if(n(t.leagueId)!==lid)continue;const got=canon(t.name).split(' ');const hit=wanted.filter(x=>got.includes(x)).length;const q=Math.max(wanted.length,got.length)?hit/Math.max(wanted.length,got.length):0;if(q>score){score=q;best=t}}return score>=.5?best:null}
function poisson(l:number,k:number){let p=Math.exp(-l);for(let i=1;i<=k;i++)p*=l/i;return p}
function predict(h:S,a:S){const hw=h.matches?h.hm/(h.matches+8):.5,aw=a.matches?a.am/(a.matches+8):.5,hgf=h.hm?h.hgf/h.hm:1.35,hga=h.hm?h.hga/h.hm:1.35,agf=a.am?a.agf/a.am:1.15,aga=a.am?a.aga/a.am:1.15,lh=clamp(((hgf*.55+(h.matches?h.gf/h.matches:1.35)*.45)*hw+(aga*.45+(a.matches?a.ga/a.matches:1.15)*.55)*aw)*1.05,.2,3.8),la=clamp(((agf*.55+(a.matches?a.gf/a.matches:1.15)*.45)*aw+(hga*.45+(h.matches?h.ga/h.matches:1.35)*.55)*hw)*.95,.15,3.5),ph=Array.from({length:9},(_,k)=>poisson(lh,k)),pa=Array.from({length:9},(_,k)=>poisson(la,k)),sh=ph.reduce((a,b)=>a+b,0),sa=pa.reduce((a,b)=>a+b,0),score:any[][]=Array.from({length:9},()=>Array(9).fill(0));let home=0,draw=0,away=0;for(let i=0;i<9;i++)for(let j=0;j<9;j++){const p=ph[i]/sh*pa[j]/sa;score[i][j]=p;if(i>j)home+=p;else if(i===j)draw+=p;else away+=p}const sum=(f:(i:number,j:number)=>boolean)=>{let z=0;for(let i=0;i<9;i++)for(let j=0;j<9;j++)if(f(i,j))z+=score[i][j];return z};const cs:any[]=[];for(let i=0;i<6;i++)for(let j=0;j<6;j++)cs.push({score:`${i}-${j}`,probability:score[i][j]});cs.sort((a,b)=>b.probability-a.probability);const min=Math.min(h.matches,a.matches),rel=clamp(.35+Math.min(min,20)/20*.65,.35,1),avg=(x:number,c:number)=>c?x/c:null,stat=(x:number)=>x>0?x:null;return{expectedGoals:{home:lh,away:la,total:lh+la},result:{home,draw,away},doubleChance:{'1X':home+draw,X2:draw+away,'12':home+away},drawNoBet:{home:home/(home+away||1),away:away/(home+away||1),drawRefund:draw},markets:{over05:sum((i,j)=>i+j>=1),under05:sum((i,j)=>i+j<1),over15:sum((i,j)=>i+j>=2),under15:sum((i,j)=>i+j<2),over25:sum((i,j)=>i+j>=3),under25:sum((i,j)=>i+j<3),over35:sum((i,j)=>i+j>=4),under35:sum((i,j)=>i+j<4),over45:sum((i,j)=>i+j>=5),under45:sum((i,j)=>i+j<5),bttsYes:sum((i,j)=>i>0&&j>0),bttsNo:sum((i,j)=>i===0||j===0)},correctScores:cs.slice(0,5),expectedStats:{shots:h.matches&&a.matches?stat(avg(h.shots,h.matches)+avg(a.shots,a.matches)):null,sot:h.matches&&a.matches?stat(avg(h.sot,h.matches)+avg(a.sot,a.matches)):null,corners:h.matches&&a.matches?stat(avg(h.corners,h.matches)+avg(a.corners,a.matches)):null,fouls:h.matches&&a.matches?stat(avg(h.fouls,h.matches)+avg(a.fouls,a.matches)):null,saves:h.matches&&a.matches?stat(avg(h.saves,h.matches)+avg(a.saves,a.matches)):null,cards:h.matches&&a.matches?stat(avg(h.cards,h.matches)+avg(a.cards,a.matches)):null},dataQuality:{homeMatches:h.matches,awayMatches:a.matches,minMatches:min,level:min>=20?'high':min>=8?'medium':min>=3?'low':'very-low',reliability:rel},reliability:rel,model:min?'Historical form + Poisson + home/away splits':'Poisson prior fallback'}}
function dateRome(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return `${p.find(x=>x.type==='year')?.value}-${p.find(x=>x.type==='month')?.value}-${p.find(x=>x.type==='day')?.value}`}
async function sofaFixtures(date:string){const x=await sofa(`/sport/football/scheduled-events/${date}`);return(x.events||[]).filter((e:any)=>/Premier League|Serie A|LaLiga|La Liga|Bundesliga|Ligue 1|Champions League/i.test(String(e.uniqueTournament?.name||e.tournament?.name||''))).map((e:any)=>({fixtureId:String(e.id),date:new Date((e.startTimestamp||0)*1000).toISOString(),league:{name:e.uniqueTournament?.name||e.tournament?.name||'Calcio'},status:e.status?.description||e.status?.type||'Scheduled',home:{name:e.homeTeam?.name,sofaId:e.homeTeam?.id},away:{name:e.awayTeam?.name,sofaId:e.awayTeam?.id}}))}
async function espnFixtures(date:string){const compact=date.replace(/-/g,'');const out:any[]=[];for(const slug of Object.keys(ESPN_LEAGUES)){try{const x=await get(`${ESPN_BASE}/${slug}/scoreboard?dates=${compact}`);for(const e of x.events||[]){const c=e.competitions?.[0],h=c?.competitors?.find((z:any)=>z.homeAway==='home'),a=c?.competitors?.find((z:any)=>z.homeAway==='away');if(!h||!a)continue;out.push({fixtureId:String(e.id),date:e.date,league:{name:ESPN_LEAGUES[slug][0]},status:c.status?.type?.description||e.status?.type?.description||'Scheduled',home:{name:h.team?.displayName||h.team?.name},away:{name:a.team?.displayName||a.team?.name}})}}catch(err){console.error('ESPN league failed',slug,err)}}return out}
export default async function handler(req:any,res:any){try{const date=dateRome();let fs:any[]=[];let source='SofaScore';try{fs=await sofaFixtures(date)}catch(e){console.error('SofaScore schedule failed',e)}if(!fs.length){source='ESPN';fs=await espnFixtures(date)}const snap=await get(SNAPSHOT_URL).catch(()=>({fixtures:[],teams:[],generatedAt:null})),base=build(snap);if(!fs.length)throw new Error('Nessuna partita disponibile per oggi');const out=fs.map(f=>{const lk=Object.keys(LEAGUES).find(k=>f.league.name.includes(k));const lid=Number(LEAGUES[f.league.name]||LEAGUES[lk||'']||0),ht=lid?team(snap,f.home.name,lid):null,at=lid?team(snap,f.away.name,lid):null,h=base.get(`${lid}:${n(ht?.apiId)}`)||empty(),a=base.get(`${lid}:${n(at?.apiId)}`)||empty();return{fixtureId:f.fixtureId,date:f.date,league:f.league,status:f.status,home:f.home,away:f.away,prediction:predict(h,a)}});res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');res.status(200).json({ok:true,date,timezone:'Europe/Rome',source,matches:out.length,fixtures:out,historyAvailable:Boolean(snap.generatedAt)})}catch(e:any){console.error('TODAY_FAILED',e);res.status(500).json({ok:false,error:String(e?.message||e),code:'TODAY_FAILED'})}}
