const SNAPSHOT_URL = 'https://raw.githubusercontent.com/anonimatoxx11xx-dev/match-probability-ai/main/data/api-football/latest.json';
const ESPN_BASE = 'https://site.api.espn.com/apis/site/v2/sports/soccer';
const LEAGUES: any = { 'Premier League': 39, 'Serie A': 135, 'La Liga': 140, 'LaLiga': 140, Bundesliga: 78, 'Ligue 1': 61, 'UEFA Champions League': 2, 'Champions League': 2 };
const ESPN_LEAGUES: any = { 'eng.1': ['Premier League',39], 'ita.1': ['Serie A',135], 'esp.1': ['La Liga',140], 'ger.1': ['Bundesliga',78], 'fra.1': ['Ligue 1',61], 'uefa.champions': ['Champions League',2] };
type S = { matches:number; gf:number; ga:number; hm:number; hgf:number; hga:number; am:number; agf:number; aga:number; shots:number; sot:number; corners:number; fouls:number; saves:number; cards:number; statMatches:number };
const empty=():S=>({matches:0,gf:0,ga:0,hm:0,hgf:0,hga:0,am:0,agf:0,aga:0,shots:0,sot:0,corners:0,fouls:0,saves:0,cards:0,statMatches:0});
const n=(v:any)=>Number(v??0)||0;
const clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
const canon=(s:any)=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
async function get(url:string){const r=await fetch(url,{headers:{accept:'application/json','user-agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function hasStats(x:any){return ['shots','sot','corners','fouls','saves','cards'].some(k=>n(x?.[k])>0)}
function add(s:S,g:number,ga:number,home:boolean,stats:any={}){s.matches++;s.gf+=g;s.ga+=ga;if(home){s.hm++;s.hgf+=g;s.hga+=ga}else{s.am++;s.agf+=g;s.aga+=ga}if(hasStats(stats))s.statMatches++;s.shots+=n(stats.shots);s.sot+=n(stats.sot);s.corners+=n(stats.corners);s.fouls+=n(stats.fouls);s.saves+=n(stats.saves);s.cards+=n(stats.cards)}
function poisson(l:number,k:number){let p=Math.exp(-l);for(let i=1;i<=k;i++)p*=l/i;return p}
function fallbackMaps(snap:any){const by=new Map<string,S>(),base=empty();const fs=(snap.fixtures||[]).filter((f:any)=>f?.goals?.home!=null&&f?.goals?.away!=null).slice().sort((a:any,b:any)=>String(b.kickoff||b.date||'').localeCompare(String(a.kickoff||a.date||'')));const counts=new Map<string,number>();for(const f of fs){const hs=f.stats?.home||{},as=f.stats?.away||{},hg=n(f.goals.home),ag=n(f.goals.away),hk=canon(f.home?.name),ak=canon(f.away?.name);if(hk&&(counts.get(hk)||0)<20){const s=by.get(hk)||empty();add(s,hg,ag,true,hs);by.set(hk,s);counts.set(hk,(counts.get(hk)||0)+1)}if(ak&&(counts.get(ak)||0)<20){const s=by.get(ak)||empty();add(s,ag,hg,false,as);by.set(ak,s);counts.set(ak,(counts.get(ak)||0)+1)}for(const st of [hs,as])if(hasStats(st)){base.statMatches++;base.shots+=n(st.shots);base.sot+=n(st.sot);base.corners+=n(st.corners);base.fouls+=n(st.fouls);base.saves+=n(st.saves);base.cards+=n(st.cards)}}return {by,base}}
async function fixtures(date:string){const out:any[]=[],seen=new Set<string>();for(const slug of Object.keys(ESPN_LEAGUES)){try{const x=await get(`${ESPN_BASE}/${slug}/scoreboard?dates=${date.replace(/-/g,'')}`);for(const e of x.events||[]){const c=e.competitions?.[0],h=c?.competitors?.find((z:any)=>z.homeAway==='home'),a=c?.competitors?.find((z:any)=>z.homeAway==='away');if(!c||!h||!a)continue;const id=String(e.id);if(seen.has(id))continue;seen.add(id);out.push({fixtureId:id,date:e.date,league:{name:ESPN_LEAGUES[slug][0]},status:c.status?.type?.description||'Scheduled',slug,home:{name:h.team?.displayName||h.team?.name,espnId:h.team?.id},away:{name:a.team?.displayName||a.team?.name,espnId:a.team?.id}})}}catch(err){console.error('ESPN league failed',slug,err)}}return out.sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
async function recent(teamId:string,s:S,excludeId:string){if(!teamId)return false;try{const x=await get(`${ESPN_BASE}/all/teams/${teamId}/schedule?limit=100`),events=(x.events||[]).slice().sort((a:any,b:any)=>String(b.date||'').localeCompare(String(a.date||'')));let added=0;for(const e of events){if(String(e.id)===String(excludeId))continue;const c=e.competitions?.[0];if(!c)continue;const done=Boolean(e.status?.type?.completed||c.status?.type?.completed);if(!done)continue;const cs=c.competitors||[],me=cs.find((z:any)=>String(z.team?.id)===String(teamId)),op=cs.find((z:any)=>String(z.team?.id)!==String(teamId));if(!me||!op)continue;add(s,n(me.score),n(op.score),me.homeAway==='home');added++;if(s.matches>=10)break}return added>0}catch(_){return false}}
function predict(h:S,a:S,base:S){const priorH=1.50,priorA=1.15;const hGF=h.matches?h.gf/h.matches:priorH,hGA=h.matches?h.ga/h.matches:1.20,aGF=a.matches?a.gf/a.matches:priorA,aGA=a.matches?a.ga/a.matches:1.45;const hAtk=h.hm?h.hgf/h.hm:hGF,hDef=h.hm?h.hga/h.hm:hGA,aAtk=a.am?a.agf/a.am:aGF,aDef=a.am?a.aga/a.am:aGA;const hs=clamp(h.matches/8,0,1),as=clamp(a.matches/8,0,1);const lh=clamp(((hAtk*.60+aDef*.40)*(.82+.18*hs))*1.05*.94+priorH*.06,.35,3.8);const la=clamp(((aAtk*.60+hDef*.40)*(.82+.18*as))*.96*.94+priorA*.06,.30,3.5);const ph=Array.from({length:9},(_,k)=>poisson(lh,k)),pa=Array.from({length:9},(_,k)=>poisson(la,k)),sh=ph.reduce((x,y)=>x+y,0),sa=pa.reduce((x,y)=>x+y,0),score:number[][]=Array.from({length:9},()=>Array(9).fill(0));let home=0,draw=0,away=0;for(let i=0;i<9;i++)for(let j=0;j<9;j++){const p=ph[i]/sh*pa[j]/sa;score[i][j]=p;if(i>j)home+=p;else if(i===j)draw+=p;else away+=p}const sum=(fn:(i:number,j:number)=>boolean)=>{let z=0;for(let i=0;i<9;i++)for(let j=0;j<9;j++)if(fn(i,j))z+=score[i][j];return z};const cs:any[]=[];for(let i=0;i<6;i++)for(let j=0;j<6;j++)cs.push({score:`${i}-${j}`,probability:score[i][j]});cs.sort((x,y)=>y.probability-x.probability);const min=Math.min(h.matches,a.matches),rel=clamp(.35+Math.min(min,20)/20*.65,.35,1);const stat=(k:keyof Pick<S,'shots'|'sot'|'corners'|'fouls'|'saves'|'cards'>)=>{const hv=h.statMatches?n(h[k])/h.statMatches:null,av=a.statMatches?n(a[k])/a.statMatches:null,bv=base.statMatches?n(base[k])/base.statMatches:null;return hv!=null&&av!=null?hv+av:bv};const expectedStats={shots:stat('shots'),sot:stat('sot'),corners:stat('corners'),fouls:stat('fouls'),saves:stat('saves'),cards:stat('cards')};return{expectedGoals:{home:lh,away:la,total:lh+la},result:{home,draw,away},doubleChance:{'1X':home+draw,X2:draw+away,'12':home+away},drawNoBet:{home:home/(home+away||1),away:away/(home+away||1),drawRefund:draw},markets:{over05:sum((i,j)=>i+j>=1),under05:sum((i,j)=>i+j<1),over15:sum((i,j)=>i+j>=2),under15:sum((i,j)=>i+j<2),over25:sum((i,j)=>i+j>=3),under25:sum((i,j)=>i+j<3),over35:sum((i,j)=>i+j>=4),under35:sum((i,j)=>i+j<4),over45:sum((i,j)=>i+j>=5),under45:sum((i,j)=>i+j<5),bttsYes:sum((i,j)=>i>0&&j>0),bttsNo:sum((i,j)=>i===0||j===0)},correctScores:cs.slice(0,5),expectedStats,dataQuality:{homeMatches:h.matches,awayMatches:a.matches,minMatches:min,homeStatMatches:h.statMatches,awayStatMatches:a.statMatches,level:min>=20?'high':min>=8?'medium':min>=3?'low':'very-low',reliability:rel,statsFallback:h.statMatches===0||a.statMatches===0},reliability:rel,model:`Current form + home/away splits + Poisson${h.statMatches===0||a.statMatches===0?' + statistical baseline fallback':''}`}}
function dateRome(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return `${p.find(x=>x.type==='year')?.value}-${p.find(x=>x.type==='month')?.value}-${p.find(x=>x.type==='day')?.value}`}
export default async function handler(req:any,res:any){try{const date=dateRome(),fs=await fixtures(date),snap=await get(SNAPSHOT_URL).catch(()=>({fixtures:[]})),fm=fallbackMaps(snap);if(!fs.length)throw new Error('Nessuna partita disponibile per oggi');const out=await Promise.all(fs.map(async f=>{const h=clone(fm.by.get(canon(f.home.name))||empty()),a=clone(fm.by.get(canon(f.away.name))||empty());const [okH,okA]=await Promise.all([recent(f.home.espnId,h,f.fixtureId),recent(f.away.espnId,a,f.fixtureId)]);const prediction=predict(h,a,fm.base);return{fixtureId:f.fixtureId,date:f.date,league:f.league,status:f.status,home:{name:f.home.name},away:{name:f.away.name},prediction,formSource:okH&&okA?'ESPN':'Snapshot/ESPN partial'}}));res.setHeader('Cache-Control','no-store,no-cache,must-revalidate,proxy-revalidate');res.setHeader('CDN-Cache-Control','no-store');res.status(200).json({ok:true,date,timezone:'Europe/Rome',source:'ESPN',matches:out.length,fixtures:out,historyAvailable:Boolean(snap.generatedAt)})}catch(e:any){console.error('TODAY_FAILED',e);res.status(500).json({ok:false,error:String(e?.message||e),code:'TODAY_FAILED'})}}
function clone(s:S):S{return{...s}}
